### ISSUE TITLE
Avoid disk lock-up during use

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1071]
## :computer: System information

- **Data Safe Haven version:** 3.3.1

## :no_entry_sign: Problematic behaviour

When the OS disk is filled up, it can become impossible for Researchers to login. 

- Set up an SRE
- Fill the OS disk
- Attempt to log in as a Researcher

## :steam_locomotive: Possible workarounds, remediations or solutions

We should fix this by restricting how much of folders like `/tmp` researchers can use. This might involve the use of disk quotas.

**Comment by JimMadge** [comment]
Archwiki is a good resource for this: https://wiki.archlinux.org/title/Tmpfs

**Comment by craddm** [comment]
Should be addressed by #1672
