### ISSUE TITLE
Deprecate ARM templates

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1083]
#### :strawberry: Description/desired behaviour
We should replace (opaque) ARM templates with other options wherever possible.

#### :page_facing_up: Tasks
- `shm-dc-template.json`
- `shm-nps-template.json`
- ~`shm-vnet-template.json`~
- ~`sre-data-server-template.json`~
- `sre-mssql2019-server-template.json`
- `sre-rds-template.json`

**Comment by jemrobinson** [comment]
No ARM templates are used in the Pulumi version.

**Comment by craddm** [comment]
As this will not be a problem in Pulumi, we will not fix this one.
