### ISSUE TITLE
Add ClamAV definition mirror

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1237]
## :strawberry: Desired behaviour

ClamAV requests that you use your own mirror if multiple machines are trying to retrieve updates. They recommend [cvdupdate](https://pypi.org/project/cvdupdate/)

## :steam_locomotive: Possible workarounds, remediations or solutions

This is requested but not required

**Comment by craddm** [comment]
Perhaps in the Pulumi version, add as a container visible internally to provide a mirror on the private network.
