### ISSUE TITLE
Migration to AzureAD domain services

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1293]
## :white_check_mark: Checklist

- [ ] I have searched open and closed issues for duplicates.
- [ ] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [ ] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [ ] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Replace local domain controller with AzureAD domain services.

## :steam_locomotive: How could this be done?

This requires admin access to tenant with its own subscriptions.

**Comment by jemrobinson** [comment]
Potentially superceded by #1570 if this is implemented.

**Comment by craddm** [comment]
Won't fix for the Powershell codebase. Planned for implementation in the Pulumi update.
