### ISSUE TITLE
Improvements to documentation for deployment of SREs

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1295]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Some elements of the documentation for deploying SREs need to tidied up, brought up to date, and to have additional troubleshooting information added.

## :memo: Required documentation changes

- Include more comprehensive troubleshooting information in the Apache Guacamole section (e.g. refreshing VM list)
- Clarify that CoCalc needs an account to be created locally, on initial use via web browser, while CodiMD and Gitlab use existing user accounts using LDAP

**Comment by edwardchalstrey1** [comment]
> Clarify that CoCalc needs an account to be created locally, on initial use via web browser, while CodiMD and Gitlab use existing user accounts using LDAP

@craddm I Was about to open a separate issue as I found that CoCalc didn't work in my SRE deployment whereas GitLab and CodiMD do - did you get the same thing?


<img width="1068" alt="Screenshot 2022-10-13 at 13 45 38" src="https://user-images.githubusercontent.com/5486164/195624609-17a80fd5-9c8c-46d3-9989-d1293417503d.png">

**Comment by craddm** [comment]
No, CoCalc always worked on mine!

**Comment by jemrobinson** [comment]
If something in the `cloud-init` script for a Linux VM fails the job will terminate. As this is also the way we check for a completed installation, there's no easy way to catch this at deploy time.

The easiest fix is to deal the offending VM (CoCalc in this case) and rerun that part of the deploy script.

**Comment by edwardchalstrey1** [comment]
> The easiest fix is to deal the offending VM (CoCalc in this case) and rerun that part of the deploy script.

I opened #1319 since doesn't look like this worked

**Comment by jemrobinson** [comment]
@craddm @edwardchalstrey1 can you confirm whether this is done and close it if so?

**Comment by craddm** [comment]
The initial things I raised are dealt with.
