### ISSUE TITLE
Required versions of Az and MSGraph modules fail on Powershell 7.3.0

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1332]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 4.0.1 
- **Operating system details:** 

## :no_entry_sign: Describe the problem

There are issues with our required Az modules on Powershell 7.3.0 - for example, the `SRE_Teardown.ps1` script fails as below:

```
2022-11-24 09:47:10 [FAILURE]: [x] Running '/Users/mcraddock/Github/data-safe-haven/deployment/secure_research_environment/remote/configure_shm_dc/scripts/Remove_Users_And_Groups_Remote.ps1' on remote VM 'DC1-SHM-BLUE' failed.
OperationStopped: GenericArguments[0], Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T
MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

Similarly there's an issue with MSGraph modules with Powershell 7.3.0 - some commands other than `Connect-MgGraph` (e.g. `Get-MgApplication`) fail like this:

```
Get-MgApplication_List1: Method not found: 'System.Net.Http.HttpClient Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient(System.Management.Automation.InvocationInfo, Microsoft.Graph.PowerShell.Authentication.IAuthContext)'.
```

## :steam_locomotive: Workarounds or solutions

For Az modules, this seems to be related to https://github.com/Azure/azure-powershell/issues/18721 - it's not a problem with our script so not something we can directly fix. 

The issue with the MSGraph modules don't arise with the latest versions.

The development container has pinned working versions of Powershell (7.2.6) and the relevant modules, so people shouldn't hit this problem if they use it, or if they're using Powershell < 7.3. We may not have to do anything if this is something that gets fixed in a Powershell update. But may be best to check all the most recent module versions work for our whole process. Simplest solution is to require Powershell <= 7.2.7

**Comment by jemrobinson** [comment]
Is it worth changing our `CheckRequirements.ps1` to enforce a Powershell version `>7.0.0 && != 7.3.0`?

**Comment by craddm** [comment]
> Is it worth changing our `CheckRequirements.ps1` to enforce a Powershell version `>7.0.0 && != 7.3.0`?

Probably, as this same issue probably affects any cmdlet from the Az modules. The solution is to either update to the latest Az modules or pin to powershell < 7.3.0. We'd presumably want to do a test deployment if we updated the Az modules as it's quite a leap (e.g. Az.Compute 4.29.0 to Az.Compute 5.1.1).
