### ISSUE TITLE
Add Linux familiarity section to user guide

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1359]
Add a better explanation in the docs that you need to be familiar with Linux/command line to be a productive user

**Comment by craddm** [comment]
Perhaps link to external resources or set out more clearly what the requirements are for the users, rather than writing any Linux guidance ourselves

**Comment by JimMadge** [comment]
> Perhaps link to external resources or set out more clearly what the requirements are for the users, rather than writing any Linux guidance ourselves

:100: Let's not reinvent the wheel here.

If we can find a user docs for,

- Xfce
- Working in a terminal/Bash?
- Guacamole (alt+ctrl+shift for example)

We should link out to those.
