### ISSUE TITLE
Write data deletion script and improve docs

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1362]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Update the teardown process to include removing the persistent data container from Azure, so data gets deleted when SRE is deleted.

## :steam_locomotive: How could this be done?

- [ ] Write a powershell script that destroys the storage account in the SHM this and test it on a non-production SRE
- [x] #1366
- ~~Include the new script as a final step in `SRE_Teardown.ps1`~~ see discussion below
- [ ] Update [the docs](https://alan-turing-institute.github.io/data-safe-haven/v4.0.1/roles/system_manager/manage_deployments.html#remove-a-complete-safe-haven)

**Comment by JimMadge** [comment]
This sounds like a good idea. In general, if we have the code to provision something we should also have the code to destroy it.

It would be a good idea to separate reversible and irreversible deletions though. For example, removing an SRD shouldn't result in any data loss (persistent data is in storage accounts and users are on the AD). However, deleting the storage accounts will delete any work that was done in the SRE.

We don't want to make it easy to accidentally delete data so we need to be clear how destructive these operations are.
It might be a good idea to _not_ make this part of `SRE_Teardown.ps1` for that reason.

@jemrobinson thoughts?

**Comment by jemrobinson** [comment]
Yes, this is deliberately *not* part of the SRE teardown as we want the data to be able to exist before and after the project starts. We should probably factor out the creation and destruction of the storage account in the SHM into a separate script which can be run without having to deploy a full SRE.

**Comment by callummole** [comment]
We already have a script called [Remove_SRE_Data_From_SHM](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/deployment/secure_research_environment/setup/Remove_SRE_Data_From_SHM.ps1). 

The output of the Teardown script points you to that script (see #1379). 

But running this script doesn't actually remove the container, or the data in it, from the SHM subscription. I am currently going through this process again with the latest version, so add a comment below with the output.

**Comment by callummole** [comment]
I see on closer inspection that the `Remove_SRE_Data_From_SHM` script doesn't seem to refer to the 'Persistent Data', but rather user information, networks, etc. It also runs during the teardown script.

**Comment by jemrobinson** [comment]
`SRE_Teardown.ps1` calls `Remove_SRE_Data_From_SHM.ps1` [here](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/deployment/administration/SRE_Teardown.ps1#L86) so you shouldn't need to run this explicitly.

**Comment by callummole** [comment]
@jemrobinson ah yes, thanks. I came to that realisation
.

**Comment by callummole** [comment]
just to confirm. The current method for deleting SRE storage accounts is still to manually do it through the portal?

**Comment by jemrobinson** [comment]
Yes, that's right. Worth adding it to the documentation?

**Comment by edwardchalstrey1** [comment]
Another thing I noticed when running a teardown:

```
2023-02-13 16:59:19 [   INFO]: Removing update automation for SRE dsgamrc...
2023-02-13 16:59:19 [FAILURE]: [x] Failed to remove update automation for SRE dsgamrc!
```

Although looking in Azure portal I can't see any resources left for `dsgamrc`

**Edit:** following James' advice below, it looks like `dsgamrc` is already gone - will need to test this next time doing a teardown whether it was the teardown script that did this

**Comment by jemrobinson** [comment]
This should be visible in the [Automation account](https://learn.microsoft.com/en-us/azure/automation/update-management/view-update-assessments) in the SHM.

**Comment by craddm** [comment]
Check if something has been added to docs to clarify how to deal with this and why we made the decision not to do this in the function itself.
