### ISSUE TITLE
Request for Arrow (R package) to be added to the Tier 3 approve list - and working in tier 3 SRE

### ISSUE THREAD

**Issue by DDelbarre** [alan-turing-institute/data-safe-haven#1388]
## :white_check_mark: Checklist

- [X] I have searched open and closed issues for duplicates.
- [X] This is a request for a new software package to be added to the Data Safe Haven
- [X] The package is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).

## :gift: Package details

Provide details about the package you would like to see added:

- Package name: arrow
- Target audience: "core"
- Package version (if different from latest): latest
- Package repository: CRAN
- Number of authors/contributors to the package codebase: 12 authors
- Any existing versions that should not be used (linking to publicly-accessible CVE databases if relevant)
- Download statistics (recent and longer-term, for both current and previous versions): 1.7 million (all time), 80K (last month)
- List of packages that this package depends on: 
    - assertthat
    - bit64 (>= 0.9-7)
    - glue
    - methods
    - purrr
    - R6
    - rlang (>= 1.0.0)
    - stats
    - tidyselect (>= 1.0.0)
    - utils
    - vctrs

## :steam_locomotive: Why is this needed?

Arrow allows for working with Parquet files, which are a data format that lots of our project data (EDoN) will be provided in. More generally, Parquet is gaining popularity as an efficient column based format for the storage of large data files. Compared to csv files, parquet files can be read/written to up to 50x faster, and be compressed to 10% of the size of a csv file, so it is likely that there will be other projects on the Safe Haven that will use these files over time. Arrow also has functionality to work with large files such as being able to query a file on disk and only import subsets of the data to R, which is useful for big data projects.

None of the currently available R packages for working with Parquet files are on the Tier 3 approved list of packages, so there is no current alternative. There are two other packages that work with Parquet files (sfarrow and parqr), but both of these require arrow as a dependency (and are not so widely used anyway). 

I cannot think of any risks that this package would introduce if it was included on the approved list. One of the authors of arrow is Apache, so it also has a reputable author involved with its development. It seems that the dependencies are already approved packages.

**Comment by jemrobinson** [comment]
This looks like a well-used package which is well-supported.

My main question is: how common is Parquet in general (across all data analysis projects rather than EDoN in particular)? In other words, is this essential enough to require pre-installation for all projects (core) or just made available for download (extra)?

**Comment by edwardchalstrey1** [comment]
Anecdotally, I have come across these being used on one other project (Colouring London), where the data provider considered it a better way to transfer data than csv - and they were working in Python, not R. It looks like you can read Parquet with pandas in Python though, so that's easy.

**Comment by craddm** [comment]
My 2p: I'd agree that it's a well-used, well-supported package. The file format hasn't been that commonly used in my previous field (although funnily enough I have used it and the arrow package to distribute data for a workshop), but I'd think that would be lack of familiarity rather than lack of a use-case. Very helpful for cross-language R/Python workflows, too. As @DDelbarre says, it's likely to be used more over time. I would imagine making it available for download rather than pre-installation would be sufficient, as I don't see that many examples of it in the wild yet. But YMMV. 

(pandas can be made to use the Python equivalent - same dev team - of this package, `PyArrow`, to read Parquet files)

**Comment by jemrobinson** [comment]
Who wants to make the PR to add this package? :)

**Comment by edwardchalstrey1** [comment]
@jemrobinson @craddm how can I update the Edon TRE now this is done?

**Comment by jemrobinson** [comment]
Note that this isn't ready to action yet as the CI job that updates the allowlists is still running.

What you'll need to do (once the CI job PR is merged) is to update to the latest `develop` version and follow the instructions here: https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/roles/system_manager/manage_data.html.

Not that these could/should be made a bit more obvious. In fact, possibly the whole of what's under `system_manager` at the moment should be pulled up into a new top-level category related to "how to run a DSH deployment"?

**Comment by edwardchalstrey1** [comment]
> What you'll need to do (once the CI job PR is merged) is to update to the latest develop version and follow the instructions here: https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/roles/system_manager/manage_data.html.

@jemrobinson I don't think I knew which PR you meant (this one?) - I haven't done this yet, should I do it asap?

**Comment by jemrobinson** [comment]
I meant that when this CI job (https://github.com/alan-turing-institute/data-safe-haven/actions/runs/4241845589) finishes, it will create a PR if there are any new packages that need to be added to the full package list. If `arrow` only has dependencies that are already on the list then no PR will be created.

**Comment by edwardchalstrey1** [comment]
> Note that this isn't ready to action yet as the CI job that updates the allowlists is still running.
> 
> What you'll need to do (once the CI job PR is merged) is to update to the latest `develop` version and follow the instructions here: https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/roles/system_manager/manage_data.html.
> 
> Not that these could/should be made a bit more obvious. In fact, possibly the whole of what's under `system_manager` at the moment should be pulled up into a new top-level category related to "how to run a DSH deployment"?

@craddm @JimMadge it looks like this is something that got left when @jemrobinson went on leave and now Edon needs the arrow package. Do you think what James meant here by linking to the ingress/egress doc is that I would need to do software ingress for the package after it's been added to the allowlist?

Matt it looks as if you CI job James mentions in the comment above didn't run. If you had some experience with `SHM_Expand_Allowlist_Dependencies.ps1`, is this something that we just run in the CI and that updates the allowlist for all SREs connected to the SHM?

**EDIT:** actually I see more recent CI jobs for the allowlist passed: https://github.com/alan-turing-institute/data-safe-haven/actions/runs/4634075136/workflow

**Comment by DDelbarre** [comment]
It looks like the `arrow` package is available on the SRE repo, but when you try to install it the installation fails with:
```
Error building Arrow C++
```
and
```------------------------- NOTE ---------------------------
There was an issue preparing the Arrow C++ libraries.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
```

If I run this in R (this gives a more in-depth install log):
```
Sys.setenv(ARROW_R_DEV = TRUE)
install.packages("arrow")
```
it looks like it tries to visit a URL to install `libarrow` (C++ ?) which it can't do due to the lack of internet access in the SRE. [This link](https://arrow.apache.org/docs/r/articles/install.html#troubleshooting) gives some more details on the installation issues.

I've only installed `arrow` on Macs (with internet access) before, so I have not come across the need to do this, and it does not mention it as a dependency on CRAN.

**Comment by edwardchalstrey1** [comment]
<details>
<summary>
Error log:
</summary>

-- stderr output is:
CMake Error at mimalloc_ep-stamp/download-mimalloc_ep.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://github.com/microsoft/mimalloc/archive/v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: github.com

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/mimalloc-v2.0.6.tar.gz' failed
         status_code: 6
         status_string: "Couldn't resolve host name"
         log:
         --- LOG BEGIN ---
         Could not resolve host: apache.jfrog.io

  Closing connection 0

  

         --- LOG END ---
         
    


CMake Error at mimalloc_ep-stamp/mimalloc_ep-download-RELEASE-impl.cmake:9 (message):
CMake Error at snappy_ep-stamp/snappy_ep-download-RELEASE.cmake:47 (message):
  Stopping after outputting logs.

  Command failed (1):

   '/usr/bin/cmake' '-P' '/tmp/RtmpaO5NYg/file1237b91035cf1f/mimalloc_ep-prefix/src/mimalloc_ep-stamp/download-mimalloc_ep.cmake'




CMake Error at mimalloc_ep-stamp/mimalloc_ep-download-RELEASE.cmake:47 (message):
  Stopping after outputting logs.


make[2]: *** [CMakeFiles/snappy_ep.dir/build.make:91: snappy_ep-prefix/src/snappy_ep-stamp/snappy_ep-download] Error 1
make[2]: *** [CMakeFiles/mimalloc_ep.dir/build.make:91: mimalloc_ep-prefix/src/mimalloc_ep-stamp/mimalloc_ep-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:682: CMakeFiles/snappy_ep.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:737: CMakeFiles/mimalloc_ep.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
**** Error building Arrow C++.  
------------------------- NOTE ---------------------------
There was an issue preparing the Arrow C++ libraries.
See https://arrow.apache.org/docs/r/articles/install.html
---------------------------------------------------------
ERROR: configuration failed for package ‘arrow’
* removing ‘/usr/local/lib/R/site-library/arrow’

The downloaded source packages are in
        ‘/tmp/RtmpP5APOm/downloaded_packages’

</details>

**Comment by edwardchalstrey1** [comment]
Looking at the system dependencies in that link:

- [x] `As of version 10.0.0, arrow requires a C++17 compiler to build. For gcc, this generally means version 7 or newerAs of version 10.0.0, arrow requires a C++17 compiler to build. For gcc, this generally means version 7 or newer` - We have gcc version 9.4.0 so seems fine
- The [arrow package docs](https://cran.r-project.org/web/packages/arrow/index.html) clearly say "This package provides an interface to the 'Arrow C++' library. " - but I don't know if this is installed
- [This page](https://arrow.apache.org/docs/6.0/r/articles/install.html#how-dependencies-are-resolved) says "You’ll need to install libparquet-dev on Ubuntu" ... "When you install the arrow R package on Linux, it will first attempt to find the Arrow C++ libraries on your system using the pkg-config command." ... presumably before trying the internet
- See Ubuntu section of [install instructions](https://arrow.apache.org/install/):

```
sudo apt update
sudo apt install -y -V ca-certificates lsb-release wget
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
sudo apt update
sudo apt install -y -V libarrow-dev # For C++
sudo apt install -y -V libarrow-glib-dev # For GLib (C)
sudo apt install -y -V libarrow-dataset-dev # For Apache Arrow Dataset C++
sudo apt install -y -V libarrow-dataset-glib-dev # For Apache Arrow Dataset GLib (C)
sudo apt install -y -V libarrow-flight-dev # For Apache Arrow Flight C++
sudo apt install -y -V libarrow-flight-glib-dev # For Apache Arrow Flight GLib (C)
# Notes for Plasma related packages:
#   * You need to enable "non-free" component on Debian GNU/Linux
#   * You need to enable "multiverse" component on Ubuntu
#   * You can use Plasma related packages only on amd64
sudo apt install -y -V libplasma-dev # For Plasma C++
sudo apt install -y -V libplasma-glib-dev # For Plasma GLib (C)
sudo apt install -y -V libgandiva-dev # For Gandiva C++
sudo apt install -y -V libgandiva-glib-dev # For Gandiva GLib (C)
sudo apt install -y -V libparquet-dev # For Apache Parquet C++
sudo apt install -y -V libparquet-glib-dev # For Apache Parquet GLib (C)
```

**Comment by craddm** [comment]
> Looking at the system dependencies in that link:
> 
> * [x]  `As of version 10.0.0, arrow requires a C++17 compiler to build. For gcc, this generally means version 7 or newerAs of version 10.0.0, arrow requires a C++17 compiler to build. For gcc, this generally means version 7 or newer` - We have gcc version 9.4.0 so seems fine
> * [ ]  The [arrow package docs](https://cran.r-project.org/web/packages/arrow/index.html) clearly say "This package provides an interface to the 'Arrow C++' library. " - but I don't know if this is installed

Looking further down the page @DDelbarre linked it talks about downloading additional third-party dependencies (without listing them), so may need to add those as well. 

Maybe we can find a way to pre-build the `arrow` package. I'm assuming it's trying to build it from source, but if we can configure it so a binary is available we might sidestep these issues (thinking out loud so might be wrong!)

**Comment by edwardchalstrey1** [comment]
> Maybe we can find a way to pre-build the arrow package. I'm assuming it's trying to build it from source, but if we can configure it so a binary is available we might sidestep these issues (thinking out loud so might be wrong!)

I'm not sure what the best practice is here. Given the install instructions above (which we can't perform without internet), is there some way we can do what @craddm suggests and then [software ingress](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/roles/system_manager/manage_data.html#software-ingress) the binary? pinging @JimMadge

**Comment by JimMadge** [comment]
It isn't the R package that is the problem here, rather that the R package depends on `libarrow`.

Packages which fetch dependencies from the internet will always be problematic as access is necessarily restricted.

If we think `libarrow` is important enough, then a long-term solution would be to install it during the SRD image building.
@DDelbarre Thanks for the report and debugging :tada:, could you open an issue about this?

@edwardchalstrey1 Yes, for existing deployments I would suggest downloading the `.deb`s required, going through the ingress process and installing them with `dpkg` using the admin account.

**Comment by JimMadge** [comment]
Arrow debs are here: https://apache.jfrog.io/ui/native/arrow/ubuntu/pool/focal/main/a/apache-arrow/

**Comment by edwardchalstrey1** [comment]
Can also try installing via download from RStudio: https://packagemanager.rstudio.com/client/#/repos/2/packages/arrow

**Comment by edwardchalstrey1** [comment]
> Can also try installing via download from RStudio: https://packagemanager.rstudio.com/client/#/repos/2/packages/arrow

This method didn't work, will try the debs method above

![Screenshot 2023-04-18 at 16 32 55](https://user-images.githubusercontent.com/5486164/232827962-56f1809e-dd6f-4d82-a14f-f8658439eb06.png)

**Comment by edwardchalstrey1** [comment]
On second thought, the above method does seem to work - I had downloaded the source file rather than the binary. Installing this way includes the R package with the underlying C++

So the steps that work which I can repeat in the Edon TRE:
1. Navigate to [RStudio package manager page for arrow](https://packagemanager.rstudio.com/client/#/repos/2/packages/arrow) and select the correct version of Ubuntu and R for the TRE
2. Download the binary and rename it to something sensible
      <img width="1242" alt="Screenshot 2023-04-19 at 09 55 36" src="https://user-images.githubusercontent.com/5486164/233024536-04e07e32-9238-4902-b99d-7470b845bc1a.png">
3. Ingress the binary to the TRE `/data` folder
4. Then the **Research user** (@DDelbarre ) can do:
     - `cp /data/arrow_binary.tar.gz ~` to create a copy in their home dir
     - Open R and run:
     - `install.packages('arrow_binary.tar.gz', repos = NULL, type="source")`
