### ISSUE TITLE
Update info on how to use databases in the SRE

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1392]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Currently there is documentation on [how to access databases in an SRE that have been set up already](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/researcher/user_guide_guacamole.html#access-databases). But not on anything on creating database tables and working with psql/msql directly as oppose to via Python, R, Dbeaver.

## :memo: Required documentation changes

It would be good to explain better how:

- PostreSQL (and Microsoft SQL) can be used for creating databases, when researchers have access to the `SG <SRE ID> Data Administrators` privileges
- All users can create tables in the public schema

A situation arose on a recent project where a researcher wanted to use PostGIS for spatial analyses, but wasn't sure how to do so and it wasn't clear to me either

**Comment by craddm** [comment]
Check if documentation makes it clear what users should and should not be able to do, and whether any such documentation is clearly visible

**Comment by craddm** [comment]
Some notes:
1) As Ed noted above, everyone can create tables in the public schema
2) Intended behaviour is that data admins can create tables in the data schema, and research users can only view them. This works after #1708 
3) the postgis schema (and the topology schema) does not currently have permissions set for anyone to do anything with it. not clear if anything needs to change there, though, as users should still be able to use PostGIS features in their tables (e.g. can still create a _point column in a new table in the Public schema)
4) System Administrators are supposed to be given superuser roles but are not.
