### ISSUE TITLE
Add a section on resizing SRD VMs for GPU VMs

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1393]
## :ledger: Where is the problem?

Update [this section](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/system_manager/manage_deployments.html#resize-the-virtual-machine-vm-of-a-secure-research-desktop-srd)

## :memo: Required documentation changes

Instructions:
- Look at the VM in the portal at the VM size it's not letting you have
- In the portal, go to the subscription -> `Usage + quotas` and search for something N series (GPUs) "Standard NVSv4" (UK South)
- Click the pen on the right and request to increase quota, with the size being at least as many vCPUs as the VM you want has
- Then increase the VM size as usual

**Comment by edwardchalstrey1** [comment]
Also maybe a minor release once these docs and similar issues complete

**Comment by JimMadge** [comment]
I think adding an admonition here to point out that quotas may be a problem is a good idea. We should be careful not to end up writing documentation for Azure however.
