### ISSUE TITLE
Update System Manager docs on how to give tier 0/1 users sudo privileges

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1396]
## :ledger: Where is the problem?

On the [users management page](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/system_manager/manage_users.html) after #1389 is merged it would be good to also specify that the `SG <SRE ID> System Administrators` security group is not sufficient to grant sudo privileges.

## :memo: Required documentation changes

The process that did work:

- Log into Serial Console of the compute VM with the admin username and pass stored in the key vault
- `sudo usermod -aG sudo firstname.lastname@prod4.turingsafehaven.ac.uk`
- Check it worked with `getent group sudo` and also trying a sudo cmd as that user in the SRE

**Comment by JimMadge** [comment]
> the SG <SRE ID> System Administrators security group is not sufficient to grant sudo privileges.

@jemrobinson is that true? If so, is that a bug?

**Comment by jemrobinson** [comment]
Do we know which of these is true?

- groups from AD might not be synchronised correctly to the VM (this is a bug if so).
- the "SRENAME System Administrators" group doesn't have any special privileges on the VM (this is a design decision that can be changed).

**Comment by JimMadge** [comment]
If they appear as Linux groups (_i.e._ it is output by `groups`) it should be easy to add a rule in `/etc/sudoers.d/`.

I can't find anything that looks like it does this in the srd cloud init. `rg sudoers` and `rg sudo` don't show anything like that either.

@edwardchalstrey1 if you have a running environment, could you as a user which is in the System Administrators security group give the output of `groups` after logging out and in.

Could you also give the contents of `/etc/sudoers` and any files in `/etc/sudoers.d/`? (You will need to do this as root).

**Comment by edwardchalstrey1** [comment]
Logged into Sandbox for which I am in system administrator sg and it shows thats the case:
```
ed.chalstrey1:~$ groups
domain users sg sandbox research users sg sandbox system administrators sg edonwrg research users sg dsgjmt research users sg dsgst research users sg dsggw research users sg dsgkeep research users sg dsgnot research users
```

> Could you also give the contents of /etc/sudoers and any files in /etc/sudoers.d/? (You will need to do this as root)

I can't do this in Sandbox as I don't have sudo privilege - but in the `dsgjmt` SRE where I manually gave myself root privilege (by method in the top comment):

```
ed.chalstrey1:~$ sudo cat /etc/sudoers
[sudo] password for ed.chalstrey1: 
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification

# User privilege specification
root	ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
```

and

```
ed.chalstrey1:~$ sudo ls /etc/sudoers.d/
90-cloud-init-users  omsagent  README
ed.chalstrey1:~$ sudo cat /etc/sudoers.d/90-cloud-init-users
# Created by cloud-init v. 22.3.4-0ubuntu1~20.04.1 on Tue, 29 Nov 2022 21:32:11 +0000

# User rules for srdbuildadmin
srdbuildadmin ALL=(ALL) NOPASSWD:ALL

# User rules for sredsgjmtadmin
sredsgjmtadmin ALL=(ALL) NOPASSWD:ALL
```

**Comment by edwardchalstrey1** [comment]
We no longer want to do this
