### ISSUE TITLE
Clarify documentation on using NVIDIA GPU-enabled VMs for SREs

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1401]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Following on from #1399 there are a couple of other Azure related things it would be good to have clear in [the docs](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/system_manager/manage_deployments.html#resize-the-virtual-machine-vm-of-a-secure-research-desktop-srd):

## :memo: Required documentation changes

- [x] Make sure that the selected VM is NVIDIA, not AMD - see [here](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-gpu)
    - This is so that CUDA can be used in the SRE
    - Note: may need to stop the VM so that more N-Series options become available for resizing
    - ~~Note: If N series still unavailable, may need to request an increase on the Quotas page of the subscription~~ I already added this to the docs in a [note](https://alan-turing-institute.github.io/data-safe-haven/develop/roles/system_manager/manage_deployments.html#resize-the-virtual-machine-vm-of-a-secure-research-desktop-srd)
- [x] Document how to make sure the NVIDIA driver is working correctly and CUDA can be used
    - Do we need to add a new smoke test for this? (open a separate issue if needed) **Edit:** we probably can't easily have a smoke test unless it involved 1) switching to a GPU VM, 2) running the test 3) switching back
    - Initially can just say run `nvidia-smi`

**Comment by edwardchalstrey1** [comment]
### CUDA steps

**Note:** we probably don't want to document this but to make it so that it doesn't need to be done

Steps taken (some possibly superfluous) to get CUDA working (run `ndvidia-smi` when logged into SRE) on an SRE with an NVIDIA GPU VM:

1. Log into the Serial Console of the compute VM
2. Run the below:

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
sudo apt-get update
sudo apt-get -y install cuda
```
but then it complained about something about dependencies and suggested I do:
```
sudo apt --fix-broken install -y
```
after which I was then able to install cuda with
```
sudo apt-get -y install cuda
```

**Comment by jemrobinson** [comment]
Can you clarify on a VM where you haven't done this:

- which versions of `cuda` and `nvidia-utils-*` are installed?
- what the output of `nvidia-smi` is (only relevant on a VM with an NVIDIA GPU)?

**Comment by edwardchalstrey1** [comment]
<img width="801" alt="Screenshot 2023-02-23 at 13 21 27" src="https://user-images.githubusercontent.com/5486164/220948765-08d93504-d62f-4d97-a3c6-2b26975c6b07.png">

**Comment by edwardchalstrey1** [comment]
> which versions of cuda installed?

<details>
```
ed.chalstrey1:~$ apt list --installed | grep cuda

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cuda-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-cccl-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-command-line-tools-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-compiler-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-cudart-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-cudart-dev-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-cuobjdump-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-cupti-11-8/unknown,now 11.8.87-1 amd64 [installed,automatic]
cuda-cupti-dev-11-8/unknown,now 11.8.87-1 amd64 [installed,automatic]
cuda-cuxxfilt-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-demo-suite-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-documentation-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-driver-dev-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-drivers-520/unknown,now 520.61.05-1 amd64 [installed,automatic]
cuda-drivers/unknown,now 520.61.05-1 amd64 [installed,upgradable to: 525.85.12-1]
cuda-gdb-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-libraries-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-libraries-dev-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-memcheck-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nsight-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nsight-compute-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-nsight-systems-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-nvcc-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-nvdisasm-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nvml-dev-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nvprof-11-8/unknown,now 11.8.87-1 amd64 [installed,automatic]
cuda-nvprune-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nvrtc-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-nvrtc-dev-11-8/unknown,now 11.8.89-1 amd64 [installed,automatic]
cuda-nvtx-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-nvvp-11-8/unknown,now 11.8.87-1 amd64 [installed,automatic]
cuda-profiler-api-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-runtime-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-sanitizer-11-8/unknown,now 11.8.86-1 amd64 [installed,automatic]
cuda-toolkit-11-8-config-common/unknown,now 11.8.89-1 all [installed,automatic]
cuda-toolkit-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-toolkit-11-config-common/unknown,now 11.8.89-1 all [installed,automatic]
cuda-toolkit-config-common/unknown,now 11.8.89-1 all [installed,upgradable to: 12.0.146-1]
cuda-tools-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda-visual-tools-11-8/unknown,now 11.8.0-1 amd64 [installed,automatic]
cuda/unknown,now 11.8.0-1 amd64 [installed,upgradable to: 12.0.1-1]
libcudnn8-dev/unknown,now 8.7.0.84-1+cuda11.8 amd64 [installed,upgradable to: 8.8.0.121-1+cuda12.0]
libcudnn8/unknown,now 8.7.0.84-1+cuda11.8 amd64 [installed,upgradable to: 8.8.0.121-1+cuda12.0]
```
</details>

**Comment by edwardchalstrey1** [comment]
> which versions nvidia-utils-* are installed?

```
ed.chalstrey1:~$ apt list --installed | grep nvidia-utils

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nvidia-utils-520/now 525.60.11-0ubuntu0.20.04.2 amd64 [installed,upgradable to: 525.78.01-0ubuntu0.20.04.1]
nvidia-utils-525/now 525.60.11-0ubuntu0.20.04.2 amd64 [installed,upgradable to: 525.85.12-0ubuntu1]
```

**Comment by jemrobinson** [comment]
And what can you see if you open the Automation Account (`RG_SHM_<SHM name>_MONITORING > shm-<shm name>-automation`) in the Portal then select `Update management` on the left-hand side-bar? Are any VMs from the SRE listed there?

**Comment by edwardchalstrey1** [comment]
> And what can you see if you open the Automation Account (RG_SHM_<SHM name>_MONITORING > shm-<shm name>-automation) in the Portal then select Update management on the left-hand side-bar? Are any VMs from the SRE listed there?

They all are, but seems like this may be the issue:

<img width="1773" alt="Screenshot 2023-02-23 at 15 34 23" src="https://user-images.githubusercontent.com/5486164/220955110-4052a327-1a64-4d22-8aca-041fffbd1ebc.png">

**Comment by JimMadge** [comment]
> > which versions nvidia-utils-* are installed?
> 
> ```
> ed.chalstrey1:~$ apt list --installed | grep nvidia-utils
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> nvidia-utils-520/now 525.60.11-0ubuntu0.20.04.2 amd64 [installed,upgradable to: 525.78.01-0ubuntu0.20.04.1]
> nvidia-utils-525/now 525.60.11-0ubuntu0.20.04.2 amd64 [installed,upgradable to: 525.85.12-0ubuntu1]
> ```

This is before installing anything else? There are two versions of the Nvidia drivers installed already?

**Comment by edwardchalstrey1** [comment]
> This is before installing anything else? There are two versions of the Nvidia drivers installed already?
@JimMadge yes

**Comment by JimMadge** [comment]
I'm pretty certain that isn't necessary and wouldn't be surprised if it could cause problems.

**Comment by jemrobinson** [comment]
Are there actually two versions or is there one (`525.60.11-0ubuntu0.20.04.2`) that satisfies two metapackages?

**Comment by JimMadge** [comment]
There are two apt packages installed. Although, it does look like files in each package might be the same. Although, Although, they are both out of date and when up to date would install different files. Some more digging,

```command
vagrant@ubuntu2004:~$ apt show nvidia-utils-520
Package: nvidia-utils-520
...
Description: Transitional package for nvidia-utils-525
 This is a transitional package for nvidia-utils-525, and can be
 safely removed after the installation is complete.
```

Given they want to update to different points I suppose 520 has been abandoned at this point. Perhaps this is because the image building has Nvidia packages pegged to some old version and automatic updates try to transition to the new package.

**Comment by JimMadge** [comment]
@edwardchalstrey1 could you show the output of
`apt search nvidia | grep -E '^nvidia-[0-9]{3}'` and
`apt list --installed nvidia | grep -E '^nvidia-[0-9]{3}'`?

**Comment by edwardchalstrey1** [comment]
@JimMadge James and I discovered the reason behind this last night, related to the Update management (see screenshot above) - but I'll open a separate issue about this.

For your suggestions:

```
ed.chalstrey1:~$ apt search nvidia | grep -E '^nvidia-[0-9]{3}'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nvidia-331/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-331-dev/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-331-updates/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-331-updates-dev/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-331-updates-uvm/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-331-uvm/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-340/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-340-dev/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-340-updates/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-340-updates-dev/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-340-uvm/focal-updates,focal-security 340.108-0ubuntu5.20.04.2 amd64
nvidia-384/focal-updates,focal-security 390.157-0ubuntu0.20.04.1 amd64
nvidia-384-dev/focal-updates,focal-security 390.157-0ubuntu0.20.04.1 amd64
```
None are installed:
```
ed.chalstrey1:~$ apt list --installed nvidia | grep -E '^nvidia-[0-9]{3}'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

**Comment by edwardchalstrey1** [comment]
Actual problem that sparked this issue is documented here: #1403
