### ISSUE TITLE
Document how to fix full /home storage SRE error

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1402]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Some users of an SRE who were generating a lot of image data ran out of storage in `/home` and the result was that when you log into the Ubuntu login, you just get a black screen.

## :memo: Required documentation changes

The solution was to increase the size of the NFS file share, but I'm not sure if we should document this somewhere?

1. Go to the subscription of the VM in the Azure portal
2. Go to `RG_SHM_<SHM ID>_SRE_<SRE ID>_STORAGE` -> `<shm id><sre id>userdata<hash> | File shares`
3. Click `Size and performance` and increase

Alternatively, can we configure a limit to the disk space that prevents this from happening? If so, how to do this might also be worth documenting.

**Comment by jemrobinson** [comment]
Yes, please document this. I think we probably need a top-level docs section (at the same level as overview, design, deployment, processes and roles) that contains all of the info about how to run a DSH in production (some of this is in roles > system manager).
