### ISSUE TITLE
Update management is not running for VMs of recently deployed SREs (except Guacamole)

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1403]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 4.0.2
- **Operating system details:** macOS Monterey

## :cactus: Powershell module versions

```
2023-02-24 09:58:58 [SUCCESS]: [✔] Powershell version: 7.2.6
2023-02-24 09:58:58 [SUCCESS]: [✔] Poshstache module version: 0.1.10
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.KeyVault module version: 4.6.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Accounts module version: 2.9.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Microsoft.Graph.Identity.DirectoryManagement module version: 1.10.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Microsoft.Graph.Authentication module version: 1.17.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Storage module version: 4.7.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Network module version: 4.18.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.PrivateDns module version: 1.0.3
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.RecoveryServices module version: 5.4.1
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Compute module version: 4.29.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Resources module version: 6.0.1
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Automation module version: 1.7.3
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Dns module version: 1.1.2
2023-02-24 09:58:58 [SUCCESS]: [✔] Powershell-Yaml module version: 0.4.2
2023-02-24 09:58:58 [SUCCESS]: [✔] Microsoft.Graph.Applications module version: 1.17.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.MonitoringSolutions module version: 0.1.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.OperationalInsights module version: 3.1.0
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.Monitor module version: 3.0.1
2023-02-24 09:58:58 [SUCCESS]: [✔] Az.DataProtection module version: 0.4.0
```

## :no_entry_sign: Describe the problem

For recently deployed SREs (e.g. `dsgkeep`) the Update management is only working for Guacamole, but not the other VMs, including the compute VM. This has resulted in packages not being updated, for example, it caused the problem that resulted in #1401 

![Screenshot 2023-02-24 at 09 59 57](https://user-images.githubusercontent.com/5486164/221149952-a5329f7b-c9aa-4ec5-bb18-bac0b69d2c1d.png)

This is strange because it looks like the VM is connected to loganalytics:

![Screenshot 2023-02-24 at 10 40 45](https://user-images.githubusercontent.com/5486164/221158955-bec49886-4d65-48f8-8034-50d7e0236bdb.png)

**Comment by jemrobinson** [comment]
Can you go to `Operations > Updates` in the Portal on an affected VM and click `Go to Updates using Automation`

<img width="678" alt="Screenshot 2023-02-24 at 15 31 19" src="https://user-images.githubusercontent.com/3502751/221219029-aa2c7bb5-4f06-4cfe-a6ac-fbc135ad9fb4.png">

then click `Enable`

<img width="1109" alt="Screenshot 2023-02-24 at 15 18 31" src="https://user-images.githubusercontent.com/3502751/221218761-d13d3b9f-c21c-4c89-915c-acbd358f325c.png">

this ought to (after a few minutes) trigger discovery of the VM in the Azure Query that wasn't working in the screenshots above.

**Comment by edwardchalstrey1** [comment]
I'm unable to see the updates when I go to `Operations > Updates`
![Screenshot 2023-02-24 at 15 48 52](https://user-images.githubusercontent.com/5486164/221224167-f0f4bed2-304a-45d4-bffc-7c1f2aea5aed.png)

But I managed to find this page by going `Update management center > Machines` and clicking on the VM:
![Screenshot 2023-02-24 at 15 51 16](https://user-images.githubusercontent.com/5486164/221224750-0c2d5840-b50f-4bbf-894b-0d0929ba1704.png)

Setting `Enable` and clicking `Save` resulted in this error:
![Screenshot 2023-02-24 at 15 51 48](https://user-images.githubusercontent.com/5486164/221224891-e927485e-f713-4858-b58d-92638fcfb22c.png)

**Comment by jemrobinson** [comment]
NB. running `Setup_SRE_Monitoring.ps1 -shmID <shm name> -sreId <sre name>` fixed the issue on a test deployment.

**Comment by jemrobinson** [comment]
> I'm unable to see the updates when I go to Operations > Updates

You have to click "Leave new experience" in the top bar.

Do NOT enable `Update management center (preview)` as this is a new Update Management solution that hasn't yet been fully rolled out.

**Comment by edwardchalstrey1** [comment]
![Screenshot 2023-02-24 at 16 24 49](https://user-images.githubusercontent.com/5486164/221232443-0817a6d4-9741-49c7-be3f-abd63919369f.png)

**Comment by jemrobinson** [comment]
As mentioned above `Do NOT enable Update management center (preview) as this is a new Update Management solution that hasn't yet been fully rolled out.`

**Comment by edwardchalstrey1** [comment]
The problem appears to be the query to find VMs in the automation updates doesn't find the VMs (apart from the Guacamole ones for some reason)

**Comment by JimMadge** [comment]
@edwardchalstrey1 If this is similar the issue we had previously with backups, where permissions (through role assignments) need to be made between subscriptions you might want to look [at the issue](https://github.com/alan-turing-institute/data-safe-haven/issues/1343) and [the pr](https://github.com/alan-turing-institute/data-safe-haven/pull/1345).

**Comment by edwardchalstrey1** [comment]
Here are the docs on how update management should work:
https://learn.microsoft.com/en-us/azure/automation/update-management/overview
https://learn.microsoft.com/en-us/azure/automation/update-management/plan-deployment

**Comment by edwardchalstrey1** [comment]
> NB. running `Setup_SRE_Monitoring.ps1 -shmID <shm name> -sreId <sre name>` fixed the issue on a test deployment.

Note, this doesn't fix the issue for "Sandbox" - despite this SRE being in the same subscription as the SHM ("prod4")

**Comment by edwardchalstrey1** [comment]
The problem appears to be that the search query of a schedule deployment doesn't find the all VMs:
![Screenshot 2023-02-27 at 14 23 32](https://user-images.githubusercontent.com/5486164/221589502-4e9fae0f-5e22-469f-bffd-a124b2541f5b.png)

Just Guacamole (although weirdly when I hit referesh it occasionally finds other VMs 😱 ):
![Screenshot 2023-02-27 at 14 23 55](https://user-images.githubusercontent.com/5486164/221589498-e3101eb1-93c9-49df-9b52-ef9810363551.png)

then this...

![Screenshot 2023-02-27 at 14 34 33](https://user-images.githubusercontent.com/5486164/221592006-04bba87c-8953-4102-8508-ca9c923a0071.png)

I also tried enabling [VM insights](https://learn.microsoft.com/en-gb/azure/azure-monitor/vm/vminsights-enable-portal) to see if this would result in the VM I added it to showing up in the above list but it didn't

**Comment by edwardchalstrey1** [comment]
Running `./Setup_SRE_Monitoring.ps1` for Sandbox I noticed this:

```
2023-02-27 14:33:56 [SUCCESS]: [✔] Retrieved log analytics workspace 'shm-prod4-loganalytics.
2023-02-27 14:33:56 [   INFO]: [ ] Ensuring logging agent is installed on all SRE VMs...
```
~~**wasn't** followed by "Ensured that logging agent is installed on all SRE VMs." OR "Failed to ensure that logging agent is installed on all SRE VMs!"~~ yes it was:

```
2023-02-27 14:34:00 [SUCCESS]: [✔] Ensured that logging agent is installed on all SRE VMs.
```

and the Log Analytics agent for linux called `OmsAgentForLinux` does appear to be present for all VMs:
![Screenshot 2023-02-27 at 15 23 26](https://user-images.githubusercontent.com/5486164/221604929-164ecb1f-8a70-4842-a86d-750d91406443.png)

**Comment by edwardchalstrey1** [comment]
Attempting the troubleshoot check of the failure in this linux-updates “deployment run”  looks like one failure:

![Screenshot 2023-02-27 at 15 41 09](https://user-images.githubusercontent.com/5486164/221609895-38f8953e-6ed8-48b9-aafa-70d15c73d38b.png)

Problem with [multihoming](https://learn.microsoft.com/en-gb/azure/automation/troubleshoot/update-agent-issues-linux#multihoming)
![Screenshot 2023-02-27 at 15 43 25](https://user-images.githubusercontent.com/5486164/221610270-81c6241a-834f-43a7-9e73-dff8052f7e81.png)

**Comment by jemrobinson** [comment]
Good spot. What are the two Log Analytics Workspaces it's registered with?

**Comment by edwardchalstrey1** [comment]
But for other compute VMs, none of the updates run because the AzureQuery provided in the deployment schedule doesn't find the VMs:

![Screenshot 2023-02-27 at 15 54 17](https://user-images.githubusercontent.com/5486164/221613353-00abe820-2973-4636-abf7-7790012716bd.png)

**Comment by jemrobinson** [comment]
I think this is where I got to with Ed on Friday. The AzureQuery *should* be able to see all VMs that are registered with the correct LogAnalyticsWorkspace, but it doesn't seem to be finding them.

**Comment by edwardchalstrey1** [comment]
> Good spot. What are the two Log Analytics Workspaces it's registered with?

See the screenshot 4 comments up, there is `AzureMonitorLinuxAgent` in addition to `OmsAgentForLinux`, but when I delete these from Sandbox compute VM and re-run `./Setup_SRE_Monitoring.ps1` it doesn't have this, it only has `OmsAgentForLinux`, so I may have added that manually earlier today by mistake (the Sandbox linux updates deployment run 3 comments up was from 21st Feb, so might be unrelated).

Looking at `Extensions + applications` now I only see the one Log Analytics agents (are "agents" are the same as "Workspace"?)


![Screenshot 2023-02-27 at 16 01 41](https://user-images.githubusercontent.com/5486164/221615246-e3fc21d5-ceca-4534-a538-fe030590e445.png)

**Comment by jemrobinson** [comment]
The VM extensions are small scripts that add capabilities to the VMs. In this case `AzureMonitorLinuxAgent` links a VM to an `Azure Monitor` resource and `OmsAgentForLinux` links a Linux VM to a LogAnalyticsWorkspace.

However, that error message gives the IDs for two LogAnalyticsWorkspaces - what are their names? One of them is the one that the VM is supposed to be connected to (see screenshot) but what is the second one?

<img width="1423" alt="Screenshot 2023-02-27 at 16 12 32" src="https://user-images.githubusercontent.com/3502751/221617568-b6849531-c7d8-44d4-a2fa-bd579006e126.png">

**Comment by edwardchalstrey1** [comment]
`(['5a7c5978-6c3f-4e2e-9f6a-a8063cf82914', 'c172386f-1bcb-48b2-b1e5-b937dc24fd3c']).` - let me check if I can see these

neither of which are the same as `4aea9c2f-9b6c-42e8-8b09-3594994fe238` in your screenshot above @jemrobinson

**Comment by edwardchalstrey1** [comment]
I can't see either of those in this list:
![Screenshot 2023-02-27 at 16 40 27](https://user-images.githubusercontent.com/5486164/221624937-74992d72-ee16-4857-93c5-14f87ecd85f8.png)

**Comment by jemrobinson** [comment]
See screenshot I attached above. You need to look at each LogAnalyticsWorkspace and look at "Workspace ID" in the "Overview" tab.

Note: `4aea9c2f-9b6c-42e8-8b09-3594994fe238` is the **subscription ID** not the **workspace ID**.

**Comment by edwardchalstrey1** [comment]
> See screenshot I attached above. You need to look at each LogAnalyticsWorkspace and look at "Workspace ID" in the "Overview" tab.
> 
> Note: `4aea9c2f-9b6c-42e8-8b09-3594994fe238` is the **subscription ID** not the **workspace ID**.

`5a7c5978-6c3f-4e2e-9f6a-a8063cf82914` is shm-prod4-loganalytics
`c172386f-1bcb-48b2-b1e5-b937dc24fd3c` is **DefaultWorkspace-f871c3f7-6a68-42fb-bed6-81689e730f7a-SUK**

![Screenshot 2023-02-27 at 16 44 29](https://user-images.githubusercontent.com/5486164/221625882-6d9fdf4f-ef7a-4460-9dac-1503919f4604.png)

**Comment by jemrobinson** [comment]
Great. I don't think `DefaultWorkspace-f871c3f7-6a68-42fb-bed6-81689e730f7a-SUK` is being used, so I'll delete that now. Can you see whether this resolves any of the other issues?

**Comment by jemrobinson** [comment]
Also, there is a Microsoft-provided diagnostic tool here: https://learn.microsoft.com/en-us/azure/azure-monitor/agents/agent-linux-troubleshoot?WT.mc_id=Portal-Microsoft_Azure_Support#log-analytics-troubleshooting-tool

**Comment by jemrobinson** [comment]
This might also be a problem with the [Hybrid Runbook Worker](https://learn.microsoft.com/en-us/azure/automation/troubleshoot/update-management) and there are [troubleshooting steps here](https://learn.microsoft.com/en-us/azure/automation/troubleshoot/extension-based-hybrid-runbook-worker).

NB. I'm sure you're already aware, but please do all potentially destructive testing on a dev environment like SRE Sandbox.

**Comment by edwardchalstrey1** [comment]
Having another look at this now - another thing to note is that the automated update management still tries to run for SREs that were torn down, which also results in a lot of failures:

<img width="1630" alt="Screenshot 2023-03-01 at 11 52 15" src="https://user-images.githubusercontent.com/5486164/222132231-b1515637-3563-4e78-9717-c6f6a796eb2d.png">

**Comment by jemrobinson** [comment]
> Having another look at this now - another thing to note is that the automated update management still tries to run for SREs that were torn down, which also results in a lot of failures:

Yes, we should add "delete the automation schedules" to the SRE teardown script. If you'd like, you can manually delete them for the moment?

**Comment by edwardchalstrey1** [comment]
Log Analytics shows that all VMs for a given SRE are present:
<img width="1898" alt="Screenshot 2023-03-01 at 12 05 40" src="https://user-images.githubusercontent.com/5486164/222134802-1a86dacd-e548-4f9f-852e-a74e59a8fd75.png">

Yet editing the update deployment Azure Query, the VMs that are found are inconsistent depending on the SRE subscription:
<img width="841" alt="Screenshot 2023-03-01 at 12 07 51" src="https://user-images.githubusercontent.com/5486164/222135713-2ea6cd5b-f8a0-4f80-a33b-8511989a584e.png">
<img width="829" alt="Screenshot 2023-03-01 at 12 09 31" src="https://user-images.githubusercontent.com/5486164/222135726-7aab3480-97e8-4c2f-886a-9aabc88aa6af.png">

For the SREs that **aren't** Sandbox, none of the updates run, even for the VMs found by the Azure Query:
<img width="1894" alt="Screenshot 2023-03-01 at 12 12 07" src="https://user-images.githubusercontent.com/5486164/222136177-efc8fc5f-daee-47f9-ac57-b0c634d21846.png">

**Comment by jemrobinson** [comment]
> For the SREs that aren't Sandbox, none of the updates run, even for the VMs found by the Azure Query:

There seems to be some inconsistency between what's shown in the AzureQuery preview and what's actually found when the query runs. In the screenshot you've attached here the AzureQuery isn't finding any VMs. Is there a case where VMs *are* found but the updates aren't running?

**Comment by edwardchalstrey1** [comment]
I'm starting to think there might be something fundamental broken in the Azure Query system we should think about raising an issue with Microsoft - whilst clicking around on the `New update deployment` page, I briefly "tricked" it into realising that all the VMs of a particular SRE were present, (I think by selecting both the SRE and SHM subscription, then un-selecting the SHM subscription)... yet when I try to duplicate this I am unable to do so!

![Screenshot 2023-03-02 at 09 48 11](https://user-images.githubusercontent.com/5486164/222396676-f298da95-bc29-4b01-9ae7-7757cc3b47ba.png)

**Comment by edwardchalstrey1** [comment]
### Preview vs edit of the same query:

![Screenshot 2023-03-02 at 10 07 55](https://user-images.githubusercontent.com/5486164/222397932-5a7d8074-a520-40df-b28b-c862e3239d03.png)
![Screenshot 2023-03-02 at 10 07 40](https://user-images.githubusercontent.com/5486164/222397936-145ba3a4-66f9-4160-b2e1-3f20e1efa67f.png)

**Comment by jemrobinson** [comment]
Have you run through the Hybrid Runbook Worker troubleshooting I linked above? VMs with a correctly configured Hybrid Runbook Worker seem to be working correctly.

## VM where updates are working
<img width="530" alt="Screenshot 2023-03-03 at 12 05 37" src="https://user-images.githubusercontent.com/3502751/222716192-09b58fbb-e5cb-4db4-8865-60b4d5bac610.png">

## VM where updates are not working
<img width="545" alt="Screenshot 2023-03-03 at 12 05 40" src="https://user-images.githubusercontent.com/3502751/222716199-58ebb966-6290-445c-bfb1-58739cc682d4.png">

### EC note: when I go on this it looks like working
![Screenshot 2023-03-03 at 13 45 26](https://user-images.githubusercontent.com/5486164/222735869-07ecaed4-aa53-421a-a75e-291441cd0488.png)

**Comment by edwardchalstrey1** [comment]
Just looking at this now, there are examples where the VM updates are still not working despite the Hybrid Worker not having the same error you just posted for Edon
![Screenshot 2023-03-03 at 13 28 41](https://user-images.githubusercontent.com/5486164/222732314-dcd1291d-41f9-45e0-8c25-74dc2732a429.png)

**Comment by edwardchalstrey1** [comment]
Looking at the [troubleshooting checklist](https://learn.microsoft.com/en-us/azure/automation/troubleshoot/extension-based-hybrid-runbook-worker) it looks like system-assigned managed identity is not enabled on our VMs:

![Screenshot 2023-03-03 at 13 31 58](https://user-images.githubusercontent.com/5486164/222733304-8b7b0632-b9b1-4d6a-aa17-34565de512f6.png)

**Comment by edwardchalstrey1** [comment]
### Troubleshoot VM extension-based Hybrid Runbook Worker issues in Automation

- [x] Check the OS is supported and the prerequisites have been met. See [Prerequisites](https://learn.microsoft.com/en-us/azure/automation/extension-based-hybrid-runbook-worker-install#prerequisites).
    - Yes

- [x] Check whether the system-assigned managed identity is enabled on the VM. Azure VMs and Arc enabled Azure Machines should be enabled with a system-assigned managed identity.
    - No

- [ ] Check whether the extension is enabled with the right settings. Setting file should have right AutomationAccountURL. Cross-check the URL with Automation account property - AutomationHybridServiceUrl. 

    For windows: you can find the settings file at C:\Packages\Plugins\Microsoft.Azure.Automation.HybridWorker.HybridWorkerForWindows\<version>\RuntimeSettings.
    For Linux: you can find the settings file at /var/lib/waagent/Microsoft.Azure.Automation.HybridWorker.HybridWorkerForLinux/.
    - @jemrobinson do you think this file be on the VM itself? I don't see it when logging into a compute VM as root

- [ ] Check the error message shown in the Hybrid worker extension status/Detailed Status. It contains error message(s) and respective recommendation(s) to fix the issue.

- [ ] Run the troubleshooter tool on the VM and it will generate an output file. Open the output file and verify the errors identified by the troubleshooter tool.

    For windows: you can find the troubleshooter at C:\Packages\Plugins\Microsoft.Azure.Automation.HybridWorker.HybridWorkerForWindows\<version>\bin\troubleshooter\TroubleShootWindowsExtension.ps1
    For Linux: you can find the troubleshooter at /var/lib/waagent/Microsoft.Azure.Automation.HybridWorker.HybridWorkerForLinux-<version>/Troubleshooter/LinuxTroubleshooter.py
    For Linux machines, the Hybrid worker extension creates a hweautomation user and starts the Hybrid worker under the user. Check whether the user hweautomation is set up with the correct permissions. If your runbook is trying to access any local resources, ensure that the hweautomation has the correct permissions to the local resources.

- [ ] Check whether the hybrid worker process is running.

    For Windows: check the Hybrid Worker Service service.
    For Linux: check the hwd. service.
Collect logs:

    For Windows: Run the log collector tool in C:\Packages\Plugins\Microsoft.Azure.Automation.HybridWorker.HybridWorkerForWindows\<version>\bin\troubleshooter\PullLogs.ps1
    Logs are in C:\HybridWorkerExtensionLogs.
    For Linux: Logs are in folders /var/log/azure/Microsoft.Azure.Automation.HybridWorker.HybridWorkerForLinux and /home/hweautomation.

**Comment by jemrobinson** [comment]
Interesting. Here's a VM where updates are working but there's no system-assigned identity.

<img width="468" alt="Screenshot 2023-03-03 at 13 42 30" src="https://user-images.githubusercontent.com/3502751/222735099-746202ca-67a4-4ffd-91c4-27f2632dcef6.png">

<img width="480" alt="Screenshot 2023-03-03 at 13 45 14" src="https://user-images.githubusercontent.com/3502751/222735691-8ec6e2fe-5daa-4209-8f2f-c1a3c13ca33b.png">

**Comment by edwardchalstrey1** [comment]
@jemrobinson I added a screenshot to your previous comment - looks like when I click on the Edon one it shows the 1 Hybrid Workers as well

**Comment by jemrobinson** [comment]
Just to confirm, is it true that:

- all VMs that this is working for show up when doing `Log Analytics workspace > Agents Management > See them in logs`
- all VMs that this is not working for don't show up

**Comment by edwardchalstrey1** [comment]
Hybrid worker troubleshooter doesn't appear to be installed (should be `Microsoft.Azure.Automation.HybridWorker.HybridWorkerForLinux-<version>/Troubleshooter/LinuxTroubleshooter.py`):

```
sresbox2admin:~$ sudo ls /var/lib/waagent/
Certificates.p7m
Certificates.pem
Certificates.xml
DD8B981580F62B2080D6F8160CB402AE50BF90ED.crt
DD8B981580F62B2080D6F8160CB402AE50BF90ED.prv
events
event_status.json
GoalState.1.xml
history
Incarnation
initial_goal_state
logcollector
Microsoft.CPlat.Core.RunCommandLinux-1.0.5
Microsoft.CPlat.Core.RunCommandLinux__1.0.5.zip
Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23
Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux__1.14.23.zip
ovf-env.xml
partition
Protocol
provisioned
published_hostname
run-command
SharedConfig.xml
TransportCert.pem
TransportPrivate.pem
waagent-network-setup.py
WALinuxAgent-2.7.3.0
WALinuxAgent-2.7.3.0.zip
WALinuxAgent-2.8.0.11
WALinuxAgent-2.8.0.11.zip
WALinuxAgent-2.9.0.4
WALinuxAgent-2.9.0.4.zip
WireServerEndpoint
```

**Comment by jemrobinson** [comment]
> Hybrid worker troubleshooter doesn't appear to be installed

... and for a VM where updates are working it *is* installed?

**Comment by edwardchalstrey1** [comment]
> ... and for a VM where updates are working it is installed?

No
![Screenshot 2023-03-03 at 13 57 23](https://user-images.githubusercontent.com/5486164/222738477-3c6b5a76-2789-4eb2-91a6-d0d5032797a3.png)

**Comment by edwardchalstrey1** [comment]
> Just to confirm, is it true that:

> - all VMs that this is working for show up when doing Log Analytics workspace > Agents Management > See them in logs
> - all VMs that this is not working for don't show up

@jemrobinson where should I be seeing them here?

![Screenshot 2023-03-03 at 14 00 05](https://user-images.githubusercontent.com/5486164/222739093-379d6a6d-999a-47ce-991d-f85a13d58ea9.png)

**Comment by jemrobinson** [comment]
It's in "Agents Management" not "Legacy agents management"

<img width="999" alt="Screenshot 2023-03-03 at 14 03 08" src="https://user-images.githubusercontent.com/3502751/222739637-6b4848cb-9739-4972-9eeb-5f4649746fcf.png">

or you can just click on "Logs" and enter this query directly:

```
Heartbeat
| where OSType == 'Linux'
| summarize arg_max(TimeGenerated, *) by SourceComputerId
| sort by Computer
| render table
```

**Comment by edwardchalstrey1** [comment]
weird that for you it's called "Agents management" and just "Agents" on mine

**Comment by edwardchalstrey1** [comment]
> > Just to confirm, is it true that:
> 
> > * all VMs that this is working for show up when doing Log Analytics workspace > Agents Management > See them in logs
> > * all VMs that this is not working for don't show up

Looks this way yes

**Comment by jemrobinson** [comment]
> > > Just to confirm, is it true that:
> > 
> > 
> > > * all VMs that this is working for show up when doing Log Analytics workspace > Agents Management > See them in logs
> > > * all VMs that this is not working for don't show up
> 
> Looks this way yes

OK, so can we try disconnecting and reconnecting a VM from LogAnalytics. I think this will require:

- delete the HybridWorker for that VM
- delete the MicrosoftMonitoringAgent (for Windows VMs) or OmsAgentForLinux (for Linux VMs) VM extension for that VM
- re-connect by running `Setup_SRE_Monitoring.ps1`
- check if the VM is now connected using the method above

**Comment by edwardchalstrey1** [comment]
Ok sure, it just so happens I have just deployed another SRE that we can mess with (`sbox2`):

- [ ] delete the HybridWorker for that VM
- [ ] delete the MicrosoftMonitoringAgent (for Windows VMs) or OmsAgentForLinux (for Linux VMs) VM extension for that VM
- [ ] re-connect by running Setup_SRE_Monitoring.ps1
- [ ] check if the VM is now connected using the method above

**Comment by jemrobinson** [comment]
OK, but let's confirm that the VMs in this SRE are *not* working before trying to fix them :)

**Comment by edwardchalstrey1** [comment]
> OK, but let's confirm that the VMs in this SRE are not working before trying to fix them :)

Can I double check what we mean by "not working"

For `sbox2` we have the following:

### Hybrid worker groups

1. Guacamole VM
2. Compute VM

![Screenshot 2023-03-03 at 14 26 08](https://user-images.githubusercontent.com/5486164/222745795-9ef6468a-0bcf-4493-b946-0becef2a2929.png)

### Logs

Looks like just Guacamole

![Screenshot 2023-03-03 at 14 24 27](https://user-images.githubusercontent.com/5486164/222746059-d086b92f-f695-4a8d-999b-c6099bcbdbdb.png)

### Azure Query finds...

1. Guacamole
2. Cocalc

![Screenshot 2023-03-03 at 14 25 16](https://user-images.githubusercontent.com/5486164/222746161-6b2ec30f-841b-4512-bc89-7702cbf3f325.png)

**Comment by jemrobinson** [comment]
You're not seeing all the VMs (since CoCalc and CodiMD don't have SBOX2 in their name). Try adding a filter on the resource group eg.

```
Heartbeat
| where OSType == 'Linux'
| where Category != 'Azure Monitor Agent'
| where ResourceGroup contains 'sbox2'
| summarize arg_max(TimeGenerated, *) by SourceComputerId
| sort by Computer
| render table
```

and you should see

- GUACAMOLE-SRE-SBOX2
- GITLAB
- CODIMD
- COCALC

The same thing will also apply to the Hybrid Worker Groups.

**Comment by edwardchalstrey1** [comment]
Ok so that's true, and it's the same case for other SREs where the update management isn't working (all of them I thought), so this SRE (sbox2) counts as "not working" I assume?

query only finds guacamole:

![Screenshot 2023-03-03 at 14 40 08](https://user-images.githubusercontent.com/5486164/222749258-7720acb2-e65d-443b-a562-fa7fe20f4b43.png)

**or does it...!**
![Screenshot 2023-03-03 at 14 47 32](https://user-images.githubusercontent.com/5486164/222750617-0fa6dc39-ae2f-48dd-8cb9-dca7c0126f9c.png)

**Comment by jemrobinson** [comment]
Can you change the scheduled time for `sre-sbox2-linux-updates` from the current value (every 7 days at starting next Tuesday at 02:02) to every 1 hours starting at 03/03/2023 15:00? This way it will run in 15 minutes time and we can see what it runs over.

**Comment by edwardchalstrey1** [comment]
hmm, didn't seem to run, will investigate - oh, wrong date, well it should run at 4pm now

**Comment by edwardchalstrey1** [comment]
Weird, said it was going to run at 4 but didn't
![Screenshot 2023-03-03 at 16 04 41](https://user-images.githubusercontent.com/5486164/222768963-cc74a945-43ec-42b1-aaf6-6d16bcb80b17.png)
![Screenshot 2023-03-03 at 16 04 33](https://user-images.githubusercontent.com/5486164/222768966-1366a87a-0558-4fe6-8dad-4c32db039980.png)

**Comment by jemrobinson** [comment]
Maybe you just needed to wait for it to finish - seems to have run now.

<img width="1270" alt="Screenshot 2023-03-03 at 16 07 59" src="https://user-images.githubusercontent.com/3502751/222769457-992ce92e-6e85-4093-80df-a6b9978a4dc2.png">

if you click on this you can see which VMs it ran over and it seems to be all 5 VMs in the SRE without missing any.

<img width="760" alt="Screenshot 2023-03-03 at 16 08 46" src="https://user-images.githubusercontent.com/3502751/222769619-cd181d3f-0182-49e4-8146-07f0daeae680.png">

so it's possible that the problem is that the query preview is not the same as what actually gets run? We can test this by changing another schedule that has been failing in the past.

**Comment by edwardchalstrey1** [comment]
For `dsggw` for example the latest run looks like this - so I think you may be right that `sbox2` isn't a good one to test this on:

![Screenshot 2023-03-03 at 16 38 07](https://user-images.githubusercontent.com/5486164/222776719-0e6c60e1-0f3d-4a93-89b6-783a517c1ac9.png)

**Comment by jemrobinson** [comment]
OK, so can you update the timing on this one so it will run tonight? Just need to change start date from 28/02/2023 to 04/03/2023.

I think this might work since looking here (https://learn.microsoft.com/en-us/azure/automation/troubleshoot/update-management?WT.mc_id=Portal-Microsoft_Azure_Automation#nologs) I can see that 

- required updates are listed for SRE-DSGGW-160-SRD-20-04-2022112900 from the Update Management view of the VM (see image attached below)
- the VM is visible from the Update Management view of the Azure Automation account
- it shows as "Non-compliant" under compliance (ie. it has been assessed as needing some updates)

in this particular case, it looks like the problem is that the update job simply hasn't run recently.

<img width="955" alt="Screenshot 2023-03-03 at 17 35 29" src="https://user-images.githubusercontent.com/3502751/222789145-cc113d77-e132-444f-a62b-8a0d9e4b9aed.png">

**Comment by jemrobinson** [comment]
Here's a VM that I think is *not* working and it seems to be due to an issue with the update agent.

<img width="1003" alt="Screenshot 2023-03-03 at 17 33 11" src="https://user-images.githubusercontent.com/3502751/222788599-71b1ff8f-cd6f-440e-b69f-e9bff089de23.png">

**Comment by edwardchalstrey1** [comment]
Looks like Hybrid runbook worker is ok on this VM - I'll look at the [Steps to fix Multihoming](https://learn.microsoft.com/en-gb/azure/automation/troubleshoot/update-agent-issues-linux#multihoming) which we already identified earlier as having the extra log analytics workspace , but maybe we just need to reinstall "OMS-Agent-for-Linux" after you deleted the extra log analytics workspace @jemrobinson 

I guess we expect the internet connectivity check to fail here as it's tier 3

<img width="1073" alt="Screenshot 2023-03-06 at 09 45 06" src="https://user-images.githubusercontent.com/5486164/223075744-896c79ce-9c6b-4a43-a879-92b0fadeadec.png">

**Comment by jemrobinson** [comment]
@edwardchalstrey1 Did fixing multihoming help? If not, did you try reinstalling the OMS agent?

**Comment by JimMadge** [comment]
Have encountered the same bug. A VM reports being connected to the Log Analytics Workspace, and Automation Account is connected to the Log Analytics Workspace. However, the automation account does not apply updates.

After troubleshooting as Ed did above, Multihoming showed as failed again.
Machine should not be multihomed (connected to >1 Log Analytics Workspace).

**Comment by JimMadge** [comment]
Possible workaround is check for this and redeploy

**Comment by craddm** [comment]
An additional point is adding an SRD manually using `Add_Single_SRD.ps1` doesn't enable automatic updates or install the Oms agent, so needs to be documented that `Setup_SRE_Monitoring.ps1` should also be run after adding an SRD

**Comment by craddm** [comment]
On a newly deployed SRD, there are what seem to be vestigial files for omsagent in `/var/opt/microsoft/omsagent/`. 

<img width="612" alt="image" src="https://github.com/alan-turing-institute/data-safe-haven/assets/5796417/261eb0c2-756e-478e-b917-5df171629392">

This id is the spurious DefaultWorkspace ID, and it is from there that the multihoming issue arises. There is already some kind of record of a workspace showing there, even though the portal shows that there are no extensions installed etc. It is *possible*, from expecting the logs of this omsagent, that this is something MS have running during the deployment of the VM, which never completes because there is no internet access

<img width="821" alt="image" src="https://github.com/alan-turing-institute/data-safe-haven/assets/5796417/0b9524d4-6cb7-49ce-aa48-171152581f48">


So I'm wondering if this is supposed to be deleted once the setup process is complete, but never is.

**Comment by jemrobinson** [comment]
Great detective work @craddm! Could be a problem that occurs during the image building process? Might be worth adding something to the deployment-time cloud-init that deletes the `/var/opt/microsoft/omsagent/` directory and seeing if that helps?

**Comment by JimMadge** [comment]
Perhaps the agent gets installed (or there is an attempt) during the build of the SRD image?
Ensuring those files are deleted, if they exist, in cloud-init could work as long as that happens before the agent gets installed?

**Comment by craddm** [comment]
Can confirm that the agent is there during the SRD image build

**Comment by JimMadge** [comment]
Great, I think the obvious thing to try is a step at the end of the build to `rm -rf` all of that.
