### ISSUE TITLE
Azure Automation Run As Account will retire on September 30, 2023 and will be replaced with Managed Identities

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1409]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Update SHM deployment scripts (and existing SHM deployments) such that the Automation Account set up has "Azure Automation Run As Account" replaced with "Managed Identities".

![Screenshot 2023-02-28 at 14 32 08](https://user-images.githubusercontent.com/5486164/221886034-a39e1b70-4b6f-44c8-b9a4-87a619a441d7.png)

## :steam_locomotive: How could this be done?

Follow: https://learn.microsoft.com/en-gb/azure/automation/migrate-run-as-accounts-managed-identity?tabs=run-as-account

**Comment by jemrobinson** [comment]
I don't think we are using "Run As Account" anywhere. We're also not using Automation Runbooks. Have you identified anywhere that this is a problem?

**Comment by edwardchalstrey1** [comment]
> I don't think we are using "Run As Account" anywhere. We're also not using Automation Runbooks. Have you identified anywhere that this is a problem?

I haven't - made an assumption here - I guess I can close this and we can just reopen if it actually comes up?
