### ISSUE TITLE
Ensure deployment schedules for an SRE in the SHM automation account get removed on SRE teardown

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1410]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Deploying an SRE currently creates deployment schedules in the Update management section of the SHM automation account, but these do not all get deleted by running the SRE teardown script.

## :steam_locomotive: How could this be done?

Edit the `SRE_Teardown.ps1` script in `deployment/administration`

**Comment by edwardchalstrey1** [comment]
See line 196 in `deployment/common/AzureAutomation` there is a function called `Remove-AzAutomationSoftwareUpdateConfiguration`

**Comment by edwardchalstrey1** [comment]
Actually looks like this already exists but there is a bug: https://github.com/alan-turing-institute/data-safe-haven/issues/1362#issuecomment-1429423253

**Comment by craddm** [comment]
Closed, as does not appear to be a bug and the process is now documented - see #1685
