### ISSUE TITLE
Cannot logout of Guacamole

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1436]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** **develop**
- **Browser details:** Chrome
- **Operating system details:** Mac OS

## :no_entry_sign: Describe the problem

![Screenshot 2023-03-21 at 10 09 23](https://user-images.githubusercontent.com/5796417/227965169-3827a135-7cd5-4013-ae51-588007098565.png)

Opening the user menu by clicking the user name at the top right of the screen will give you the option to log out. Clicking that initially looks like it is logging the user out, but after a brief period the user is re-authenticated and redirected back to Guacamole.

## :steam_locomotive: Workarounds or solutions

The problem is with upstream code - this is a known issue with using OpenID Connect for authentication, and thus fixing it depends on an upstream fix - see https://issues.apache.org/jira/browse/GUACAMOLE-519

**Comment by jemrobinson** [comment]
If you're a user and want to log out, you can go to `portal.azure.com` and logout from there.

**Comment by JimMadge** [comment]
> If you're a user and want to log out, you can go to `portal.azure.com` and logout from there.

Is this documented?

Could be a useful tip to avoid an 'unoccupied machine/forgot to lock screen' attack

**Comment by jemrobinson** [comment]
> > If you're a user and want to log out, you can go to `portal.azure.com` and logout from there.
> 
> Is this documented?
> 
> Could be a useful tip to avoid an 'unoccupied machine/forgot to lock screen' attack

Not currently documented as we were worried about how to explain how to log out of the right account (eg. for users who are signed into an institutional Microsoft 365 account). We could definitely add this though.
