### ISSUE TITLE
Unable to install R package from allow list (RPostgreSQL)

### ISSUE THREAD

**Issue by DDelbarre** [alan-turing-institute/data-safe-haven#1439]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [ ] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [X] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 4.0.2
- **Browser details:** Chrome
- **Operating system details:** Chromebook

## :no_entry_sign: Describe the problem

The R package `RPostgreSQL` is listed in the allow list for Tier 3 SREs, but I am having trouble installing it. I tried the following code to install the package:
```
install.packages("RPostgreSQL")
```

When this is run, a "HTTP status was 403 forbidden" error message is returned when it tried to download the package from the repository.

I am able to install other packages from the allow list, so the package repository seems to be working and it seems like an issue specific to this package?

**Comment by edwardchalstrey1** [comment]
Error message:

```
install.packages("RPostgreSQL")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/RPostgreSQL_0.7-5.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/RPostgreSQL_0.7-5.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/RPostgreSQL_0.7-5.tar.gz': HTTP status was '403 Forbidden'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘RPostgreSQL’ failed
```

**Comment by edwardchalstrey1** [comment]
`allowlist-core-r-cran-tier3.list` only has: `RPostgres` whereas `allowlist-full-r-cran-tier3.list` has `RPostgres` and `RPostgreSQL` - so perhaps this has something to do with it - will investigate

**Comment by JimMadge** [comment]
@edwardchalstrey1 is that error message from a test deployment you have?

Something to check first is whether the Nexus allowlists are up to date.

Could you make sure your local allowlists are up to date and run `data-safe-haven/deployment/administration/SHM_Package_Repository_Update_Allowlists.ps1` then see if the problem persists?

**Comment by JimMadge** [comment]
_Also_, I think the process of updating allowlists is missing from the documentation, so we should check and add it if necessary.

**Comment by edwardchalstrey1** [comment]
> Could you make sure your local allowlists are up to date and run data-safe-haven/deployment/administration/SHM_Package_Repository_Update_Allowlists.ps1 then see if the problem persists

Right, I'll check this, maybe no-one ran it for `prod4`

> is that error message from a test deployment you have?

No it's from `edonwrg` SRE

**Comment by edwardchalstrey1** [comment]
@JimMadge Using the full allowlist that includes `RPostgreSQL`:

```
2023-04-13 11:29:11 [   INFO]: Loaded allowlist from '/Users/echalstrey/projects/open_source/data-safe-haven/environment_configs/package_lists/allowlist-full-python-pypi-tier3.list'
2023-04-13 11:29:11 [   INFO]: Loaded allowlist from '/Users/echalstrey/projects/open_source/data-safe-haven/environment_configs/package_lists/allowlist-full-r-cran-tier3.list'
2023-04-13 11:29:11 [   INFO]: Updating allowlists on SHM-PROD4-MANY-REPOSITORY-PROXY-TIER-3...
2023-04-13 11:29:12 [SUCCESS]: [✔] VM 'SHM-PROD4-MANY-REPOSITORY-PROXY-TIER-3' already running.
2023-04-13 11:31:13 [SUCCESS]: [✔] Remote script execution succeeded
```

So seems all good, but I still get the 403 error when trying to install the package in R

`cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/RPostgreSQL_0.7-5.tar.gz': HTTP status was '403 Forbidden'`

Does this^ suggest that there is a permissions issue?

> The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it

I got this when logged into the compute VM as admin and opening R with sudo permissions `sreedonwrgadmin:~$ sudo R`
But as Daniel notes, it is possible to install other packages.

**Comment by JimMadge** [comment]
Interesting. I can't remember what error we expect when something isn't on the allowlist, maybe it should be 404.

Could you try installing something which is definitely _not_ on the allowlist for comparison?

**Comment by edwardchalstrey1** [comment]
> Interesting. I can't remember what error we expect when something isn't on the allowlist, maybe it should be 404.
> 
> Could you try installing something which is definitely _not_ on the allowlist for comparison?

Actually when trying to install an R package from CRAN that's not in the allowlist we get the same error:

```
> install.packages("A3")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘pbapply’

trying URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/pbapply_1.7-0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/pbapply_1.7-0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/pbapply_1.7-0.tar.gz': HTTP status was '403 Forbidden'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘pbapply’ failed
trying URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/A3_1.0.0.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/A3_1.0.0.tar.gz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://10.10.3.198:80/repository/cran-proxy/src/contrib/A3_1.0.0.tar.gz': HTTP status was '403 Forbidden'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘A3’ failed
```

**Comment by edwardchalstrey1** [comment]
But just to confirm, `RPostgreSQL` is definitely in `allowlist-full-r-cran-tier3.list`. There is also `allowlist-core-r-cran-tier3.list` which doesn't have that package, however this file doesn't seem to get used by `SHM_Package_Repository_Update_Allowlists.ps1` based on my printout (see the 2nd line):

```
2023-04-13 11:29:11 [   INFO]: Loaded allowlist from '/Users/echalstrey/projects/open_source/data-safe-haven/environment_configs/package_lists/allowlist-full-python-pypi-tier3.list'
2023-04-13 11:29:11 [   INFO]: Loaded allowlist from '/Users/echalstrey/projects/open_source/data-safe-haven/environment_configs/package_lists/allowlist-full-r-cran-tier3.list'
2023-04-13 11:29:11 [   INFO]: Updating allowlists on SHM-PROD4-MANY-REPOSITORY-PROXY-TIER-3...
2023-04-13 11:29:12 [SUCCESS]: [✔] VM 'SHM-PROD4-MANY-REPOSITORY-PROXY-TIER-3' already running.
2023-04-13 11:31:13 [SUCCESS]: [✔] Remote script execution succeeded
```

**Comment by edwardchalstrey1** [comment]
@craddm @JimMadge I notice we also had to add `arrow` to a new "extra" allowlist in this [PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1391/files), which isn't documented [here](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/deployment/build_srd_image.html#adding-a-new-r-package) - should I make a PR with `RPostgreSQL` there - how does this work?

**Update:** trying this now: [CI run](https://github.com/alan-turing-institute/data-safe-haven/actions/runs/4690849405/jobs/8314514522)

**Comment by edwardchalstrey1** [comment]
I noticed there are certain other packages in the core R allowlist that don't currently install because of 403 error: e.g. `RPostgres`, `RSQLite`, `RMySQL`

**Comment by edwardchalstrey1** [comment]
I see that the “full” list gets generated as an output file - the fact that `RPostgreSQL` is already there suggests it's a dependency of something else on the core list and should really be installable already

**Comment by JimMadge** [comment]
> @craddm @JimMadge I notice we also had to add `arrow` to a new "extra" allowlist in this [PR](https://github.com/alan-turing-institute/data-safe-haven/pull/1391/files), which isn't documented [here](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/deployment/build_srd_image.html#adding-a-new-r-package) - should I make a PR with `RPostgreSQL` there - how does this work?

`RPostgreSQL` was already in the full allowlist so adding it to extra should make no difference. I will revert that PR.

That documentation looks out of date to me. The current way of doing this is explained [here](https://alan-turing-institute.github.io/data-safe-haven/develop/processes/software_package_approval.html). @edwardchalstrey1 can you make sure these don't clash.

**Comment by edwardchalstrey1** [comment]
> `RPostgreSQL` was already in the full allowlist so adding it to extra should make no difference. I will revert that PR.

Ok makes sense

> That documentation looks out of date to me. The current way of doing this is explained [here](https://alan-turing-institute.github.io/data-safe-haven/develop/processes/software_package_approval.html). @edwardchalstrey1 can you make sure these don't clash.

Sure, in this case though we are not adding anything new, it seems we have uncovered a bug whereby certain packages already on the allowlist for CRAN are un-installable

**Comment by JimMadge** [comment]
> I noticed there are certain other packages in the core R allowlist that don't currently install because of 403 error: e.g. `RPostgres`, `RSQLite`, `RMySQL`

Does make me wonder if this is due to case sensitivity.

@edwardchalstrey1 can you connect to the Nexus web front end in your test environment and have a poke around. It might be worth teaming up on that?

**Comment by craddm** [comment]
Seems like any package that starts with a capital will fail (e.g. `PRROC` and `RColorBrewer` fail), but capitals in the middle are fine (e.g. `matrixStats` installs fine).

Got into the Nexus web interface. The problem is something to do with the content selectors. We need to look at how they are generated. I can fix individual packages by modifying the search term the relevant connector uses to exactly match the package name. Not sure why it only matters when they start with a capital, though.

**Comment by JimMadge** [comment]
> Seems like any package that starts with a capital will fail (e.g. PRROC and RColorBrewer fail), but capitals in the middle are fine (e.g. matrixStats installs fine).

That _is_ odd.

It would be worth looking at the issue tracker, there seem to be similar issues about case sensitivity with repository proxies.

- https://issues.sonatype.org/browse/NEXUS-8764?jql=text%20~%20%22case%20sensitive%22
- https://issues.sonatype.org/browse/NEXUS-12075
- https://issues.sonatype.org/browse/NEXUS-22051

**Comment by JimMadge** [comment]
Other things to check,

- Does this also happen for PyPI packages?
- Does this also happen when there is no allowlist?

**Comment by JimMadge** [comment]
An example which fails to install with a capital letter _not_ at the beginning `package.install("doParallel")`

**Comment by JimMadge** [comment]
The script to build Nexus content selectors takes the package allow lists and modifies the package names _including making all names lowercase_:

https://github.com/alan-turing-institute/data-safe-haven/blob/8a337391c52ec3fa7466646faee30f100064ec45/deployment/safe_haven_management_environment/cloud_init/resources/configure_nexus.py#L599-L620

This was done to fix an issue installing PyPI packages https://github.com/alan-turing-institute/data-safe-haven/issues/1112

Closed here: https://github.com/alan-turing-institute/data-safe-haven/commit/826c3c547a126cecb2d18afec8927f7018ed992e

**Comment by craddm** [comment]
The content selector in Nexus looks like this to start with:

<img width="922" alt="Screenshot 2023-04-18 at 11 18 39" src="https://user-images.githubusercontent.com/5796417/232748684-8e760c44-72b1-4bf7-a91b-ad5f3ad99a19.png">


Changing it to match the package case, as below, then allows installation:
<img width="947" alt="Screenshot 2023-04-18 at 11 19 04" src="https://user-images.githubusercontent.com/5796417/232748899-c173a1c0-770c-42b6-ac39-eabfdf604fc0.png">
