### ISSUE TITLE
Document how to add a new inboundAccessFrom IP address

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1444]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

It's not clear anywhere in the docs how to change the [inboundAccessFrom](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/deployment/deploy_sre_apache_guacamole.html#sre-configuration-properties) property of the config post-deployment - but @craddm has a method to do this via the NSG in Azure

## :memo: Required documentation changes

Add documentation on how to do this [here](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/roles/system_manager/manage_users.html)

**Comment by craddm** [comment]
It somehow doesn't quite feel like that belongs on that specific page, but I'm not sure where else would be better...
