### ISSUE TITLE
Smoke tests fail for Python versions 3.9 and 3.10

### ISSUE THREAD

**Issue by eeelllccc** [alan-turing-institute/data-safe-haven#1455]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS 
- **Data Safe Haven version:** v4.04 

## :cactus: Powershell module versions
2023-05-04 11:52:12 [WARNING]: Powershell version: 7.3.3
2023-05-04 11:52:12 [WARNING]: The currently supported version of Powershell is 7.3.2.
2023-05-04 11:52:12 [WARNING]: In case of errors originating from Powershell code, ensure that you are running the currently supported version.
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Resources module version: 6.5.1
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.MonitoringSolutions module version: 0.1.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.DataProtection module version: 0.4.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.RecoveryServices module version: 5.4.1
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Automation module version: 1.9.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Poshstache module version: 0.1.10
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Accounts module version: 2.12.1
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.KeyVault module version: 4.9.1
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.PrivateDns module version: 1.0.3
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Dns module version: 1.1.2
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Network module version: 5.3.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Microsoft.Graph.Identity.DirectoryManagement module version: 1.21.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Compute module version: 5.3.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Storage module version: 4.7.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.OperationalInsights module version: 3.1.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Az.Monitor module version: 3.0.1
2023-05-04 11:52:12 [SUCCESS]: [✔] Microsoft.Graph.Authentication module version: 1.21.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Microsoft.Graph.Applications module version: 1.21.0
2023-05-04 11:52:12 [SUCCESS]: [✔] Powershell-Yaml module version: 0.4.2
2023-05-04 11:52:12 [SUCCESS]: [✔] Microsoft.Graph.Users module version: 1.21.0

## :no_entry_sign: Describe the problem
After deployment with config variable:
```
"computeVmImage": {
        "type": "Ubuntu",
        "version": "20.04.2023031401"
     }
```
the smoke tests fail for python versions 3.9 and 3.10, with output shown in the log section below.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>
smoke test output:

```
 ✓ Julia packages
 ✓ Julia functionality
 ✗ Python packages (3.9)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_packages' in file run_all_tests.bats, line 28,
    in test file run_all_tests.bats, line 67)
     `test_python_packages '3.9'' failed
   pyenv: version `3.9.15 3.9.16' not installed
 ✗ Python functionality (3.9)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_functionality' in file run_all_tests.bats, line 21,
    in test file run_all_tests.bats, line 70)
     `test_python_functionality '3.9'' failed
   pyenv: version `3.9.15 3.9.16' not installed
 ✗ Python virtual environments (3.9)
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 186,
    from function `test_python_virtual_environments' in file run_all_tests.bats, line 45,
    in test file run_all_tests.bats, line 73)
     `test_python_virtual_environments '3.9'' failed
   
   -- output does not contain substring --
   substring (1 lines):
     All tests passed for Python 3.9.15 3.9.16
   output (20 lines):
     Preparing to test Python 3.9.15 with virtual environment 3.9.15-test
[x] Testing that pyenv existsxists
[✔] Testing pyenv versionssions
[✔] Testing pyenv virtualenvslenvs
[✔] Testing virtualenv creationation
[✔] Testing virtualenv activationation
[✔] Testing Python versionrsion
     [ ] Testing virtualenv packages
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
     [✔] Testing virtualenv packages
     [ ] Testing virtualenv package installation
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
   
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
     [✔] Testing virtualenv package installation
[✔] Testing virtualenv deletionetion
     All tests passed for Python 3.9.15
   --
   
 ✗ Python package repository (3.9)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_repository' in file run_all_tests.bats, line 35,
    in test file run_all_tests.bats, line 76)
     `test_python_repository '3.9'' failed
   pyenv: version `3.9.15 3.9.16' not installed
 ✗ Python packages (3.10)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_packages' in file run_all_tests.bats, line 28,
    in test file run_all_tests.bats, line 81)
     `test_python_packages '3.10'' failed
   pyenv: version `3.10.8 3.10.10' not installed
 ✗ Python functionality (3.10)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_functionality' in file run_all_tests.bats, line 21,
    in test file run_all_tests.bats, line 85)
     `test_python_functionality '3.10'' failed
   pyenv: version `3.10.8 3.10.10' not installed
 ✗ Python virtual environments (3.10)
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 186,
    from function `test_python_virtual_environments' in file run_all_tests.bats, line 45,
    in test file run_all_tests.bats, line 88)
     `test_python_virtual_environments '3.10'' failed
   
   -- output does not contain substring --
   substring (1 lines):
     All tests passed for Python 3.10.8 3.10.10
   output (20 lines):
     Preparing to test Python 3.10.8 with virtual environment 3.10.8-test
[x] Testing that pyenv existsxists
[✔] Testing pyenv versionssions
[✔] Testing pyenv virtualenvslenvs
[✔] Testing virtualenv creationation
[✔] Testing virtualenv activationation
[✔] Testing Python versionrsion
     [ ] Testing virtualenv packages
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
     [✔] Testing virtualenv packages
     [ ] Testing virtualenv package installation
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
   
     [notice] A new release of pip is available: 23.0.1 -> 23.1.2
     [notice] To update, run: python3.10 -m pip install --upgrade pip
     [✔] Testing virtualenv package installation
[✔] Testing virtualenv deletionetion
     All tests passed for Python 3.10.8
   --
   
 ✗ Python package repository (3.10)
   (from function `pyenv' in file run_all_tests.bats, line 31,
    from function `setup_python' in file run_all_tests.bats, line 15,
    from function `test_python_repository' in file run_all_tests.bats, line 35,
    in test file run_all_tests.bats, line 91)
     `test_python_repository '3.10'' failed
   pyenv: version `3.10.8 3.10.10' not installed
 ✓ Python packages (3.11)
 ✓ Python functionality (3.11)
 ✓ Python virtual environments (3.11)
 ✓ Python package repository (3.11)
 ✓ R packages
 ✓ R functionality
 ✓ R package repository
 ✓ Mounted drives (/data)
 ✓ Mounted drives (/home)
 ✓ Mounted drives (/output)
 ✓ Mounted drives (/shared)
 ✓ Mounted drives (/scratch)

```

</details>

## :recycle: To reproduce
- Deploy an SRE with config option:
```
"computeVmImage": {
        "type": "Ubuntu",
        "version": "20.04.2023031401"
     }
```
- Run smoke tests

**Comment by JimMadge** [comment]
Thanks @edchapman88!

One thing to note, `"version": "20.04.2023031401"` is quite old, certainly older than the v4.0.4-beta branch. (And older than a [change to the SRD image](https://github.com/alan-turing-institute/data-safe-haven/pull/1421)).

Can we see what happens if you build a new SRD image from the commit you have checked out?

I'm not sure if that will fix the problems, but at the moment we are looking at a potentially incompatible combination of SRD image and tests. We would want to know if this problem still occurs with and image and tests from the same commit.

**Comment by edwardchalstrey1** [comment]
> Thanks @edchapman88!
> 
> One thing to note, `"version": "20.04.2023031401"` is quite old, certainly older than the v4.0.4-beta branch. (And older than a [change to the SRD image](https://github.com/alan-turing-institute/data-safe-haven/pull/1421)).
> 
> Can we see what happens if you build a new SRD image from the commit you have checked out?
> 
> I'm not sure if that will fix the problems, but at the moment we are looking at a potentially incompatible combination of SRD image and tests. We would want to know if this problem still occurs with and image and tests from the same commit.

@JimMadge Where can we see what the latest SRD image build should be besides the [example configs](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/environment_configs/sre_greent3guac_core_config.json)?

How often are we updating the build? I copied `20.04.2023031401` from that PR you linked, so I assumed this is the most recent?

**Comment by edwardchalstrey1** [comment]
Following from the above, would the right way to do things be that for each release we [build a new image](https://alan-turing-institute.github.io/data-safe-haven/develop/deployment/build_srd_image.html)?

**Comment by JimMadge** [comment]
> @JimMadge Where can we see what the latest SRD image build should be besides the [example configs](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/environment_configs/sre_greent3guac_core_config.json)?

You can see the images in the image gallery. We shouldn't think of the examples as a recommendation for which image to use, or which is the latest. The builds are not reproducible so if you didn't build the version named there that information isn't of much use.

> How often are we updating the build? I copied 20.04.2023031401 from that PR you linked, so I assumed this is the most recent?
> 
> Following from the above, would the right way to do things be that for each release we [build a new image](https://alan-turing-institute.github.io/data-safe-haven/develop/deployment/build_srd_image.html)?

My mistake! It looks like that version was built for that PR.

I think these are the wrong questions. The situation is we have scripts to create an image gallery and, build and deploy SRD images to that gallery. This isn't a public service we offer (at least not now). Each operator needs to build and maintain their images.

You will need to build new images as often as you require. It is probably a good idea to do it for each deployment. Absolutely should be done when there have been changes to the code which builds the base image. There have been a few package version updates since March.

**Comment by edwardchalstrey1** [comment]
Ok thanks @JimMadge , makes sense. So I'll build a new image from the 4.0.4 release branch and push it to the gallery.

@edchapman88 When I've done this I'll let you know and I'll update the configs for the May DSG SREs, and you can deploy a new SRD with the new config, but you won't need to deploy the whole SRE as we discussed, just remember to use a different ipLastOctet

**Comment by JimMadge** [comment]
``   pyenv: version `3.9.15 3.9.16' not installed``
``   pyenv: version `3.10.8 3.10.10' not installed``

These look odd.

Are there multiple patch versions of each minor version installed?
Are the smoke test scripts trying to run, for example, `pyenv 3.9.15 3.9.16`

**Comment by edwardchalstrey1** [comment]
In the Sandbox SRE which uses the older `20.04.2022112900` image, the following Python versions are installed:

```
ed.chalstrey1:tests$ pyenv versions
  system
  3.8.15
* 3.9.15 (set by /home/ed.chalstrey1/.pyenv/version)
  3.10.8
```

**Comment by edwardchalstrey1** [comment]
This might be related to us deploying multiple SRDs into the same SRE with different Python versions

**Comment by JimMadge** [comment]
But we need to know about `20.04.2023031401` (or later?) where the tests are failing.

I don't think multiple SRD versions in the same SRE should matter. The smoke tests are built and copied to the SRDs when they are deployed. They are independent from each other.

**Comment by edwardchalstrey1** [comment]
Ok, I'm deploying another SRE/SRD with `20.04.2023031401` and I'll see if it has the same problem, then investigate further: but I think before Ed deployed a second SRD with the `20.04.2023031401` image, he used an even older one that I put in the config by mistake - the tests all ran fine except 3.11 was failing, because 3.11 was not installed

**Comment by edwardchalstrey1** [comment]
Ok I've now deployed a fresh SRE with the `20.04.2023031401` image for the SRE and all the smoke tests pass, including Python 3.9, 3.10 and 3.11

@edchapman88 Can you let us know if the problem persists for you if you run the smoke tests on the `20.04.2023031401` SRD after having deleted the SRD that used the older image?

@JimMadge For the May DSG, we've just deployed most of the SREs which use the `20.04.2023031401` image - which we know works. I guess to properly test the `4.0.4` branch, I should create a new image in the gallery and ensure at least one of the SREs we use has an SRD built from that image - would that be a sufficient test of `4.0.4` release as far as you're concerned?

**Comment by JimMadge** [comment]
> @JimMadge For the May DSG, we've just deployed most of the SREs which use the 20.04.2023031401 image - which we know works. I guess to properly test the 4.0.4 branch, I should create a new image in the gallery and ensure at least one of the SREs we use has an SRD built from that image - would that be a sufficient test of 4.0.4 release as far as you're concerned?

Yes we should make sure an image built from that branch works :+1:

**Comment by edwardchalstrey1** [comment]
> Yes we should make sure an image built from that branch works 👍

Ok great, I've made an issue to track this: https://github.com/alan-turing-institute/data-safe-haven-team/issues/21
