### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by cmougan** [alan-turing-institute/data-safe-haven#1473]
Perhaps it could be good to have in the readme all the related paper to the safe haven.

In case researchers want to cite

**Comment by JimMadge** [comment]
Hi @cmougan, we have a [CITATION.cff](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/CITATION.cff) file in the repository. That includes citation for the project as well as the design paper.

From the [main page](https://github.com/alan-turing-institute/data-safe-haven) of the repo you can export a citation a bibtex from the "About" section.

**Comment by cmougan** [comment]
I find this non-intuitive.

If i go to the main page and search for "about" i dont find a bibtex entry.

It's a suggestion for perhaps better dissemination

**Comment by jemrobinson** [comment]
<img width="433" alt="Screenshot 2023-05-23 at 13 20 46" src="https://github.com/alan-turing-institute/data-safe-haven/assets/3502751/e58f128f-4145-4663-bf30-b7de9ef0b78b">

It might not be as clear as it could be, but, as @JimMadge says, there is a "Cite this repository" link on the main page which uses the GitHub-supported method of generating a citation. We may also consider adding this to the README as you suggest.

**Comment by JimMadge** [comment]
There is also the badge in the README (although the link is broken!).

**Comment by jemrobinson** [comment]
I think we're using code citation standards: @cmougan are you happy for us to close this?

**Comment by cmougan** [comment]
Its a suggestion for the authors of the repository. I still dont find a bibtex entry that I can easily cite. Up to the authors @jemrobinson

**Comment by jemrobinson** [comment]
@cmougan: Main page, under the "About" section on the right hand side. Click "Cite this repository" then "BibTeX".

<img width="405" alt="Screenshot 2023-10-06 at 13 21 28" src="https://github.com/alan-turing-institute/data-safe-haven/assets/3502751/269045b6-ea6a-4c1d-aff3-a20e383fb115">
