### ISSUE TITLE
Pulumi: SHM package repositories

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1481]

**Comment by JimMadge** [comment]
Working on container for nexus allow list handling here https://github.com/alan-turing-institute/nexus-allowlist

- Automatic configuration
- Automatic updating of allow lists

Should allow repositories/proxies to be deployed as container instances.

**Comment by JimMadge** [comment]
Might want to consider using https://gitlab.com/thiagocsf/nexus3-cli instead of maintaining our own nexus bindings.

**Comment by JimMadge** [comment]
A difference I've noticed testing this,

When trying to install a disallowed PyPI package, Nexus (presumably) returns a [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) and prompts the user for credentials. _If_ you then use the admin credential you can (as expected) install a disallowed package. In current deployments you instead get a 403 and pip returns a non-zero exit code.

Finding Nexus and interacting with it using the admin credentials was always a risk. The difference here is that pip will prompt users for credentials. I don't think it is a significant reduction in security, perhaps it gives some clues. But it isn't great for users as it is a confusing error compared to the existing situation.

This might be due a difference in Nexus version.

**Comment by JimMadge** [comment]
Note, you can stop the interactive prompt for credentials with `--no-input`. We could set `no-input = True` in `pip.conf` globally.
