### ISSUE TITLE
Configuring external DNS resolution for SRDs fails 

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1503]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop

## :cactus: Powershell module versions

```
2023-07-13 15:49:26 [SUCCESS]: [✔] Powershell version: 7.3.2
2023-07-13 15:49:26 [SUCCESS]: [✔] Microsoft.Graph.Identity.DirectoryManagement module version: 1.21.0
2023-07-13 15:49:26 [SUCCESS]: [✔] Poshstache module version: 0.1.10
2023-07-13 15:49:26 [SUCCESS]: [✔] Microsoft.Graph.Authentication module version: 1.21.0
2023-07-13 15:49:26 [SUCCESS]: [✔] Az.MonitoringSolutions module version: 0.1.0
2023-07-13 15:49:26 [SUCCESS]: [✔] Az.PrivateDns module version: 1.0.3
2023-07-13 15:49:26 [SUCCESS]: [✔] Az.Dns module version: 1.1.2
2023-07-13 15:49:26 [SUCCESS]: [✔] Az.RecoveryServices module version: 5.4.1
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Storage module version: 4.7.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Microsoft.Graph.Users module version: 1.21.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Accounts module version: 2.12.4
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.KeyVault module version: 4.9.1
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Network module version: 5.3.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Compute module version: 5.3.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.DataProtection module version: 0.4.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Powershell-Yaml module version: 0.4.2
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Monitor module version: 4.2.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Resources module version: 6.5.1
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.Automation module version: 1.9.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Microsoft.Graph.Applications module version: 1.21.0
2023-07-13 15:49:27 [SUCCESS]: [✔] Az.OperationalInsights module version: 3.1.0
```

## :no_entry_sign: Describe the problem

During the `Apply_SRE_Network_Configuration` step of deployment, the remote script that configures external DNS resolution on DC1 fails, claiming that the value of the FQDN parameter is incorrect. 

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
2023-07-13 15:14:38 [   INFO]: Configuring external DNS resolution for SRDs via DC1-SHM-BLUE...
2023-07-13 15:15:39 [   INFO]: Script output:


Value[0]        : 
  Code          : ComponentStatus/StdOut/succeeded
  Level         : Info
  DisplayStatus : Provisioning succeeded
  Message       : date.microsoft.com,ssprdedicatedsbprodncu.serv
icebus.windows.net,ssprdedicatedsbprodscu.servicebus.windows.net,strongauthenticationservice.auth.microsoft.com,stzn-jo
bruntimedata-prod-su1.azure-automation.net,test.stats.update.microsoft.com,time.google.com,time1.google.com,time2.googl
e.com,time3.google.com,time4.google.com,tlu.dl.delivery.mp.microsoft.com,ubuntu.qgis.org,uks-jobruntimedata-prod-su1.az
ure-automation.net,umwatson.events.data.microsoft.com,usge-jobruntimedata-prod-su1.azure-automation.us,v10.events.data.
microsoft.com,v10.vortex-win.data.microsoft.com,v20.events.data.microsoft.com,wcus-jobruntimedata-prod-su1.azure-automa
tion.net,we-jobruntimedata-prod-su1.azure-automation.net,windowsupdate.microsoft.com,wus2-jobruntimedata-prod-su1.azure
-automation.net,www.office.com,www.powershellgallery.com provided in criteria Fqdn is invalid.
 [x] Failed to apply DNS policies to client subnet 'sre-t3guac-10.153.5.0_24'
The value EQ,*-sb.servicebus.windows.net,aadcdn.msftauth.net,aadconnecthealth.azure.com,ac-jobruntimedata-prod-su1.azur
e-automation.net,adhsprodncuaadsynciadata.blob.core.windows.net,adhsprodwcuaadsynciadata.blob.core.windows.net,adhsprod
weuaadsynciadata.blob.core.windows.net,adhsprodweuehsyncia.servicebus.windows.net,adhsprodwusaadsynciadata.blob.core.wi
ndows.net,adhssyncprodpksweu.servicebus.windows.net,adminwebservice.microsoftonline.com,adnotifications.windowsazure.co
m,ae-jobruntimedata-prod-su1.azure-automation.net,apt.postgresql.org,archive.ubuntu.com,ase-jobruntimedata-prod-su1.azu
re-automation.net,au.download.windowsupdate.com,azure.archive.ubuntu.com,cc-jobruntimedata-prod-su1.azure-automation.ne
t,changelogs.ubuntu.com,cid-jobruntimedata-prod-su1.azure-automation.net,cran.r-project.org,credentials.azure.com,crl.m
icrosoft.com,crl3.digicert.com,crl4.digicert.com,css.phonefactor.net,ctldl.windowsupdate.com,current.cvd.clamav.net,d20
rj4el6vkp4c.cloudfront.net,database.clamav.net,database.clamav.net.cdn.cloudflare.net,dbeaver.io,developer.download.nvi
dia.com,download.microsoft.com,download.windowsupdate.com,eus2-jobruntimedata-prod-su1.azure-automation.net,fe2cr.updat
e.microsoft.com,fe3cr.delivery.mp.microsoft.com,files.pythonhosted.org,geo-prod.do.dsp.mp.microsoft.com,go.microsoft.co
m,jpe-jobruntimedata-prod-su1.azure-automation.net,login.live.com,login.microsoftonline.com,login.windows.net,managemen
t.azure.com,ne-jobruntimedata-prod-su1.azure-automation.net,ntservicepack.microsoft.com,ocsp.digicert.com,onegetcdn.azu
reedge.net,packages.gitlab.com,packages.microsoft.com,passwordreset.microsoftonline.com,pfd.phonefactor.net,pfd2.phonef
actor.net,policykeyservice.dc.ad.msft.net,*.agentsvc.azure-automation.net,*.azure-automation.net,*.blob.core.windows.ne
t,*.monitor.azure.com,*.ods.opinsights.azure.com,*.oms.opinsights.azure.com,provisioningapi.microsoftonline.com,psg-pro
d-eastus.azureedge.net,pypi.org,qgis.org,s1.adhybridhealth.azure.com,scus-jobruntimedata-prod-su1.azure-automation.net,
sea-jobruntimedata-prod-su1.azure-automation.net,secure.aadcdn.microsoftonline-p.com,security.ubuntu.com,settings-win.d
ata.microsoft.com,shmblueartifactsanoblwvs.blob.core.windows.net,slscr.update.microsoft.com,ssprdedicatedsbprodncu.serv
icebus.windows.net,ssprdedicatedsbprodscu.servicebus.windows.net,strongauthenticationservice.auth.microsoft.com,stzn-jo
bruntimedata-prod-su1.azure-automation.net,test.stats.update.microsoft.com,time.google.com,time1.google.com,time2.googl
e.com,time3.google.com,time4.google.com,tlu.dl.delivery.mp.microsoft.com,ubuntu.qgis.org,uks-jobruntimedata-prod-su1.az
ure-automation.net,umwatson.events.data.microsoft.com,usge-jobruntimedata-prod-su1.azure-automation.us,v10.events.data.
microsoft.com,v10.vortex-win.data.microsoft.com,v20.events.data.microsoft.com,wcus-jobruntimedata-prod-su1.azure-automa
tion.net,we-jobruntimedata-prod-su1.azure-automation.net,windowsupdate.microsoft.com,wus2-jobruntimedata-prod-su1.azure
-automation.net,www.office.com,www.powershellgallery.com provided in criteria Fqdn is invalid.

Disabling DNS cache...
 [o] Successfully disabled DNS cache.
Value[1]        : 
  Code          : ComponentStatus/StdErr/succeeded
  Level         : Info
  DisplayStatus : Provisioning succeeded
  Message       : 
Status          : Succeeded
Capacity        : 0
Count           : 0



2023-07-13 15:15:39 [FAILURE]: [x] Remote script execution has failed. Please check the output above before re-running this script.
```

</details>

## :recycle: To reproduce

Try running the `Apply_SRE_Network_Configuration` script, either as part of a deployment of a new SRE or on an already existing SRE.

**Comment by JimMadge** [comment]
https://github.com/alan-turing-institute/data-safe-haven/blob/50c93f9d8584ed12363692f04dabf4d1974f711d/deployment/secure_research_environment/remote/network_configuration/scripts/Configure_External_DNS_Queries_Remote.ps1#L84

[-Fqdn argument rules](https://learn.microsoft.com/en-us/powershell/module/dnsserver/add-dnsserverqueryresolutionpolicy?view=windowsserver2022-ps#-fqdn)

@craddm can you look through the log to see if you can find why that string in invalid?
@jemrobinson do you know where `$AllowedFqdns` is defined, it may be that an update to that list has caused the problem.

**Comment by craddm** [comment]
https://github.com/alan-turing-institute/data-safe-haven/blob/50c93f9d8584ed12363692f04dabf4d1974f711d/deployment/secure_research_environment/setup/Configure_External_DNS_Queries.ps1#L25-L39

`$AllowedFqdns` comes from https://github.com/alan-turing-institute/data-safe-haven/blob/develop/deployment/safe_haven_management_environment/network_rules/shm-firewall-rules.json

That changed 2 months ago when we fixed the service bus issue in https://github.com/alan-turing-institute/data-safe-haven/commit/7a1b29e24fd22b74ca0526b805b6c10d02a9e60c

The change there was to use a wildcard instead of individual FQDNS. That in itself shouldn't cause this problem, as there are other wildcards and the docs say wildcards are fine.

Ah, wait, got it.

`*-sb.servicebus.windows.net` covers FQDNs that would previously have been removed by the  line `Where-Object { $_ -notlike "g*.servicebus.windows.net" } | # Remove AzureADConnect password reset endpoints` - that's probably it, will try a fix.

**Comment by JimMadge** [comment]
Good spot!
Not sure if that causes the problem but it does look odd. Why include items in the list if the first thing you do is remove them?

Maybe what we want to do then is include `*-sb.servicebus.windows.net` and exclude `g*.servicebus.windows.net` so that the **exclude takes precedence over the include**.
@jemrobinson ?

**Comment by jemrobinson** [comment]
In the place where the rules get applied

https://github.com/alan-turing-institute/data-safe-haven/blob/50c93f9d8584ed12363692f04dabf4d1974f711d/deployment/secure_research_environment/remote/network_configuration/scripts/Configure_External_DNS_Queries_Remote.ps1#L84-L88

the logic is:

l.84: for any FQDN on the "allow" list, allow DNS name resolution to recurse to the fallback DNS server (which is Azure DNS)
l.87: for any FQDN not on the "allow" list, apply the default (recursion permitted or recursion blocked). The default depends on the tier of the SRE.
