### ISSUE TITLE
Consider renaming methods shadowing builtins

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1512]
There are a number of cases of method names which shadow Python builtin functions.
For example,

https://github.com/alan-turing-institute/data-safe-haven/blob/f0a890632725e2b6883c8997787294b824caa1cb/data_safe_haven/administration/users/user_handler.py#L96-L101

https://github.com/alan-turing-institute/data-safe-haven/blob/f0a890632725e2b6883c8997787294b824caa1cb/data_safe_haven/administration/users/user_handler.py#L159-L164

We should consider renaming these to avoid confusion or problems overwriting a builtin function within the classes namespace.

For example, `list` could be `list_users` to `to_list`.

**Comment by jemrobinson** [comment]
@JimMadge : Which linting settings highlight this as a problem? I couldn't reproduce it.

**Comment by JimMadge** [comment]
The 'A' rules I think https://docs.astral.sh/ruff/rules/#flake8-builtins-a

**Comment by jemrobinson** [comment]
Yeah - I tried enabling all of them and I couldn't get these to flag up again.

**Comment by JimMadge** [comment]
Closing as no linting errors are now raised.

**Comment by jemrobinson** [comment]
More weird than that - I couldn't even find a version of black/ruff/mypy that reproduces this warning.

**Comment by JimMadge** [comment]
Yeah, I think they only raise errors for functions/objects shadowing builtins rather than methods.
