### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1513]
There is a magic number in the code here:

https://github.com/alan-turing-institute/data-safe-haven/blob/f0a890632725e2b6883c8997787294b824caa1cb/data_safe_haven/administration/users/active_directory_users.py#L88-L98

It isn't clear what this number represents and there isn't handling for when it is `<6`.

**Comment by jemrobinson** [comment]
Happy to make a quick fix for this but do you want it to be before or after #1506 @JimMadge ?

**Comment by JimMadge** [comment]
After please 😱
