### ISSUE TITLE
Pulumi: Type of Config parameter errors

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1515]
We should change the `ValueError`s to `DataSafeHavenError`s. Possibly `DataSafeHavenInputError` or `DataSafeHavenParameterError`.

_Originally posted by @jemrobinson in https://github.com/alan-turing-institute/data-safe-haven/pull/1506#discussion_r1272516663_

**Comment by JimMadge** [comment]
closed in #1530
