### ISSUE TITLE
Pulumi: Refactor Typer commands

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1529]
> One thing I'm not sure about,
>
> The Typer commands are all (or almost all) just wrappers for a classes `__call__` method. It feels like unecessary boiler plate when the contents of the `__call__` method could just be in the functions decorated with `Typer.command`. Especially as the `__init__` methods of the classes I remember only create a reference to the logger singleton.
>
> I'm thinking,
>
> - Is there a strong advantage to having commands as classes
> - If not
>   - Can we remove that pattern now or,
>   - Open an issue to remove it in the future to let this merge now?

_Originally posted by @JimMadge in https://github.com/alan-turing-institute/data-safe-haven/pull/1502#pullrequestreview-1538897401_

**Comment by JimMadge** [comment]
We still have a few of these hanging around?

**Comment by jemrobinson** [comment]
Where?

**Comment by JimMadge** [comment]
Oh, I meant. We must still have some because the issue is open, but I see #1530 is closed :smile:.

**Comment by jemrobinson** [comment]
Issues only auto-close on merge into `develop` and I often forget to close them manually!
