### ISSUE TITLE
Pulumi: Rename SRD to workspace

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1531]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Change naming of SRDs to Workspaces in line with SATRE

**Comment by JimMadge** [comment]
Closed by #1532
