### ISSUE TITLE
Release: 4.1.0

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1544]
## :white_check_mark: Checklist

Refer to the [Deployment](https://data-safe-haven.readthedocs.io/en/latest/deployment) section of our documentation when completing these steps.

- [x] Consult the `data-safe-haven/VERSIONING.md` guide and determine the version number of the new release. Record it in the title of this issue.
- [x] Create a release branch called e.g. `release-v0.0.1`
- [x] Draft a changelog for the release similar to our previous releases, see https://github.com/alan-turing-institute/data-safe-haven/releases
- [x] Deploy an SHM from this branch and save a transcript of the deployment logs
- [ ] Build an SRE compute image (SRD) and save transcripts of the logs
- Using the new image, deploy two SREs which between them cover tiers 2 and 3 and Guacamole/Microsoft RDS
    - [ ] Save the transcript of your tier 2 SRE deployment
    - [ ] Save the transcript of your tier 3 SRE deployment
- [ ] Complete the [Security evaluation checklist](https://data-safe-haven.readthedocs.io/en/latest/deployment/security_checklist.html) from the deployment documentation

## :computer: Release information

- **Version number:** 4.1.0
- **SHM ID:** orange (https://github.com/alan-turing-institute/trusted-research/issues/216)
- **T2 SRE ID:** lemon (https://github.com/alan-turing-institute/trusted-research/issues/235)
- **T3 SRE ID:** grape (https://github.com/alan-turing-institute/trusted-research/issues/236)
- **T2 MSRDS SRE ID:** kiwi (https://github.com/alan-turing-institute/trusted-research/issues/240)

## :deciduous_tree: Deployment problems

See https://github.com/alan-turing-institute/data-safe-haven-team/issues/21

Additional PRs: https://github.com/alan-turing-institute/data-safe-haven/pulls?q=is%3Apr+is%3Aclosed+base%3Arelease-v4.1.0+base%3Arelease-v4.0.4

**Comment by edwardchalstrey1** [comment]
@jemrobinson @JimMadge @JimMadge 

I've now completed the checks for the release and can confirm that release 4.1.0 passed the security tests for tier 2 and tier 3 Guacamole SREs 🎉 

The one hiccup is the msrds SRE I deployed - right now I don't think it's a great use of time debugging this, seeing as how we plan to remove it in the next release anyway, but the SRD and webapps couldn't be connected to after log in:

![Screenshot 2023-08-15 at 15 08 09](https://github.com/alan-turing-institute/data-safe-haven/assets/5486164/5f601192-f04a-4143-94f6-d68c78439321)

I think the options are:
1. Debug this and make and changes to the 4.1.0 branch
2. Go ahead and release 4.1.0 as is, with broken msrds and a note saying so
3. Merge the MSRDS removal into 4.1.0 (or call it 4.1.1?)

If there isn't time to do number 1 then I'd like to do one of the alternatives as we want to deploy a 4.1.0 SRE this week for LWM

**Comment by jemrobinson** [comment]
Have you gone through the various debugging steps from https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_sre_microsoft_rds.html#deploy-web-applications-cocalc-codimd-and-gitlab ? What were the results?

**Comment by edwardchalstrey1** [comment]
No I haven't tried to fix it yet, but I can this afternoon

**Edit:** Troubleshooting fixed the issue

**Comment by craddm** [comment]
Closing as superseded by #1585
