### ISSUE TITLE
Drop dependence on lists of external IP addresses/domain names

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1549]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

There are currently a few places where we maintain lists of external IP addresses (eg. the IP addresses of Ubuntu's package servers) or domain names (eg. lists of AzureAD authentication endpoints).

We should try, wherever possible, to replace these with generic wildcarded "allow-all" rules as long as this doesn't cause security issues.

#### Firewall rules
- `AllowExternalAzureAutomationOperations` ApplicationRule could be replaced with a NetworkRule that allows the `GuestAndHybridManagement` service tag (NB. this will need testing, as we haven't verified what this tag allows)
- `AllowExternalAzureADConnectPasswordReset` ApplicationRule could potentially allow `*..servicebus.windows.net` (which is a security risk, but this rule only applies to the DC)
- `AllowExternalAzureADConnectOperations` ApplicationRule could potentially allow `*.blob.core.windows.net` (which is a *large* risk, but this rule only applies to the DC)

#### NSG rules
- `AllowAzureAutomationOutbound` rule on the compute NSG could possibly use the `GuestAndHybridManagement` service tag instead of hard-coded IP addresses

## :steam_locomotive: How could this be done?

Going through the code carefully and evaluating each potential change

**Comment by JimMadge** [comment]
For context, places where this has been a problem previously,

- #742
- #1467
- #1503

Maintaining lists of allowed domains of IP addresses is fragile. This can (and will) change over time. This can cause things to break and we will generally not be aware of the breaking change until it happens. All deployed instances may break at the same time.

If we are confident that machines are well isolated and that compromising them is unlikely, we may be comfortable having less restrictive outbound network rules. These are machines that users should never have access to, and we are reasonably confident that even a deliberate attack would be difficult.

**Comment by JimMadge** [comment]
- [ ] shm-firewall-rules.json

Should go through the rules and make decisions.
Some rules feel fairly reasonable (pypi.org for example). Others, particularly Azure services, have random strings or numbers and presumably are scaled up/down as needed. Wildcard rules could help here, but could also create security problems if made too permissive.

It may be possible to replace hard-coded endpoints with a target (like "Internet" in Azure) or, if the lists are published, fetch them at deploy time.

**Comment by JimMadge** [comment]
Hardcoding domains is problematic is a broader sense. Having to make new releases do deal with changes in domains we don't control is a pain.

We could,

- Make this the problem of system managers
- Have an external list (like https://github.com/StevenBlack/hosts) which TREs fetch from (the same with package allowlists).

**Comment by JimMadge** [comment]
I'm not entirely certain what `AllowExternalAzureAutomationOperations` is for.

It might also want `AzureMonitor` "Log Analytics, Application Insights, AzMon, and custom metrics (GiG endpoints)." https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview

**Comment by jemrobinson** [comment]
> I'm not entirely certain what `AllowExternalAzureAutomationOperations` is for.
> 
> It might also want `AzureMonitor` "Log Analytics, Application Insights, AzMon, and custom metrics (GiG endpoints)." https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview

I think this is the set of domains which an SRD talks to when it wants to report its update status to Azure Automation. Not sure why it can't use the direct link to the Automation Account (which happens inside the VNet through privatelink). I'd be wary of adding too much here as anything you add here is accessible from user-facing computers.
