### ISSUE TITLE
Update Ubuntu images to gen2

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1550]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Currently we use:
- Image publisher: Canonical
- Image offer: 0001-com-ubuntu-server-focal
- Image plan: 20_04-LTS

Azure default for Ubuntu 20.04 is now
- Image publisher: canonical
- Image offer: 0001-com-ubuntu-server-focal
- Image plan: 20_04-lts-gen2

Note that this also changes the default repositories from http://archive.ubuntu.com/ubuntu/ to http://azure.archive.ubuntu.com/ubuntu/ so we'll also need to update the update proxy server and firewall to allow eg. cloud-mirror-lb.uksouth.cloudapp.azure.com.

## :steam_locomotive: How could this be done?

- Update AzureCompute.psm1
- Update update server cloud-init
- Update update server NSG rules
- Update SHM firewall rules

**Comment by JimMadge** [comment]
Azure docs on gen2 https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2

https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/should-i-create-a-generation-1-or-2-virtual-machine-in-hyper-v
> We recommend that you create a generation 2 virtual machine to take advantage of features like Secure Boot unless one of the following statements is true:
> 
>   - You're using an existing, pre-built virtual disk (VHD or VHDX) which is not [compatible with UEFI](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-8.1-and-8/hh824898(v=win.10)).
>   - Generation 2 doesn't support the operating system you want to run on the virtual machine.
>   - Generation 2 doesn't support the boot method you want to use.

So it feels like we are _strongly_ encouraged to use gen2.
We should note that some VM sizes are not compatible with gen2 https://learn.microsoft.com/en-us/azure/virtual-machines/generation-2#generation-2-vm-sizes

**Comment by craddm** [comment]
Is there any reason *not* to switch to gen2? 

At the moment we don't specify the security type in our deployment scripts, as far as I can see, and from the emails I've been getting from Azure, looks like switching to gen2 will also make the VMs we deploy (from November) default to the [`TrustedLaunch` security type](https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch-faq?tabs=cli). 

That's where I can see potential issues with GPU VMs *if* you used the `TrustedLaunch` security type, as that has Secure Boot on by default:

```
Installation of the CUDA driver on Secure Boot enabled Ubuntu VMs requires additional steps documented at [Install NVIDIA GPU drivers on N-series VMs running Linux](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup#install-cuda-driver-on-ubuntu-with-secure-boot-enabled). Secure Boot should be disabled for installing CUDA Drivers on other Linux VMs.
```

Also, our VMs currently have a `standard` backup policy, which'll need to be replaced with an `enhanced` policy with `TrustedLaunch` enabled.

Note that the Windows domain controller is also currently gen1 and could also be updated to gen2. 

We could potentially make the VMs stick with the `Standard` security type if we don't need the Trusted Launch features.

**Comment by JimMadge** [comment]
Somewhat related to #1574 #1892.
Those will support (default to 22.04/24.04).
