### ISSUE TITLE
DSH release v4.0.3 - Powershell version requirement incomplete

### ISSUE THREAD

**Issue by eeelllccc** [alan-turing-institute/data-safe-haven#1567]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?
Under `Software Prerequisites` on [this page](https://alan-turing-institute.github.io/data-safe-haven/v4.0.3/deployment/deploy_sre_apache_guacamole.html).

## :memo: Required documentation changes
The version requirement for Powershell is **v7.0 or above** and it should be **v7.0.0 <= and <= v7.2.8**

The following exception was returned when using v7.3.3:
`Exception: Please downgrade Powershell to a minimum version of 7.0.0 and a maximum of
7.2.8 (currently using 7.3.3)!`

Note: This exception has not be thrown when using Powershell v7.3.3 with release v4.0.4 of DSH previously.

**Comment by jemrobinson** [comment]
@craddm: is <= 7.2.8 still a requirement? From #1361 we found issues with `7.3.0` and `7.3.1` but has anyone tested `7.3.2` or above?

**Comment by craddm** [comment]
The issue was incompatibilities with Powershell `7.3.x` and some of the older versions of modules that we were still allowing, as fixed in #1368. The latest Powershell is `7.3.6` and the latest codebases `develop/4.1.0` work fine with `7.3.6`.

For release `4.0.3`, you could either change the doc to warn people or maybe cherry-pick in the fixes to the list of allowed modules and remove the Powershell version check.

An alternative is to use the `.devcontainer` to deploy using VS Code - shouldn't have any problem then.

**Comment by jemrobinson** [comment]
@edchapman88: This version requirement isn't actually enforced in the code, just suggested. Have you tried running with 7.3.3?

**Comment by eeelllccc** [comment]
@jemrobinson How would I go about running it without calling the [`Deploy_SRE.ps1`](https://github.com/alan-turing-institute/data-safe-haven/blob/develop/deployment/secure_research_environment/setup/Deploy_SRE.ps1) script? Because running that script produced the exception that I included in my original issue.

**Comment by craddm** [comment]
@jemrobinson for that release it was enforced when running the `Deploy_SRE.ps1` script.

@edchapman88 Running each step manually should work, as detailed in the user guide - https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_sre_apache_guacamole.html - as the individual steps don't check Powershell requirements. but I would also recommend using a devcontainer with VSCode - happy to help you set that up if you need some advice https://code.visualstudio.com/docs/devcontainers/containers

**Comment by eeelllccc** [comment]
@craddm thanks for pointing that out, I presume I could also just edit the version requirements defined in `CheckRequirements.ps1` if I wanted to get around the checks - I'm not actually blocked on deploying an SRE at the moment because I carried out the deployment by simply changing my powershell version to meet the requirements.
