### ISSUE TITLE
Jupyter Notebook launched from SRD menu cannot start Python kernel 

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1584]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:**  `4.1.0`
- **Browser details:** Chrome 
- **Operating system details:** MacOS 

## :no_entry_sign: Describe the problem

If Jupyter Notebook is launched from the `Applications` menu, it cannot connect to the system Python kernel.

<img width="1309" alt="image" src="https://github.com/alan-turing-institute/data-safe-haven/assets/5796417/0e2a9727-9776-472b-ab7b-ac3a07d2ec20">

Running Julia or R kernels presents no problem.

## :steam_locomotive: Workarounds or solutions

If launched from the terminal (for example, running `jupyter notebook &`), the notebooks can connect to the Python kernel without issues.

**Comment by JimMadge** [comment]
Possibly a compatibility issue between the version of jupyter and the system python3.

I would prefer we move to remove jupyter (and all other PyPI packages) from the SRD image going forward.

**Comment by JimMadge** [comment]
We should quickly look to see if there is any obvious difference between the launcher and terminal Jupyter sessions.
If we can't find a good fix a note in the user docs should be sufficient.

_I.e._ `which jupyter-notebook` and the `.desktop` file for Jupyter.

**Comment by JimMadge** [comment]
We've spent quite a bit of time on this with no joy.

I think important things to consider are,

- We will be moving away from providing packages like Jupyter at a system level in the future
- We have a workaround (launch `jupyter-notebook` from the command line)

So we can either push this to the next release or document the workaround and move on.

From talking to @craddm I believe there was a difference between the programs being launched in the command line and from the `.desktop` file. However, we didn't find a way to get both to work and launch the same program.

@craddm If you could write what you found in this issue that would be helpful.

**Comment by jemrobinson** [comment]
If the `.desktop` file doesn't work, should we just remove it?

**Comment by JimMadge** [comment]
> If the `.desktop` file doesn't work, should we just remove it?

@craddm Is that from system Juptyer (as in `apt install jupyter`)? In that case it should be easy.
I would be surprised if `pip install jupyter` added a desktop entry 🤔.

**Comment by craddm** [comment]
We actually add the `.desktop` file in the `cloud-init` for the VM image

From: Jim Madge ***@***.***>
Date: Thursday, 29 February 2024 at 08:51
To: alan-turing-institute/data-safe-haven ***@***.***>
Cc: Matthew Craddock ***@***.***>, Mention ***@***.***>
Subject: Re: [alan-turing-institute/data-safe-haven] Jupyter Notebook launched from SRD menu cannot start Python kernel (Issue #1584)

If the .desktop file doesn't work, should we just remove it?

@craddm<https://github.com/craddm> Is that from system Juptyer (as in apt install jupyter)? In that case it should be easy.
I would be surprised if pip install jupyter added a desktop entry 🤔.

**Comment by JimMadge** [comment]
@craddm In that case. We could remove that file as part of v4.2.0.

**Comment by JimMadge** [comment]
Closed by #1754

**Comment by Davsarper** [comment]
Should this issue be closed as per @JimMadge 's last comment? what was the final resolution?
