### ISSUE TITLE
Authentication hangs if subscription id is passed rather than subscription name

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1611]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop @ bfbde01

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

If a subscription id is passed to `dsh init`, rather than the subscription name, the initialisation process hangs and eventually times out with an unhelpful error message:

```
2023-09-20 13:27:39 [   ERROR] Could not initialise Data Safe Haven.                                                              cli.py:94
2023-09-20 13:27:39 [   ERROR] Failed to create backend resources.                                                                cli.py:94
2023-09-20 13:27:39 [   ERROR] maximum recursion depth exceeded while calling a Python object  
```

This error actually seems to be something that is down to the Azure SDK, so we either try to stop the user from entering the wrong thing before it gets that far or take their input and turn it into the thing we need.

We could probably support both the ID and the name. At the moment, it seems a bit odd that you have to supply the ID for the admin group and then the name for the subscription, rather than having them both be consistent one way or another. Supplying the name is friendlier in both cases, but I suppose it depends what the Azure API needs.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

**Comment by JimMadge** [comment]
I think it would be better to use one, and only one, or ID or name.

Are subscription names unique per tenant?
Presumably subscription IDs are globally unique, so that seems like a sensible choice.

**Comment by JimMadge** [comment]
- [x] Change `dsh context add` option from `subscription` to `subscription-name` for clarity
- [x] Add check that `subscription-name` is a valid subscription name, not a uuid and raise exception
      Or, catch problem deploying avoiding infinite loop.
