### ISSUE TITLE
Handle dangling lock files

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1636]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

When running, Pulumi creates a lockfile to prevent changes being made concurrently.
If the `dsh` process ends unexpectedly (for example, loss of internet connection, sigkill) the lockfile may remain, blocking any operations until it is removed.
The `pulumi cancel` command can be used to rectify this.

## :steam_locomotive: How could this be done?

- Wrapper for pulumi cancel
- Catching this outcome and prompting the user to take manual intervention

**Comment by jemrobinson** [comment]
The `--force` arguments to `dsh deploy shm` and `dsh deploy sre` will do this. Could be flagged better in the documentation though and/or checked before running?

**Comment by JimMadge** [comment]
> The `--force` arguments to `dsh deploy shm` and `dsh deploy sre` will do this. Could be flagged better in the documentation though and/or checked before running?

:+1:

Could be. I think we also discussed using a `--force` flag to indicate that changes should be made (otherwise prompt user for confirmation). If so that would be repurposed.
