### ISSUE TITLE
DSH should have citation file, DOI ~~and automate adding contributors~~

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1648]
Add the following:
- [ ] DOI from Zenodo
- [x] Citation file - Already exists: https://github.com/alan-turing-institute/data-safe-haven/blob/5ab54596814de11ca4558407332d51efb86f306f/CITATION.cff
- ~~all-contributors bot~~ see #1649

**Comment by edwardchalstrey1** [comment]
@JimMadge @craddm Any thoughts as to whether DSH codebase should have a DOI in addition to citation file? On further reflection it's not clear to me this is needed

From [the Turing Way](https://the-turing-way.netlify.app/communication/citable/citable-cite.html?highlight=digital%20object%20identifier#citing-software):
> Zenodo should... make a snapshot copy of the current state of your repository (just one branch, without any history), and should also assign a persistent identifier (DOI) to that snapshot.

I'm not sure what the best practice for DOIs for software is. Would it make sense to have a DOI for each release?

**Comment by edwardchalstrey1** [comment]
@all-contributors please add @edwardchalstrey1 for code, docs

**Comment by craddm** [comment]
Zenodo will generate a new one for each release, but also gives you a canonical DOI that always takes you to the latest release.

**Comment by edwardchalstrey1** [comment]
Am un-assigning myself from this as per Martin's comment on slack:

> In terms of the Zenodo link, it would probably be better if one of us staying on the project click the link button to create the Zenodo record so we have access for any future updates. I’d suggest myself or Jim. See the [Zenodo developers Guide](https://developers.zenodo.org/#github) for details of the Zenodo JSON metadata file.

**Comment by JimMadge** [comment]
Closed in https://github.com/alan-turing-institute/data-safe-haven/pull/1649
