### ISSUE TITLE
Pulumi: Restructure/break down init

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1651]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Related to #1640 

The `init` subcommand does a number of things,

- Creates Azure infrastructure
  - Storage account
    - Pulumi backend
    - Configuration store
  - Management group
  - Anything else?
- Sets some _local_ configuration
  - Which subscription, management group, shm

This means you use init for a number of logically distinct tasks

- Creating new backend infrastructure
- Switching between SHMs
- Updating configuration

I think this could be clearer by breaking these tasks down and using different sub commands.

There is also a lack of symetry with `dsh init` creating the backend infrastructure and `dsh teardown backend` destroying it, in contract to, for example, `dsh create sre` `dsh teardown sre`.

## :steam_locomotive: How could this be done?

Command structure ideas,

Add `backend`/`context` and `config` commands

- dsh
  - backend/context
    - create/init
    - destroy
    - switch (switch between backends/projects like you currently would with `init`)
    - config (alternatively, this could be a top level subcommand)
  - create
  - teardown

Restructure around backend, SHM, SRE (or, bring backend into `create`/`teardown`)
(We don't need to do all of this at once)

- dsh
  - backend
    - create
    - teardown
    - switch
    - config
  - shm
  - sre

**Comment by craddm** [comment]
I agree generally with breaking it down. Particularly like making an explicit `switch`. Some other thoughts. 

I feel like the backend and SHM are a bit jumbled up. When you create a backend, you're creating a backend for an SHM. You can't have multiple SHMs under one backend, and switching backend means switching SHM. If we wanted to allow different backends (Azure/Pulumi Cloud/S3 etc), that ambiguity gets worse, because switching backend then implies you might be able to change backend independently of changing SHM. But in our model, a backend is a backend for a specific SHM, so you can't switch backend without switching SHM. 

I think I'm wondering why have `backend` separate at all? Say we reorganised it around `shm` and `sre`. Why not have `dsh shm init` or `dsh shm backend` rather than `dsh backend foo`? All of the things you would want to do with the backend actually reflect which SHM you are/want to be interacting with. Why `dsh backend switch` and not `dsh shm switch`? And if you tore down the SHM, why would you want to keep the backend?

Why not have something like

`dsh create backend` 
`dsh create shm`
`dsh create sre`

(Also what does `dsh backend config` do?)

**Comment by JimMadge** [comment]
> When you create a backend, you're creating a backend for an SHM. You can't have multiple SHMs under one backend, and switching backend means switching SHM.

I believe that is true, although I think that is the wrong way of thinking about this. I think you could equally say an SRE belongs to only one SHM, so why not have `dsh shm sre`. However, I don't think that helps the user and it is better to have a context like `dsh <component> <action>` or `dsh <action> <component>`.

I see the backend as a distinct component. It isn't SHM or SRE infrastructure. Instead it is shared configuration, state, secrets needed by the managers.

I can see keeping a backend after destroying and SHM being useful for logging/auditing as it will contain Pulumi history and backup files https://github.com/alan-turing-institute/data-safe-haven/issues/1638.

Also, we need to be careful about distinguishing between a DSH backend and a Pulumi backend, because they are not the same thing. I'm coming to think supporting other Pulumi backends is not the best use of our time now because we need to store other data in an Azure storage account anyway.

The backend feels a bit different to SHM/SRE as I'm expecting we will add more commands than just `create` and `destroy`. See https://github.com/alan-turing-institute/data-safe-haven/issues/1640 where we are looking at adding commands to manage configuration (which is better because admins won't need to share (as many) command line arguments).

**Comment by craddm** [comment]
> I see the backend as a distinct component. It isn't SHM or SRE infrastructure. Instead it is shared configuration, state, secrets needed by the managers.
> 
> I can see keeping a backend after destroying and SHM being useful for logging/auditing as it will contain Pulumi history and backup files #1638.

Fair.
 
> Also, we need to be careful about distinguishing between a DSH backend and a Pulumi backend, because they are not the same thing. I'm coming to think supporting other Pulumi backends is not the best use of our time now because we need to store other data in an Azure storage account anyway.

Definitely makes our life simpler.
 
> The backend feels a bit different to SHM/SRE as I'm expecting we will add more commands than just `create` and `destroy`. See #1640 where we are looking at adding commands to manage configuration (which is better because admins won't need to share (as many) command line arguments).

Yes, I'm definitely pro shifting to config files, as getting the command lines right is cumbersome at best.

**Comment by JimMadge** [comment]
Ok, I think I will have a go at this. Maybe I will do #1640 first.

@craddm Do you have as strong opinion on whether it makes more sense for the interface to be `create/destroy -> shm/sre` or `shm/sre -> create/destroy`?

I would have assumed the later would be easier to structure in the code, but I haven't looked too deeply. There might be advantages to having `<component>` first if each component ends up having bespoke commands.

**Comment by craddm** [comment]
On the one hand, the `<verb> <object>` syntax feels more natural initially, but can see what you mean. What sort of bespoke commands might we have? I can see things like adding a database, adding another VM etc to SREs:

`dsh sre create`
`dsh sre add database`
`dsh sre add vm`
`dsh sre update ssl`

vs

`dsh create sre blah`
`dsh add database sre`
`dsh add vm sre`
`dsh update ssl sre`

Hm, I felt like I would like `<verb> <object>` better, but writing out some examples I actually think I prefer `<object> <verb>`, as it's more immediately obvious what you're operating on.

**Comment by JimMadge** [comment]
I think there is quite a bit of scope for adding commands, if that is what we want to do. It might be more sensible to point to how these things can be achieved in the Azure portal or web interfaces to any tools we deploy. Managing users, shutting down VMs, restarting container instances, that sort of thing.

I definitely wouldn't want to have commands like `add database` though. I feel the way we should handle this is _any_ infrastructure change is achieved by updating the Pulumi program(s) and running `pulumi up`. So adding/removing infrastructure is the same. I think I see that process as `dsh backend config ...` (to adjust, say, the workspaces in an SRE) then `dsh deploy sre`.

**Comment by jemrobinson** [comment]
The original reason for the backend being separate from the SHM is that in the backend code we deploy Azure resources using the Python SDK which then let us use Pulumi to deploy SHM and SRE resources. The backend is the thing that bootstraps the use of Pulumi elsewhere (a resource group, a storage account, a couple of containers, a key vault and a managed identity).

**Comment by JimMadge** [comment]
Closed in #1655
