### ISSUE TITLE
DBeaver driver versions not updating automatically

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1695]
`update_package_versions.yaml` duplicates the line for updating the RStudio version under the DBeaver driver update section, so the drivers never get updated automatically.

**Comment by JimMadge** [comment]
Is this related to #1666?

**Comment by craddm** [comment]
Relates to that yes, but am still having trouble with getting DBeaver to automatically recognise the drivers. I'm hoping to finally fix that today, but this is a distinct enough issue it was worth fixing alone.
