### ISSUE TITLE
Pulumi: Use an Annotated Container Type for validation

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1721]
Because this is quite similar to the database unique list validation, it might be possible to do something like create an Annotated Container Type `UniqueList[T]` and a validator for it.

Do you think that is possible? Let's open an issue if so and not block this.

_Originally posted by @JimMadge in https://github.com/alan-turing-institute/data-safe-haven/pull/1716#discussion_r1467558000_

**Comment by JimMadge** [comment]
It probably isn't worth creating one validator for both here, as validating the SREs dict checks that one item of the values are unique, not that all values are unique.

I'll look at adding a `UniqueList` annotated type though.
