### ISSUE TITLE
Clam AV On-access scanning

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1722]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:**  develop
- **Operating system details:**  macOS

## :cactus: Powershell module versions

Not relevant

## :no_entry_sign: Describe the problem

ClamAV has an on-access scanning service that doesn't seem to be running correctly on a Tier 2 SRD

![image](https://github.com/alan-turing-institute/data-safe-haven/assets/5796417/90b5f679-6e7f-4861-912e-2bf1367e3f85)

## :steam_locomotive: Workarounds or solutions

`clamonacc` is found at `/usr/sbin/clamonacc` rather than `/usr/bin/clamonacc`, so changing the relevant file - `clamav-clamonacc.service` - should hopefully fix it

**Comment by JimMadge** [comment]
`clamav-clamonacc.service` is a file we maintain? (I think I wrote it 😶).

This is one of the reasons I like Arch. `/bin`, `/sbin`, `/usr/sbin` are all just symlinks to `/usr/bin`.

**Comment by craddm** [comment]
It's the only place I can find the filepath for `clamonacc`!

**Comment by JimMadge** [comment]
It makes sense, it is a systemd unit file. When it is enabled it should instruct systemd how to run the ClamAV daemon.

**Comment by JimMadge** [comment]
It is [here](https://github.com/alan-turing-institute/data-safe-haven/blob/fc4dc129c92f028f5bc02585e6b7208f9061349c/deployment/common/resources/clamav-clamonacc.service)

**Comment by JimMadge** [comment]
Should also check the path in [clamav-clamscan.service](https://github.com/alan-turing-institute/data-safe-haven/blob/fc4dc129c92f028f5bc02585e6b7208f9061349c/deployment/common/resources/clamav-clamdscan.service) is correct
