### ISSUE TITLE
Transition to role-based access control (RBAC) in Azure by 31 August 2024

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#1756]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [ ] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Email from Microsoft Azure:

> You're receiving this notice because you use Azure classic administrator roles.
> 
> On 31 August 2024, Azure classic administrator roles will be retired. If your organization has active Co-Administrator or Service Admin roles, you'll need to transition to using Azure RBAC roles by then. (All Azure classic resources and Azure Service Manager will also be [retired](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fazure.microsoft.com%2Fupdates%2Fazure-classic-resource-providers-will-be-retired-on-31-august-2024%2F&data=05%7C02%7Cdsalvadorjasin%40turing.ac.uk%7C0957243fdb2548ac8f2408dc4251a8c0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638458165694844368%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=MxMeN4B50KuttWdbFhfkeLGBXR704hc3nJx5QyfsoaE%3D&reserved=0) on that date.)
> 
> You may continue using these Azure classic admin roles until they're retired. However, starting 3 April 2024, you'll no longer be able to add new Co-Administrator roles through the Azure portal.
> 
> Required action
> 
> To avoid potential disruptions in service, [transition](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fclassicadmins&data=05%7C02%7Cdsalvadorjasin%40turing.ac.uk%7C0957243fdb2548ac8f2408dc4251a8c0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638458165697977205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=iiwE48nZ5asLSko2lZ9h5y8CxZW4xd%2BU3hAiTTJq81M%3D&reserved=0) any classic admin roles that still need access to your subscription to an Azure RBAC role by 31 August 2024, when classic admin roles will no longer be supported.
> 
> Help and support
> 
> If you have questions, ask community experts in [Microsoft Q&A](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fanswers%2Ftags%2F189%2Fazure-rbac&data=05%7C02%7Cdsalvadorjasin%40turing.ac.uk%7C0957243fdb2548ac8f2408dc4251a8c0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638458165697985662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=pcBaj0ZVa4BDxWUobLN4NNpuwnxl6m%2BQWD4nqq909Ak%3D&reserved=0). If you have a support plan and you need technical help, open the [Azure portal](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.azure.com%2F%23blade%2FMicrosoft_Azure_Support%2FHelpAndSupportBlade%2Foverview&data=05%7C02%7Cdsalvadorjasin%40turing.ac.uk%7C0957243fdb2548ac8f2408dc4251a8c0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638458165697993716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HvKbzFgK1f2jRTEzRYxZjD6fnIGPso07fdtKhxAQCyg%3D&reserved=0) and select the question mark icon at the top of the page.
> 
> Learn more about service retirements that may impact your resources in the [Azure Retirement Workbook](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FServicesRetirementWorkbook&data=05%7C02%7Cdsalvadorjasin%40turing.ac.uk%7C0957243fdb2548ac8f2408dc4251a8c0%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638458165698000519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Nac%2FvjCCueNbBtvop4oUS1Mqv3m2B6To255ENIz6cS8%3D&reserved=0). Please note that retirements may not be visible in the workbook for up to two weeks after being announced.
> 

## :steam_locomotive: How could this be done?

The [documentation](https://data-safe-haven.readthedocs.io/en/latest/processes/data_access_controls.html#administrative-access) mentions that access to all Data Safe Haven Azure resources is controlled via Azure Active Directory (Azure AD) and Role-Based Access Control (RBAC). However, the email from Azure mentions that subscriptions that are affected by this transition are:

- [PROD] SAFE HAVEN DOMAINS
- DECEMBER 2023 DATA STUDY GROUP - IGNOTA LABS
- DECEMBER 2023 DATA STUDY GROUP - JOHNSON MATTHEY
- [PROD] SAFE HAVEN MANAGEMENT V4
- [PROD] SAFE HAVEN MANAGEMENT
- [PROD] SAFE HAVEN VM IMAGES
- TURING1 SRE EDON DATA
- DECEMBER 2023 DATA STUDY GROUP - AMBER/UKCEH
- TURING1 SRE LWMCENSUS
- LIVING WITH MACHINES SECURE

**Comment by jemrobinson** [comment]
This is one to check with RCP but I don't think we're using any classic administrator roles on these subscriptions.

**Comment by JimMadge** [comment]
We don't use any classic administrator roles for DSH so this should not affect us.
