### ISSUE TITLE
Smoke tests failing due to issues with Python versions

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1762]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** MacOS
- **Data Safe Haven version:** 4.2.0

## :cactus: Powershell module versions

N/A

## :no_entry_sign: Describe the problem

On the dev environment, I ran the smoke tests successfully on an SRD image deployed on a newly deployed t1 environment. However, running the smoke tests on the same SRD image deployed on a pre-existing T2 environment where an SRD had been deployed from a previous image failed.

The error seemed to be caused by there being multiple patch versions of Python 3.11 present (3.11.7 and 3.11.8). The tests initially run on 3.11.7, but then fail on version '3.11.7 3.11.8'. (I cannot double check this right now as the dev environment is not running). Thus the version numbers are being combined and the tests fail because they're trying to use a non-existent version. Possibly the issue is partly due to there being more versions than expected, as the test files seem to be hardcoded to expect three versions of Python available.

Smoke tests run successfully. 

## :deciduous_tree: Log messages

Unfortunately, since the dev subscription is currently out of action, I can't provide a screenshot of the logs.

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

**Comment by jemrobinson** [comment]
Confirming that running `./Add_Single_SRD.ps1` creates the expected`run_all_tests.bats` file:

```
...
# Python
# ------
# Test Python 3.10
@test "Python packages (3.10)" {
    test_python_packages '3.10'
}
@test "Python functionality (3.10)" {
    test_python_functionality '3.10'
}
@test "Python virtual environments (3.10)" {
    test_python_virtual_environments '3.10'
}
@test "Python package repository (3.10)" {
    test_python_repository '3.10'
}

...
```

... but I think the failure comes in these utility functions which aim to get the correct Python version:

```
get_full_python_version() {
    pyenv versions --bare --skip-aliases | grep -v "/" | grep "${1}." | xargs
}

setup_python() {
    eval "$(pyenv init - --no-rehash)"
    pyenv shell "$(get_full_python_version $1)"
    run python --version
    assert_output --partial "${1}."
}

test_python_functionality() {
    setup_python "$1"
    run python tests/test_functionality_python.py 2>&1
    assert_output --partial 'All functionality tests passed'
    pyenv shell --unset
}
```

I've added a fix in 1e68bcd7

**Comment by JimMadge** [comment]
So is the problem if there are two patch versions of the same minor version installed?

`get_full_python_version` would give both patch versions.

**Comment by JimMadge** [comment]
Works locally :+1:

```console
❯ pyenv versions --bare --skip-aliases | grep -v "/" | grep "3.12." | xargs
3.12.1 3.12.2
❯ pyenv versions --bare --skip-aliases | grep -v "/" | grep "3.12." | tail -n 1 | xargs
3.12.2
```

(Assuming `$1` is `major.minor`)

**Comment by craddm** [comment]
Confirmed that this works remotely too.

**Comment by jemrobinson** [comment]
The only question here is whether we can rely on `pyenv versions` to sort the versions for us, or whether we should add a `sort` to the pipeline. I think it's probably OK to rely on `pyenv` for the moment.
