### ISSUE TITLE
Remove process details from Documentation

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1764]
## :ledger: Where is the problem?

The documentation has a top level "Processes" section.
That might give the wrong impressions, that the DSH codebase sets out specific processes to follow.

Within that section are pages that are about Turing-specific processes, which are not essential to using DSH in production,

- Classification process
- Data transfer at the Turing
- ...

## :memo: Required documentation changes

- [x] Rename section (perhaps something more like operation, management)
- [ ] Check pages for Turing-specific things (rather than DSH specific things or general advice)
- [ ] Remove non-DSH things and rewrite
- [ ] Ensure Turing-specific things are captured in other documentation (TRESA)

**Comment by JimMadge** [comment]
Untangling the Turing specifics is a little complicated.

My new proposal is,

- Remove the processes section entirely
- Relocate useful, appropriate information (_e.g._ data ingress advice to DPR role section)
- Change classification language (_etc._) to be more generic
  - "You should ensure the data can be released" instead of "You must complete _the_ data classification process before release"
- Add section in overview, alongside tiers, explaining that
  - The code is not enough, you need people, processes
  - Tiers are parts of the controls, you should think about how you will use them
  - Ultimately, all data going in and out should be assessed and an agreement reached
  - There are restrictions for users but we cannot be entirely safe against bad actors
  - We have documented what we do at the Turing in TRESA docs

**Comment by jemrobinson** [comment]
If anything that you're removing looks like it would be useful in the TRESA docs, can you make a PR to add it there?

**Comment by JimMadge** [comment]
> If anything that you're removing looks like it would be useful in the TRESA docs, can you make a PR to add it there?

Yes. What I might do is wait for this to be closed, then open an issue collecting everything that has been removed. I expect I might not be able to make a PR before going on leave.
