### ISSUE TITLE
Reduce coupling between SHM and SRE configs

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1777]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Reduce coupling between SHM and SRE configs

## :steam_locomotive: How could this be done?

- Separating SHM and SRE configs into different files
  - Note that we still want both to be serialised to/from AzureStorage as is done currently
- Find a sensible way to set the SRE index in a way that ensures each SRE will still deploy to a non-overlapping IP range
  - This could be done e.g. by checking the index against existing known indices at upload time
  - See #1902

**Comment by JimMadge** [comment]
This should improve the user experience.

You can create an SHM config and deploy an SHM without worrying about (or seeing) SRE config.
It should be neater and less intimidating for users.

**Comment by JimMadge** [comment]
Might not be needed if we close #1900
