### ISSUE TITLE
Add ClamAV to the workspaces

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1783]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

The workspace VMs currently have no antivirus, we should fix this.

## :steam_locomotive: How could this be done?

Install ClamAV and add appropriate NSG/firewall rules to allow it to work as intended.

**Comment by JimMadge** [comment]
Related to #1574
