### ISSUE TITLE
Implement Pulumi tests

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1835]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

With our infrastructure deployed by Pulumi, we should be able to write some infrastructure tests.

## :steam_locomotive: How could this be done?

Look at the Pulumi testing docs: https://www.pulumi.com/docs/using-pulumi/testing/

Note [this issue](https://github.com/pulumi/examples/issues/1007) which implies it won't be trivial to add unit tests to an inline program.

**Comment by JimMadge** [comment]
The property and integration tests deploy real infrastructure.

Unit tests look quite simple to implement though, there is a [guide](https://www.pulumi.com/docs/using-pulumi/testing/unit/).
It more or less involved mocking the Pulumi SDKs deploy function.

So, we wouldn't be able to check that the Pulumi calls will definitely work, but you can check that, for example, `dsh deploy shm` would deploy a set of Pulumi objects with certain arguments.

That is very similar to what I've done with mocking some Azure SDK functions.

**Comment by JimMadge** [comment]
From a conversation with @jemrobinson,

The property tests can check a series of assertions against deployed infrastructure. Probably too costly to put in CI. However, that could be a really interesting test we could run before releases, and to provide as a `dsh validate` command to help ensure a deployed TRE is behaving as expected.
