### ISSUE TITLE
Structure of commands

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1836]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We should agree on the structure of our user-facing command "API".

Current workflow looks something like:

```
dsh context add # makes the local context
dsh context create # deploys Azure resources
dsh config template > config.yaml # creates a local YAML file
dsh config upload config.yaml # upload the local config to Azure
dsh deploy shm # deploy an SHM
... some time passes ...
dsh config show > config.yaml # download the config file locally and edit it
dsh config upload config.yaml # upload the new config with e.g. an SRE called "sandbox" added
dsh deploy sre sandbox # deploy an SRE
```

I think this could be simplified and also made less (potentially) error-prone by preventing users from clobbering existing config files unless this is done deliberately.

## :steam_locomotive: How could this be done?

Have a discussion about what commands (and options) should be exposed.

**Comment by jemrobinson** [comment]
Some discussion on #1820:

> Perhaps we could replace `dsh config upload config.yaml` with something like `dsh deploy shm --config config.yaml` which would prompt for "are you sure?" if there's a remote config that differs from `config.yaml`.

> I think that sounds sensible. It would be easy (and probably useful) to keep the `$ dsh config upload ...` command. Both functions should just need to call a couple of `Config` methods.

> I'm happy to have more powerful advanced commands (or options to commands) but I'd like to keep the minimal required commands simple and easy to understand. If possible, they would just be: `dsh initialise; dsh deploy` but I realise we're not there at the moment!

> I think this is a philosophical argument.
>
> I would say that isn't simple or easy to understand. Having so few commands means they must be complex and handle a lot of processes without input from the user.
>
> I would say something more like a tree (`dsh shm {deploy, destroy}`, `dsh sre {deploy, destroy}` is simple and easy to understand because the commands are clear, limited and descriptive.

**Comment by JimMadge** [comment]
Somewhat related to discussion in https://github.com/alan-turing-institute/data-safe-haven/issues/1651 about order of commands.

Might be worth rolling that into this issue (because although that is closed the command order didn't change).

**Comment by JimMadge** [comment]
From #1848, it would be good to have a consistent file structure for the commands.

Could be
```
commands
├── __init__.py (exports all command groups)
├── sre
│   ├── __init__.py (exports only the command group)
│   ├── command_group.py
│   ├── deploy.py
│   └── teardown.py
├── shm
│   ├── __init__.py
│   ├── deploy.py
│   └── teardown.py
├── context
│   └── ...
├── admin
│   ├── add_users.py
│   └── ...
└── config
    └── ...
```
