### ISSUE TITLE
Python virtual environment smoke tests on SRD

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#1841]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 4.2.0
- **Operating system details:** macOS

## :no_entry_sign: Describe the problem

This is an issue encountered when running smoke tests in the SRD. When `bats run_all_tests.bats` is run, the Python virtual environment tests pass, but when this test is run individually (by running `test_virtual_environments_python.sh`), the first check seems to fail:

 
<img width="704" alt="Screenshot 2024-04-26 at 17 06 29" src="https://github.com/alan-turing-institute/data-safe-haven/assets/57944311/5fe07b6c-7970-4520-a273-a8efa222c8b6">

**Comment by jemrobinson** [comment]
This test runs `which pyenv`. What happens when you run that on its own? What's the return value (run `echo $?` straight afterwards).

**Comment by jemrobinson** [comment]
@dsj976 : Is this still a problem?

**Comment by dsj976** [comment]
This is not a problem any longer

![Screenshot 2024-07-16 at 11 19 21](https://github.com/user-attachments/assets/bcff262e-9ae0-4ff5-9215-b2048a25e839)

**Comment by JimMadge** [comment]
Unable to reproduce.
