### ISSUE TITLE
Identity container group does not start during SRE deployment

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1864]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop

## :no_entry_sign: Describe the problem

When deploying an SRE, the container groups for the identity services fail to deploy. Instead, they get stuck on a `Waiting` status and then fail. 

The only error message relates to a failure to mount an Azure File Volume. The container group has the IP address 0.0.0.0 allocated to it, which is also incorrect.

## :deciduous_tree: Log messages

```json
"instanceView": {
    "events": [
        {
            "count": 1 "firstTimestamp": "2024-05-03T13:59:37.214Z",
            "lastTimestamp": "2024-05-03T13:59:37.214Z",
            "message": "Failed to mount Azure File Volume.",
            "name": "FailedMountAzureFileVolume",
            "type": "Warning"
        }
    ]
}
```

## :recycle: To reproduce

Deploy an SRE using pulumi

**Comment by JimMadge** [comment]
Is this related to #1849 or are you working around that?

**Comment by jemrobinson** [comment]
Unrelated. Workaround for #1849 was to manually add the encryption key to the config file.
