### ISSUE TITLE
Stdout, stderr and log usage

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1891]
From [PR discussion](https://github.com/alan-turing-institute/data-safe-haven/pull/1881#discussion_r1600036932).

We should decide how and when to use stdout and logging.
Logging may (or may not) be directed to stdout by default, but could also be direct to file.

Historically logging has been used heavily and printing avoided.

> In general, I think the only time we should be writing directly to stdout is if we're in a command that is intended to be used as part of a pipe/redirect.

> I think that is incorrect and goes against convention.
> 
> I think of stdout as information for the user. Logs are for posterity, for the user/admin.
`pacman -Syu` for example uses stdout to show the user package being downloaded and installed, and hooks being run. You wouldn't pipe that to anything else. Logs of transactions are also written to logs in `/var/logs/pacman.log`.
> 
> Or, a more common/mundane example, you would rarely pipe `<command> --help` to another command, but it would be very odd to not send that to stdout.

My suggestion would be,

- Information the user should know goes to stdout.
  - What the program is doing (at a high level)
  - Prompts for user input
  - Output of CLI commands
- stderr
  - Specifically for error messages (for convention and to help split from stdout)
- Information useful for auditing and debugging goes to logs.
  - What the program is doing at different levels (INFO to DEBUG)
  - Record of decisions
- Some things will go to both logs and stdout/stderr, although output for the user doesn't need to be in log format.
  - What the program is doing at a high level
  - Warnings
  - Errors

**Comment by jemrobinson** [comment]
I see a distinction between the use of a logging library and whether output goes to `stdout/stderr`.

The HHGTP has a [brief section](https://docs.python-guide.org/writing/logging/) discussing why using a logging library is better than `print`.

> The only time that print is a better option than logging is when the goal is to display a help statement for a command line application.

So I strongly think that we should keep using a logging library even for things that should be written to `stdout/stderr`. I agree that we should take a look at:

- why `pytest` doesn't seem to be able to see our log messages
- which things belong at which log level
- what the format of things we write to `stdout` (e.g. for user interaction) should be
- what's the right defaults are to ensure that appropriate things are being written to `stdout`

**Comment by JimMadge** [comment]
Yes, I think the best solution would be to have one function/class to handle output to multiple streams. With arguments like,

- stream: List of stdout, stderr, logs
- log level: One of info, warning, error, ...

The log string (timestamp, log level, _etc._) could then be added only for the logs, which could be directed to stdout/file/syslog(?),

**Comment by JimMadge** [comment]
> why pytest doesn't seem to be able to see our log messages

Looking at this a bit yesterday. It looks like some, but not all, messages are captured.

I recall thinking before it might be due to the way the entrypoint is all wrapped up in a try block.

**Comment by jemrobinson** [comment]
Possibly related: I've noticed recently that if Pulumi crashes, the overall `dsh` process keeps running and can't be terminated with Ctrl+C.

**Comment by JimMadge** [comment]
On discussion,

- Would be good to refine the output for logs to stdout/file
  - No need for [INFO] _etc._ blocks for users?
- Automatically log (more verbosely) to file
- Check verbosity of information to stdout
  - Use debug level more


A useful question for when `print` is appropriate. What information would you want to give the user, but not need to put in logs.

Could be,

- Information directed specifically at the user
- Information the user has asked for
- Output to be redirected
- Interactive prompts

**Comment by jemrobinson** [comment]
@JimMadge was interested in having the output logs use a machine-readable format. 

Currently `utility > logger.py > LoggingHandlerPlainFile` is the place where we define the handler which does things like e.g. strip colours from the output before passing it to a file - it should be reasonably easy to change the format string here.

N.B. We could also upload the logs to whatever centralised logging/analysis solution we use (e.g. Grafana) if we're interested in traceability.
