### ISSUE TITLE
Remove SRE index

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1902]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

If connections like VNet peering between the SHM and SRE could be removed, there would be no need for the SRE index

## :steam_locomotive: How could this be done?

Check that this is unused everywhere

**Comment by JimMadge** [comment]
Would be a lot easier if we close #1900.
