### ISSUE TITLE
Remove Entra groups and applications during SRE teardown

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1903]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop @ bfbde01

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

When an SRE is torn down, the groups (and applications) in Entra ID are not deleted (see also #1826).

**Comment by JimMadge** [comment]
Possibly related to #1813 #1890
