### ISSUE TITLE
Move log analytics to SRE

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1905]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We do not need a central log analytics workspace so this could be moved to the SRE

**Comment by JimMadge** [comment]
This enables #1900 

Should also consider whether we want to keep/replace log analytics.
