### ISSUE TITLE
Release: 4.2.1

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1914]
## :white_check_mark: Checklist

Refer to the [Deployment](https://data-safe-haven.readthedocs.io/en/latest/deployment) section of our documentation when completing these steps.

- [x] Consult the `data-safe-haven/VERSIONING.md` guide and determine the version number of the new release. Record it in the title of this issue.
- [x] Create a release branch called e.g. `release-v0.0.1`
- [x] Draft a changelog for the release similar to our previous releases, see https://github.com/alan-turing-institute/data-safe-haven/releases

### For major or minor releases

- [ ] Deploy an SHM from this branch and save a transcript of the deployment logs
- [ ] Build an SRE compute image (SRD) and save transcripts of the logs
- Using the new image, deploy a tier 2 and a tier 3 SRE
    - [ ] Save the transcript of your tier 2 SRE deployment
    - [ ] Save the transcript of your tier 3 SRE deployment
- [ ] Complete the [Security evaluation checklist](https://data-safe-haven.readthedocs.io/en/latest/deployment/security_checklist.html) from the deployment documentation
- [ ] Update [SECURITY.md](../../SECURITY.md) and [VERSIONING.md](../../VERSIONING.md)

### For major releases

- [ ] Confirm that a third party has carried out a full penetration test evaluating:
  1. external attack surface
  1. ability to exfiltrate data from the system
  1. ability to transfer data between SREs
  1. ability to escalate privileges on the SRD.

### Update documentation

- [x] Update supported versions in `SECURITY.md`
- [x] Update pen test results in `VERSIONING.md`

## :computer: Release information

- **Version number:** _
- **SHM ID:** _
- **T2 SRE ID:** _
- **T3 SRE ID:** _

**Comment by jemrobinson** [comment]
# Changelog draft:

```
## :warning: Update Requires Manual Intervention :warning:

If you are using a `4.2.0` SHM and want to upgrade to `4.2.1`, please follow the steps below:

1. Delete the `GUACAMOLE-SRE-{sreId}` VM and associated resources from the `RG_SHM_{shmId}_SRE_{sreId}_REMOTE_DESKTOP` resource group
1. Re-run the deployment script `Deploy_SRE.ps1 -shmId {shm} -sreId {sre} -VmSizes {as before}` from `deployment/secure_research_environment/setup`

## Known issues
- As for 4.2.0

## Bug Fixes
- Update Guacamole to 1.5.5 to avoid [this known bug](https://lists.apache.org/thread/0sok6jgddhoxl01yvvlptqf1ptqnp5lc)

**Full Changelog**: https://github.com/alan-turing-institute/data-safe-haven/compare/v4.2.0...v4.2.1
```

**Comment by JimMadge** [comment]
I've put that text in a draft release attached to the release branch.

**Comment by jemrobinson** [comment]
10:22 TRESA: running the deployment script atm
11:32 TRESA: deployment script worked without any issues. Running tests now
