### ISSUE TITLE
Possible issues with configuring VPN for DC access

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#1961]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

The documentation for setting up the VPN for connecting to the DC on the powershell codebase need to be updated [Existing docs](https://data-safe-haven.readthedocs.io/en/latest/deployment/deploy_shm.html#configure-vpn-connection) point to a page that has changed substantially in the last week. Our existing method of connecting to the VPN appears to be no longer described on the Azure documentation: https://learn.microsoft.com/en-us/azure/vpn-gateway/point-to-site-entra-vpn-client-mac

## :memo: Required documentation changes

The documentation will need to be updated to reflect the new process for connecting the VPN described on the MS site, but we also need to test whether the new process works

**Comment by craddm** [comment]
Can confirm that the method we were using to connect to the DC still works, so it's now a question of either finding documentation for the old process or making our own

**Comment by craddm** [comment]
Old docs can be found on the wayback machine - https://web.archive.org/web/20240105230602/https://learn.microsoft.com/en-us/azure/vpn-gateway/point-to-site-vpn-client-cert-windows

**Comment by jemrobinson** [comment]
Closed by #1993
