### ISSUE TITLE
Replace admin_group_id with admin_group_name

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1962]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

If possible, it would be nice to replace the opaque `admin_group_id` parameter with a more human-readable `admin_group_name` parameter.

## :steam_locomotive: How could this be done?

This is likely to involve some AzureCLI/GraphAPI calls.

**Comment by vaishnavi-2901** [comment]
hey, please assign this to me.

**Comment by jemrobinson** [comment]
Thanks @vishu1089 but I think we've already got this one covered. If you're interested in contributing to this project, we have a few issues tagged as `good first issue` which you could take a look at?

**Comment by vaishnavi-2901** [comment]
Sure
