### ISSUE TITLE
How to handle config names/ids

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#1965]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Several of our config files share a pattern where they need a human-readable/writeable name and a YAML/JSON-safe ID. We should standardise how this is done.

### Requirements

- **Human name**
  - Supports a reasonably-size character set (at least numbers, letters, punctuation and whitespace)
  - Can be reasonably long if desired
  - Can be written into YAML/JSON as a value (not necessarily as a key)
  - Use cases:
    - log messages
    - tags on Azure resources

- **Config ID**
  - Safe for use as a YAML/JSON key (restricted character set probably without whitespace or punctuation)
  - Should be short (probably max 8 characters)
  - (Ideally) easily generated from the human name
  - Collisions between names unlikely
  - Use cases:
    - keys in YAML/JSON config files
    - providing unique names for Azure resources

### Conclusion
- Our existing `json_safe` function fails to meet the requirement to avoid collisions
- If we want to stick with generating the ID from the human name we should probably use some kind of compact hash-function (or a truncation of a hash)
- If we want the ID to be user-provided we should explain why

### Outstanding questions
- Which characters should be allowed in human-name?
- What maximum length should human-name have?
- Which hash function should we use?

**Comment by jemrobinson** [comment]
Thoughts @JimMadge @craddm ?

**Comment by jemrobinson** [comment]
Discussion with @JimMadge :

- human-friendly name -> "description"
- config id -> "name"

**Comment by JimMadge** [comment]
Name clashes do feel like a risk. I'm not certain how likely it is, but it feels like we know it is possible and it is easy to avoid, so we should.

The advantage of the users setting a key are,

- we don't have to handle clashes
- we don't have to generate unique or canonical keys
- we don't have to ask the user to enter the full name, a hash/key they didn't create
  or, we don't have to provide an interactive selector which presents the human friendly names

I think "description" and "name" are clearer, had I gone with that initially we might have avoided the question in the first place 😅 .

**Comment by jemrobinson** [comment]
Naming is hard! Shows the difference between the developer/implementation mindset ("this is a key in a lookup table so I will call it 'key'") and the user/functional mindset ("this is the name of a thing so I will call it 'name'").

**Comment by craddm** [comment]
Was never really all that keen on calling it `key` and it turns out that that difference was the reason I was unable to articulate
