### ISSUE TITLE
Show "all" SREs

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1973]
The `dsh config show` command takes a required SRE name.

After you have uploaded the config, you have no local reference for the SREs that have been configured.
Can we add a way to list all SRE configs?

https://github.com/alan-turing-institute/data-safe-haven/blob/458c19c681af12ba87e62fd9fda0f92edaf6e540/data_safe_haven/commands/config.py#L36-L42

**Comment by jemrobinson** [comment]
Related to #1812?

**Comment by JimMadge** [comment]
Closing as duplicate :smile:.
