### ISSUE TITLE
Docker pull hotfix for latest

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#1994]
Same issue as #1984 but for v4.X.Y series.

See conversation [from here](https://github.com/alan-turing-institute/data-safe-haven/pull/1955#issuecomment-2213709499)

**Comment by craddm** [comment]
So we're an expecting a sysadmin to provide a docker account in the config file. SHM or SRE level docker account? Probably makes most sense to do SHM level?.

**Comment by jemrobinson** [comment]
Closed by #2004
