### ISSUE TITLE
Adding new items to the config file

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2006]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

If new items are ever added to the config file, it is not possible to update an existing config with them, since the first step in doing so is to download and validate the existing config, which will always fail.

## :steam_locomotive: How could this be done?

Either default values could be added when downloading an existing config or the validation step could be skipped.

**Comment by JimMadge** [comment]
Hmm, like database migrations.

I don't like the idea of adding default values.
Could we instead,

- Provide a way to `dsh config show` despite validation errors
  Maybe it should run and just raise a warning?
- Add a useful error message like "You configuration is probably out of data, run `dsh config show > config.yaml`, update the configuration and upload `dsh config upload`"

I think we don't want to encourage people to start editing configuration in Azure or using az CLI.

**Comment by jemrobinson** [comment]
> Could we instead,
> 
>     * Provide a way to `dsh config show` despite validation errors
>       Maybe it should run and just raise a warning?

Yes, I think this would make sense

>     * Add a useful error message like "You configuration is probably out of data, run `dsh config show > config.yaml`, update the configuration and upload `dsh config upload`"

This is the bit that doesn't work now. Running `dsh config upload <my local file>` is the part that fails, since we try to download and validate the existing config to show the diff wrt the new one.

> I think we don't want to encourage people to start editing configuration in Azure or using az CLI.

Agreed

**Comment by JimMadge** [comment]
Maybe what we want is a bool argument to the method which downloads the file to skip validation. Most of the time, we probably want to do that, but not on upload.
