### ISSUE TITLE
Decide where volumes should be mounted

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2027]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We're currently mounting several different blob/files volumes in dedicated folders at root level (e.g. `/data`). While some of this might make sense for users, we don't need to expose e.g. configuration or desired state data here and there might be a more intuitive way to expose data (e.g. `/data/input`, `/data/output`) or we could see what the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) recommends.

## :steam_locomotive: How could this be done?

Think about what needs to be exposed to users and what can be hidden. Move the mountpoints accordingly.

**Comment by JimMadge** [comment]
`/mnt/` is probably the most natural FHS directory for this. These are all network shares which are not essential for the VMs to boot.

I'm not _too_ worried about following FHS. As we are designing this for our users, if something like `/data/input`, `/data/output`, `/data/backup`, makes more sense to them than  `/mnt/` I think we should do that.

In a similar way, putting "sysadmin" data (like the desired state configuration) in a place where they might expect it (probably `/mnt/`) would help them and us with debugging.

**Comment by JimMadge** [comment]
We could probably also add skeleton symlinks to the directories researchers will want to use so that they appear in home directories, `~/input`, `~/output` rather than asking people to look around in `/data/` or `/mnt/`.

**Comment by jemrobinson** [comment]
Reading the FHS guidelines I think:

1. Config files (like the desired-state files) should probably go in `/etc` (host-specific configuration)
2. `/mnt` is for temporary mounts which I don't think we have
3. `/srv` might be a sensible place for the data if we don't like `/data`. This would pair well with the symlink idea as users wouldn't need to care where the mount actually lives.

**Comment by JimMadge** [comment]
1. Maybe. I don't think I've ever seen configuration like that being put in `/etc`. It is usually used for application configuration like `/etc/ssh/`. I don't think there is an application here, it is just files for Ansible. `/var/desired_state` could be another option which I think would make sense.
2. It's hard to tell but I feel like temporary might mean not required at boot like `/` and `/boot`. Certainly putting mount points for network drives or storage that isn't part of the Linux filesystem in `/mnt` is very common.
3. I haven't seen `/srv` used that often. The way I read it that is more intended for data you are serving, likely available remotely, like a website.

I think there is an advantage to putting things either where people would naturally expect them (`/mnt` feels like that to me) or where they are easy to find.

**Comment by jemrobinson** [comment]
- `/desired_state` -> `/var/local/ansible`
- `/data` -> `/mnt/input`
- `/output` -> `/mnt/output`
- `/shared` -> `/mnt/shared`
