### ISSUE TITLE
List of available SRE configs

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2037]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

It's easy to lose track of what SRE names are already configured for a given SHM. The local filename can be completely different from the remote filename, and if you're working on an SHM deployed by somebody else you may not know what SRE configs already exist without manually going to the portal and checking the storage container.

## :steam_locomotive: How could this be done?

Add a function that lists remote SRE configs.

**Comment by jemrobinson** [comment]
Is this a duplicate of #1812 or is it different?

**Comment by craddm** [comment]
Oops, misread that one, as I thought that was specifically about finding *live* SREs
