### ISSUE TITLE
Add RStudio

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2041]
In previous versions we included RStudio, a popular R IDE.

Supporting RStudio is a little tricky as there is no deb in the canonical repositories, no PPA, and no snap.
To support this we would need to find way to fetch a deb from the Posit site.

We have coverage for R IDEs/editors (codium, vim, emacs).
However, many R developers have a strong preference RStudio so supporting it would likely help researchers.

**Comment by craddm** [comment]
https://github.com/eddelbuettel/ppa-rstudio
