### ISSUE TITLE
Nvidia utils

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2042]
For work using Nvidia GPU instances workspaces will need the Nvidia drivers and other packages provided by `nvidia-utils`.

There are multiple `nvidia-utils` packages for different driver/CUDA/... versions.
We should aim to install the most appropriate version for the hardware being used.
That might be a little tricky as it would depend on the VM SKU.

We could potentially use the VM size argument to choose which package version and template that in the desired state.
Or, we could have a map in the desired state and provide and argument (or variable or fact) to ansible to select the right version.

**Comment by jemrobinson** [comment]
Does `nvidia-utils` depend on the CPU architecture? I think the types of GPUs on Azure are the same for Intel and AMD CPU SKUs.

**Comment by JimMadge** [comment]
Only in that there will presumably be builds for amd64, ARMv*.

What I mean is, the different Nvidia GPU architectures (Pascal, Volta, Ampere, Hopper) should be used with different driver versions. With the wrong version, they may work sub-optimally or not work at all.

**Comment by jemrobinson** [comment]
@JimMadge : Would adding `nvidia-utils` to the default ansible apt list make sense? This ought to install the correct version for the VM at deployment time, right? And if the SKU is changed we can add a warning note to the docs asking admins to uninstall and reinstall.

**Comment by jemrobinson** [comment]
Looks like this should now be done with `ubuntu-drivers` [see here](https://www.civo.com/docs/compute/gpu-instance-drivers-ubuntu).

**Comment by JimMadge** [comment]
I believe `apt install nvidia-utils` just prompts you to install one of the numbered packages. I think `nvidia-utils` is a virtual package which is provided by the specific packages.

`ubuntu-drivers` looks like a good way to go.
