### ISSUE TITLE
Include Azure Data Studio and sqlcmd

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2043]
These packages are more tricky to install as there is no deb in the canonical repos, or snap.

We might want to consider if these packages are necessary.
The functionality of Azure Data Studio may be covered by DBeaver.

sqlcmd is a CLI tool for interacting with MSSQL databases. Do we want to continue to include both MSSQL and PostreSQL?

**Comment by jemrobinson** [comment]
DBeaver covers all of this.

**Comment by JimMadge** [comment]
I would prefer to close this as will not fix for now in that case.

**Comment by jemrobinson** [comment]
That's fine, but then we need an issue to test DBeaver. It won't have drivers for all these DB flavours out-of-the-box so we'll need to install them.

**Comment by JimMadge** [comment]
DBeaver drivers issue here: https://github.com/alan-turing-institute/data-safe-haven/issues/2134
