### ISSUE TITLE
Users cannot login to workspaces when MFA is required

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2049]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOs
- **Data Safe Haven version:** develop @ 2fd913486

## :package: Packages

<details>
<summary>List of packages</summary>

```none
acme==2.10.0
annotated-types==0.7.0
appdirs==1.4.4
Arpeggio==2.0.2
attrs==23.2.0
azure-common==1.1.28
azure-core==1.30.2
azure-identity==1.17.1
azure-keyvault-certificates==4.8.0
azure-keyvault-keys==4.9.0
azure-keyvault-secrets==4.8.0
azure-mgmt-automation==1.0.0
azure-mgmt-compute==31.0.0
azure-mgmt-containerinstance==10.1.0
azure-mgmt-core==1.4.0
azure-mgmt-dns==8.1.0
azure-mgmt-keyvault==10.3.0
azure-mgmt-msi==7.0.0
azure-mgmt-network==25.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.1.1
azure-mgmt-storage==21.2.1
azure-storage-blob==12.20.0
azure-storage-file-datalake==12.15.0
azure-storage-file-share==12.16.0
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
chevron==0.14.0
click==8.1.7
cryptography==42.0.8
-e git+https://github.com/craddm/data-safe-haven.git@9e0dd10867265b3270568f9be5a26a57b883df23#egg=data_safe_haven
dill==0.3.8
dnspython==2.6.1
fqdn==1.5.1
grpcio==1.60.1
idna==3.7
isodate==0.6.1
josepy==1.14.0
markdown-it-py==3.0.0
mdurl==0.1.2
msal==1.29.0
msal-extensions==1.2.0
msrest==0.7.1
oauthlib==3.2.2
parver==0.5
portalocker==2.10.1
protobuf==4.25.3
psycopg==3.2.1
pulumi==3.124.0
pulumi_azure_native==2.49.1
pulumi_random==4.16.3
pulumi_tls==5.0.4
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
Pygments==2.18.0
PyJWT==2.8.0
pyOpenSSL==24.1.0
pyRFC3339==1.1
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
semver==2.13.0
setuptools==70.3.0
shellingham==1.5.4
simple_acme_dns==3.1.0
six==1.16.0
typer==0.12.3
typing_extensions==4.12.2
urllib3==2.2.2
validators==0.28.3
websocket-client==1.8.0
```

</details>

## :no_entry_sign: Describe the problem

Users cannot login to workspaces within SREs. The error message typically means the password is incorrect, but it is correct. An admin account can login at the serial console. 

`sudo password -S <user.name>` indicates the passwords for the users are locked.

Update:

The problem is with the Require MFA Conditional Access Policy. When trying to login to the Ubuntu desktop, a request is made for MFA authentication (presumably because it's coming from a different IP address than you've already logged in to guacamole from) which never reaches the user.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

![image](https://github.com/user-attachments/assets/5256755b-0900-4de3-bea2-5250781671c4)

</details>

## :recycle: To reproduce

Deploy an SRE attached to an Entra ID with the Require MFA Conditional Access policy set up and attempt to login to the workspace.

**Comment by JimMadge** [comment]
> sudo password -S <user.name> indicates the passwords for the users are locked.

Do you mean `passwd -S`?
what was the output?
I think that is expected though, as the users are provided by LDAP and not the local passwd/shadow database.

To find what the problem is, I think we need to look at and confirm,

- Entra ID
- LDAP connection (`ldapsearch` may be helpful)

**Comment by craddm** [comment]
Yes, `passwd -S`, response is `<username> L`

- Entra ID 
The users are there, exist, and are added to the Users group for the relevant SRE. Looking in the logs for the various id containers confirms they're being picked up by those containers.

- LDAP connection
`ldapsearch` returns 

```none
ldap_sasl_interactive_bind: Can't contact LDAP server (-1)
```

That said, the ldap server is contactable - I can `telnet` into it. It obviously doesn't respond to anything I type, as it doesn't really do telnet, but the server can be connected to on the correct port.

**Comment by JimMadge** [comment]
I haven't been able to reproduce this deploying from 57225bc8cf41cf277fed52fb411cccf35d8f00d8 (which shouldn't have changed anything with respect to LDAP).

**Comment by JimMadge** [comment]
Just checking, did you run `ldapsearch` without any arguments or put in the hostname and port?

I think we are using a non-standard port so it might be important to specify that.

**Comment by JimMadge** [comment]
@craddm did you use `dsh` to create the user?
Is it a new user? I remember we had problems with expired accounts/passwords before.

**Comment by craddm** [comment]
> Just checking, did you run ldapsearch without any arguments or put in the hostname and port?

Yes, but not sure how to format the search. I was also messing it up a bit, so now I get other errors instead. So clearly comms with the ldap server is intact.

>@craddm did you use dsh to create the user?
Is it a new user? I remember we had problems with expired accounts/passwords before.

One was created with dsh, and one was created using the portal, IIRC. however, neither are new - both created a few months ago, one in March, one in May. 

I'll note that I have always had this problem, and created one with the `dsh` commands before and still had the same problem. I'll try again now though.

Edit: ok, same problem with a brand new user created using `dsh` commands

**Comment by jemrobinson** [comment]
Try the following:

**Anonymous bind**
`ldapsearch -x -H ldap://<url of LDAP server>:1389 -b "OU=users,DC=<whatever>,DC=develop,DC=turingsafehaven,DC=ac,DC=uk"`

this should list all users available in the LDAP OU "users". If you get nothing here it's either a problem with the LDAP server or with the network connection to it. Check the logs in the `apricot` server.

**Login attempt**
`ldapsearch -x -H ldap://<url of LDAP server>:1389 -b "OU=users,DC=<whatever>,DC=develop,DC=turingsafehaven,DC=ac,DC=uk" -D "CN=<ID of user you know the password for>,OU=users,DC=green,DC=develop,DC=turingsafehaven,DC=ac,DC=uk" -W`

This should prompt you for a password for that user. If this doesn't work, possibly the password is wrong. Again, check the `apricot` server logs.

**Comment by craddm** [comment]
Here's what I'm getting from the `apricot` logs:

```none
2024-07-25 09:22:50+0000 [ReadOnlyLDAPServer,1465,10.0.2.4] Authentication failed.
	(invalid_grant) AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. Trace ID: 014e123e-0c1c-47f2-b491-94e4c5ea9200 Correlation ID: a4744c82-83ef-460e-bdf2-d460a3277237 Timestamp: 2024-07-25 09:22:50Z
2024-07-25 09:22:50+0000 [ReadOnlyLDAPServer,1465,10.0.2.4] S->C LDAPMessage(id=1, value=LDAPBindResponse(resultCode=49, errorMessage="Invalid password for user 'matt.craddock@blue.develop.turingsafehaven.ac.uk'."), controls=None)
```

```none
2024-07-25 09:24:32+0000 [ReadOnlyLDAPServer,1466,10.0.2.4] Authentication failed.
	(invalid_grant) AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. Trace ID: 67cacefd-2803-4bf1-8a44-30c35e900f00 Correlation ID: 3ee6dbdd-4610-4289-bd2f-9f3c0333e43a Timestamp: 2024-07-25 09:24:32Z
2024-07-25 09:24:32+0000 [ReadOnlyLDAPServer,1466,10.0.2.4] S->C LDAPMessage(id=1, value=LDAPBindResponse(resultCode=49, errorMessage="Invalid password for user 'funky.monkey@blue.develop.turingsafehaven.ac.uk'."), controls=None)
2024-07-25 09:24:32+0000 [ReadOnlyLDAPServer,1466,10.0.2.4] S<-C LDAPMessage(id=2, value=LDAPUnbindRequest(), controls=None)
2024-07-25 09:24:32+0000 [ReadOnlyLDAPServer,1466,10.0.2.4] Handling an LDAP unbind request.
```

```none
2024-07-25 09:28:53+0000 [ReadOnlyLDAPServer,1475,10.0.2.4] Authentication failed.
	(invalid_grant) AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'. Trace ID: f1f9a53d-838a-4695-a7b3-0e9b91fba000 Correlation ID: 51ff5e10-f1cc-42e7-acb4-4855feb5bfd7 Timestamp: 2024-07-25 09:28:53Z
2024-07-25 09:28:53+0000 [ReadOnlyLDAPServer,1475,10.0.2.4] S->C LDAPMessage(id=1, value=LDAPBindResponse(resultCode=49, errorMessage="Invalid password for user 'fay.kname@blue.develop.turingsafehaven.ac.uk'."), controls=None)
2024-07-25 09:28:53+0000 [ReadOnlyLDAPServer,1475,10.0.2.4] S<-C LDAPMessage(id=2, value=LDAPUnbindRequest(), controls=None)
2024-07-25 09:28:53+0000 [ReadOnlyLDAPServer,1475,10.0.2.4] Handling an LDAP unbind request.
```

The password is correct for all users, so it must be something to do with the MFA access (which is set up for all accounts). Possibly some legacy setting in the way the `blue` tenant is set up?

**Comment by jemrobinson** [comment]
Oh, I think you're using the same Entra directory that I'm using to test #2039. I've probably deleted a rule that allows the application to authenticate without MFA. Let me look into how to fix this.

**Comment by craddm** [comment]
Possible solutions:
1) Set up the conditional access policy to only apply to specific apps (e.g. guacamole) and not be otherwise applied. This requires MFA for login to guacamole but not for login to the desktop
![image](https://github.com/user-attachments/assets/69140985-b613-4ec1-a12d-3a558afd5264)
Tested, and works
2) Apply custom security attributes to the application to allow it to be excluded from the list of included apps. `apricot` cannot be excluded directly using the menus above, since it is not a web app. Will test this this afternoon.

**Comment by craddm** [comment]
Solution 2 turned out to be rather counterintuitive to the extent that it feels buggy - the filter condition seems to produce the opposite result for web apps and non-web apps, even where the attribute being used is the same for both apps. 

Instead, we found that the `Operating System` field is blank for the request made by `apricot`, and that by filtering by OS, we could keep MFA for `guacamole` but skip it for `apricot`

![image](https://github.com/user-attachments/assets/525c06bf-fd12-4cab-bf26-47ec53ec8615)

The process will be documented in #2039
