### ISSUE TITLE
/etc/skel files not being applied

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2051]
<img width="924" alt="Screenshot 2024-07-24 at 14 43 52" src="https://github.com/user-attachments/assets/f65d242a-83fa-489a-9887-d09caff302ca">

At least for LDAP users, files in `/etc/skel/` don't appear to be written to the home directory.
Possibly a problem with `pam_mkhomedir.so`. Possibly a problem with the files in `/etc/skel`

**Comment by JimMadge** [comment]
The files are written using `useradd` so this is likely a LDAP problem.

**Comment by jemrobinson** [comment]
Can you explain further? Do we have e.g. `pam_mkhomedir.so skel=/etc/skel ...` in our auth file?

**Comment by JimMadge** [comment]
All I know now is that when you create a local user the skeleton files are copied but not when an LDAP user's home directory is created.

This writes the PAM directive, which looks correct to me.

https://github.com/alan-turing-institute/data-safe-haven/blob/996f54f1fdd039fc2372a428fdee911e25baeb11/data_safe_haven/resources/workspace/ansible/desired_state.yaml#L64-L72

It is possible that isn't working as we want though.

**Comment by jemrobinson** [comment]
Looks like the `skel=/etc/skel umask=0022` command isn't being applied

```
> cat /usr/share/pam-configs/mkhomedir
Name: Create home directory on login
Default: no
Priority: 0
Session-Type: Additional
Session-Interactive-Only: yes
Session:
        optional                        pam_mkhomedir.so
```

**Comment by JimMadge** [comment]
I don't think we want to modify that file, it is owned by a package and will be overwritten on upgrade.

**Comment by JimMadge** [comment]
I think the `pamd` module should write to the configuration file `/etc/pam.d/common-session`

**Comment by jemrobinson** [comment]
No, but I think the `community.general.pamd` call should trigger a change to this file which doesn't seem to have happened.

**Comment by jemrobinson** [comment]
> /etc/pam.d/common-session

It doesn't seem to be here either:

```
$ cat /etc/pam.d/common-session
#
# /etc/pam.d/common-session - session-related modules common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of modules that define tasks to be performed
# at the start and end of interactive sessions.
#
# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

# here are the per-package modules (the "Primary" block)
session [default=1]                     pam_permit.so
# here's the fallback if no module succeeds
session requisite                       pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
session required                        pam_permit.so
# The pam_umask module will set the umask according to the system default in
# /etc/login.defs and user settings, solving the problem of different
# umask settings with different shells, display managers, remote sessions etc.
# See "man pam_umask".
session optional                        pam_umask.so
# and here are more per-package modules (the "Additional" block)
session required        pam_unix.so 
session [success=ok default=ignore]     pam_ldap.so minimum_uid=1000
session optional        pam_systemd.so 
# end of pam-auth-update config
```

**Comment by JimMadge** [comment]
Interesting, maybe because the module mode is `args_present` but the module isn't there at all.

**Comment by JimMadge** [comment]
I'll open a PR to test
