### ISSUE TITLE
Multiple SHMs sharing an Entra directory

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2053]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop @ a21263d

## :package: Packages

<details>
<summary>List of packages</summary>

```none
acme==2.10.0
annotated-types==0.7.0
appdirs==1.4.4
Arpeggio==2.0.2
attrs==23.2.0
azure-common==1.1.28
azure-core==1.30.2
azure-identity==1.16.1
azure-keyvault-certificates==4.8.0
azure-keyvault-keys==4.9.0
azure-keyvault-secrets==4.8.0
azure-mgmt-automation==1.0.0
azure-mgmt-compute==30.6.0
azure-mgmt-containerinstance==10.1.0
azure-mgmt-core==1.4.0
azure-mgmt-dns==8.1.0
azure-mgmt-keyvault==10.3.0
azure-mgmt-msi==7.0.0
azure-mgmt-network==25.4.0
azure-mgmt-rdbms==10.1.0
azure-mgmt-resource==23.1.1
azure-mgmt-storage==21.2.0
azure-storage-blob==12.20.0
azure-storage-file-datalake==12.15.0
azure-storage-file-share==12.16.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
chevron==0.14.0
click==8.1.7
cryptography==42.0.8
-e git+ssh://git@github.com/jemrobinson/data-safe-haven.git@a21263dc7be1fb3bf889d85ca5025ffb1fba3128#egg=data_safe_haven
dill==0.3.8
dnspython==2.6.1
fqdn==1.5.1
grpcio==1.60.1
idna==3.7
isodate==0.6.1
josepy==1.14.0
markdown-it-py==3.0.0
mdurl==0.1.2
msal==1.29.0
msal-extensions==1.2.0
msrest==0.7.1
oauthlib==3.2.2
parver==0.5
portalocker==2.10.0
protobuf==4.25.3
psycopg==3.1.19
pulumi==3.121.0
pulumi_azure_native==2.50.1
pulumi_random==4.16.2
pulumi_tls==5.0.4
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
Pygments==2.18.0
PyJWT==2.8.0
pyOpenSSL==24.1.0
pyRFC3339==1.1
pytz==2023.4
PyYAML==6.0.1
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
semver==2.13.0
setuptools==70.2.0
shellingham==1.5.4
simple_acme_dns==3.1.0
six==1.16.0
typer==0.12.3
typing_extensions==4.12.2
urllib3==2.2.2
validators==0.28.3
websocket-client==1.8.0
```

</details>

## :no_entry_sign: Describe the problem

Whenever we create new Entra users from our command line, they are assigned to the default Entra domain. They should instead be assigned to the domain appropriate to this SHM.

## :steam_locomotive: Workarounds or solutions

Needs an update to EntraUsers

**Comment by JimMadge** [comment]
Discussion from slack:

> @jimmadge: Is this equivalent to asking "Do we want users to be restricted to a single SRE, so that if one person need access to multiple SREs they will have multiple accounts?"
> @jemrobinson: No - it's equivalent to saying "Do we want to be certain that a user account created in one SHM can't be added to an SRE in a different SHM", which feels like a sensible restriction to me.
> @JimMadge: :100:
