### ISSUE TITLE
Incorrect dependencies for secure_transport_configuration

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2056]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop @ 996f54f

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

SRE does not deploy due to incorrect dependencies for database `secure_transport_configuration`

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
  azure-native:dbforpostgresql:Configuration (sre_gitea_server_db_gitea_secure_transport_configuration):
    error: Code="ResourceNotFound" Message="The Resource 'Microsoft.DBforPostgreSQL/flexibleServers/shm-pink-sre-coral-db-server-gitea' under resource group 'shm-pink-sre-coral-rg' was not found. For more details please go to
https://aka.ms/ARMResourceNotFoundFix"
```

</details>

## :recycle: To reproduce

Attempt to deploy a fresh SRE

**Comment by JimMadge** [comment]
I'm not sure what this means. Does the Pulumi process not see the DB server as a prerequisite for deploying the DB Configuration?

Does it need a [`depends_on`](https://www.pulumi.com/docs/concepts/options/dependson/)?

**Comment by jemrobinson** [comment]
These lines have no explicit dependence on `db_server`

https://github.com/alan-turing-institute/data-safe-haven/blob/360a3a885d10da1865c901fb22c100d1cb4785b9/data_safe_haven/infrastructure/components/composite/postgresql_database.py#L79-L87

I suggest adding this in two places:
- `server_name=db_server.name`
- add `opts=ResourceOptions.merge(child_opts, ResourceOptions(parent=db_server)),`

**Comment by jemrobinson** [comment]
NB. these also can't be deleted:

```
@ destroying.....
 -  azure-native:dbforpostgresql:Configuration sre_remote_desktop_db_guacamole_secure_transport_configuration deleting (456s) error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID:
'19e12c92-9278-436f-8383-ab8a277d5505'"
 -  azure-native:dbforpostgresql:Configuration sre_remote_desktop_db_guacamole_secure_transport_configuration **deleting failed** error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID:
'19e12c92-9278-436f-8383-ab8a277d5505'"
@ destroying.....
    pulumi:pulumi:Stack data-safe-haven-shm-pink-sre-coral  error: update failed
    pulumi:pulumi:Stack data-safe-haven-shm-pink-sre-coral **failed** 1 error
Diagnostics:
  azure-native:dbforpostgresql:Configuration (sre_hedgedoc_server_db_hedgedoc_secure_transport_configuration):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '97c5c6a7-d367-42a8-91de-f6436c044c6f'"

  azure-native:dbforpostgresql:Configuration (sre_postgresql_database_server_db_postgresql_secure_transport_configuration):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'f3683997-b216-49ef-8e9a-c71eb8500f27'"

  azure-native:dbforpostgresql:Configuration (sre_remote_desktop_db_guacamole_secure_transport_configuration):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '19e12c92-9278-436f-8383-ab8a277d5505'"

  azure-native:dbforpostgresql:Configuration (sre_gitea_server_db_gitea_secure_transport_configuration):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '5edc1fa0-7824-40d9-a93b-3c97f52bf6a7'"

  pulumi:pulumi:Stack (data-safe-haven-shm-pink-sre-coral):
    error: update failed
```

**Comment by jemrobinson** [comment]
Also - do we want to disable secure transport for **all** our postgres DBs? Have we checked whether other DBs that were previously working are still working (e.g. guacamole user db etc.)?

**Comment by JimMadge** [comment]
I haven't been able to reproduce the failure to delete.
I'll see if I can.
