### ISSUE TITLE
"Could not load SHMConfig configuration" error during deployment

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#2063]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [ ] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:**  Mac OS
- **Data Safe Haven version:**  `tresa-testing` branch

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

This error occurs when trying to deploy a TRE with the DSH Pulumi version.

The command `dsh sre deploy sandbox_sre` results in the error:

```
Could not load SHMConfig configuration.                                                                             
Could not load file 'shm.yaml' from Azure storage.                                                                  
Could not deploy Secure Research Environment 'sandbox_sre'.
```

Have verified that the `shm.yaml` file exists and is correctly populated in the `config` container.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

**Comment by jemrobinson** [comment]
This is triggered by using a "friendly" Azure location instead of the canonical name (e.g. "UK South" instead of "uksouth").
