### ISSUE TITLE
Azure-native error when deploying SRE with DSH Pulumi

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#2066]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [ ] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:**  branch `tresa-testing`

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

I get the following error when running `dsh sre deploy sandbox_sre`:

```
Diagnostics:                                                                                                                        
  azure-native:operationalinsights:Workspace (sre_monitoring_log_analytics):                                                        
    error: azure-native:operationalinsights:Workspace resource 'sre_monitoring_log_analytics' has a problem: 'workspaceName' does   
not match expression '^[A-Za-z0-9][A-Za-z0-9-]+[A-Za-z0-9]$' 
```

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

**Comment by jemrobinson** [comment]
This is caused by the use of underscores in the SRE name which need to be converted to `-` before they can be used as Azure resource names.
