### ISSUE TITLE
Symlink VSCodium to code

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2070]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** `develop @ 653ab48`
- **Browser details:** Firefox

## :no_entry_sign: Describe the problem

Running `which code` at the command line produces no output. This might be unexpected for people who want to use VSCode. 

## :steam_locomotive: Workarounds or solutions

We should consider symlinking `codium` to `code`.

**Comment by JimMadge** [comment]
Are we expecting people to launch a GUI application from the command line?

**Comment by jemrobinson** [comment]
I wasn't, but it came up in TRESA testing. Seems like a small fix, but also non-essential.
