### ISSUE TITLE
`dbforpostgresql.Configuration` can't be deleted

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2072]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** 

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

Attempts to delete `dbforpostgresql:Configuration` resources fail. See [this issue](https://github.com/pulumi/pulumi-azure-native/issues/3476) on the `pulumi-azure-native` repo.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Diagnostics:
  azure-native:dbforpostgresql:Configuration (sre_remote_desktop_db_guacamole_secure_transport_configuration):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'd746ae35-9ba2-4495-ad04-27e41998ac30'"```

</details>

## :recycle: To reproduce

<!--
How can the current behaviour be reproduced? Include some steps to reproduce the problem.

Example:
- Deploy an SRE with option X set to Y
- Attempt to perform action Z
- Observe the previously mentioned failure/error message
-->
Deploy an SRE with a `dbforpostgresql:Configuration` then remove it and attempt to update.

**Comment by JimMadge** [comment]
I think this should have been fixed by #2059 

https://github.com/alan-turing-institute/data-safe-haven/blob/63539c4bbcb3d3fff960dc64a3e6f787fda7ae38/data_safe_haven/infrastructure/components/composite/postgresql_database.py#L93-L96

**Comment by jemrobinson** [comment]
Cool - I'll take a look on latest develop. This ResourceOption is new to me!

**Comment by jemrobinson** [comment]
This seems to be working now.
