### ISSUE TITLE
Cloud-init variables

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2075]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We currently expand our cloud-init file with a local of instance-specific variables. It would be better to pass these to Ansible for expansion in templates.

## :steam_locomotive: How could this be done?

Not sure on the best way to pass variables to the Ansible playbook. @JimMadge might have thoughts.

**Comment by JimMadge** [comment]
Ansible [docs on using variables](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html).

The best option for us is probably to write the variables as YAML or JSON and upload that to the desired state blob as something like `vars/pulumi_vars.yaml`.

In the playbook we can then do

```yaml
- hosts: all
  vars_files:
    - vars/pulumi_vars.yaml
```
