### ISSUE TITLE
Suggest users install with pip install of using hatch

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2084]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Using `hatch` is overly complicated for end users. We should suggest they install with pip instead.

## :memo: Required documentation changes

Update hatch references

**Comment by JimMadge** [comment]
A few things we need to be careful about,

- (How) do we enforce a strict set of pinned dependencies like in the requirements.txt.
  That is currently don't with a hatch pre-install hook
- I think we have files that wouldn't be included in a wheel build (non-python files in `data_safe_haven`)
