### ISSUE TITLE
Workspace lock-screen

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2101]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** develop @ 7b4e6f4
- **Browser details:** Firefox

## :no_entry_sign: Describe the problem

When logging back into a VM with a previously active session, users have to unlock after the login screen, using the same password.

## :steam_locomotive: Workarounds or solutions

This can be disabled with the following (from v4.X.Y)

```
# Disable light-locker which can cause irritating error messages
echo "Hidden=true" >> /etc/xdg/autostart/light-locker.desktop
```

**Comment by JimMadge** [comment]
Workaround in #2128
