### ISSUE TITLE
Add missing DBeaver drivers

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2134]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

DBeaver needs drivers for PostgreSQL and MSSQL or it is essentially unusable.

<img width="611" alt="Screenshot 2024-08-16 at 12 32 41" src="https://github.com/user-attachments/assets/80e07c2f-a5ab-4871-93f1-c7e487b306af">

## :steam_locomotive: How could this be done?

Download and install drivers with ansible. Note this will probably require allowing access to `maven.org` but it might be possible to do with Nexus if #2135 is implemented.

**Comment by JimMadge** [comment]
Work on v4,

- https://github.com/alan-turing-institute/data-safe-haven/issues/1666
- https://github.com/alan-turing-institute/data-safe-haven/pull/1704

It looks fairly involved to 'trick' DBeaver to use drivers that you have installed yourself.
I'm going to quickly try DbGate and BeeKeeper Studio to see if those package the drivers rather than trying to install them from the internet at run time.

**Comment by JimMadge** [comment]
- DBGate
  - Connects to psql
  - Can create tables
  - Seems to have trouble seeing tables/data
- Beekeeper Studio
  - Can connect to psql
  - Can create tables, enter data
  - Can see tables/data

<img width="1266" alt="Screenshot 2024-10-01 at 16 04 21" src="https://github.com/user-attachments/assets/c29d2652-8cb2-4f7c-adde-f34ce318d7c0">

**Comment by jemrobinson** [comment]
Is Beekeeper free? [This](https://www.beekeeperstudio.io/pricing/) implies not. Looks good if it works though.

**Comment by JimMadge** [comment]
Community and paid for versions a bit like DBeaver. The community edition supports a good range of databases though, including postgres and SQL server.

**Comment by jemrobinson** [comment]
Cool - do you have time to make a PR to switch over to this?

**Comment by JimMadge** [comment]
Will do soon. I was just checking SQL Server also works. (getting the details right took a while 😒).

I'll add connection details to the docs.
