### ISSUE TITLE
Improve SSLLabs score

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2137]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

We currently have an "A" score on SSLLabs but this could be improved.

<img width="1005" alt="Screenshot 2024-08-16 at 15 34 46" src="https://github.com/user-attachments/assets/c56f6032-de51-49a5-8ca1-8839619e7317">

## :steam_locomotive: How could this be done?

Add missing features e.g. HSTS

**Comment by JimMadge** [comment]
HSTS is probably easy to support. Should just require adding a parameter to the reverse proxy (application gateway?) serving Guacamole.

**Comment by jemrobinson** [comment]
Done in #2138.
