### ISSUE TITLE
List which regions we support

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2144]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

Some of the resource SKUs we use are only available in some regions. For example:

- [Premium ZRS](https://learn.microsoft.com/en-us/azure/virtual-machines/disks-deploy-zrs?tabs=portal#regional-availability).

## :memo: Required documentation changes

We should list supported regions

**Comment by JimMadge** [comment]
- [NFS file shares (same regional support as premium file shares)](https://learn.microsoft.com/en-us/azure/storage/files/redundancy-premium-file-shares#premium-file-share-accounts)
