### ISSUE TITLE
Cannot launch PyCharm

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2148]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:**  5.0.0
- **Browser details:**

**Comment by craddm** [comment]
![image](https://github.com/user-attachments/assets/b991bf1d-fe89-4b9f-a931-ccd03ae9a694)

This error message was received on startup, after accepting the EUA

Clicking `Reset settings` closes PyCharm and allows you to reopen it successfully. However, after closing PyCharm, you'll get the same error message again next time you open it.

**Comment by craddm** [comment]
This error now seems to be intermittent, possibly after a recent update to PyCharm. Testing today, I got this error on approx 1 in every 5 attempts at starting Pycharm. It doesn't seem necessary to click `Reset settings`

**Comment by JimMadge** [comment]
@craddm Any idea what causes it? Do you want to close this issue or are you working on it?

**Comment by craddm** [comment]
It appears to be something that happens with anything that uses with JetBrains's Intellij platform (e.g. https://youtrack.jetbrains.com/issue/RUBY-33145/Exception-Class-initialization-must-not-depend-on-services.-Consider-using-instance-of-the-service-on-demand-instead) - I'm still trying to find a workaround.

**Comment by craddm** [comment]
I have not been able to find a reliable way to fix this. I would say that it is intermittent, easy to work round, and is more likely to be fixed upstream than by something that we do. It may be worth leaving this issue open so that anyone encountering the problem knows what is happening.

**Comment by JimMadge** [comment]
OK, I'll remove it from any milestones so we can keep tracking without a plan to fix it for the time being.

**Comment by JimMadge** [comment]
@craddm Could add a note to the user docs saying this is a known issue and the workaround.

**Comment by craddm** [comment]
I'm unable to replicate this with the most recent version of PyCharm (2024.2.3), so I think this is no longer an issue.
