### ISSUE TITLE
No access to VMs/workspaces for user

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2195]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** macOS
- **Data Safe Haven version:** [craddm/gitea_external_mirror](https://github.com/craddm/data-safe-haven/tree/gitea_external_mirror)

Note that this branch is up-to-date with `develop` and should not differ from it on any relevant code

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

On a freshly deployed SRE, my user cannot see any workspaces from the guacamole dashboard. The user is in the correct group on Entra ID.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

The `guacamole_user_sync` container is reporting an out-of-memory error during update of the user database

```none
INSERT 0 0
psql:/app/resources/update_users.sql:47: ERROR:  out of memory
INSERT 0 0
INSERT 0 0
INSERT 0 0
2024-09-23T15:54:46+00:00 Finished database synchronisation
Waiting 180 seconds before re-attempting synchronisation
```

</details>

**Comment by JimMadge** [comment]
Possibly related problem,

Guacamole interface

<img width="498" alt="Screenshot 2024-09-27 at 09 49 33" src="https://github.com/user-attachments/assets/f15a21ff-0a60-4060-82db-073cd1dcbe20">

**Comment by jemrobinson** [comment]
@craddm: Can you check whether using `guacamole-user-sync:main` fixes this problem? If it does, I'll tag it and make a PR to DSH.

**Comment by JimMadge** [comment]
@jemrobinson What changes were made in that container?

I'm deploying with a larger memory allocation to guacamole-user-sync to see if that makes a difference 🤞.

**Comment by jemrobinson** [comment]
> What changes were made in that container?

- Full rewrite in Python
- Reduced container size

**Comment by craddm** [comment]
testing now

**Comment by JimMadge** [comment]
Increasing the memory available to the guacamole-user-sync container to 1Gi still gives the OOM error. No workspaces appear.

**Comment by craddm** [comment]
Not working at all:
![image](https://github.com/user-attachments/assets/4fd434d3-f877-4231-aecb-b7d75f95e043)

**Comment by JimMadge** [comment]
I'm getting the same, lots of restarts. Unfortunately you can't see the logs 😶.

**Comment by jemrobinson** [comment]
ldap library isn't properly included in the current Docker image.

**Comment by JimMadge** [comment]
Something @craddm or I can work on in https://github.com/alan-turing-institute/guacamole-user-sync ?

**Comment by jemrobinson** [comment]
Here's the issue https://github.com/alan-turing-institute/guacamole-user-sync/issues/17
