### ISSUE TITLE
Unable to deploy SHM and SRE to different subscriptions

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2201]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:** v5.0.0

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

It is not possibly to deploy a TRE across subscriptions, with SREs deployed to subscriptions not containing their SHM.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

## :recycle: To reproduce

- Deploy an SHM to SubscriptionA
- Attempt to deploy an SRE to SubscriptionB

**Comment by jemrobinson** [comment]
In the `SRENetworkingComponent` we attempt to add a record to the SHM DNS zone. If this is in another subscription, our regular Pulumi provider won't be able to find it - we need to add a separate [Pulumi provider](https://www.pulumi.com/docs/iac/concepts/resources/providers/) in this file that is connected to the SHM subscription.

**Comment by JimMadge** [comment]
Would it be sensible to the the AzureSDK to add DNS records? (Given we have no `SHMProjectManager`)

**Comment by JimMadge** [comment]
Actually, if this works for us a bit of code like [this](https://www.pulumi.com/docs/iac/concepts/resources/providers/#explicit-provider-configuration) looks pretty easy and clean

```python
class MyResource(pulumi.ComponentResource):
    def __init__(self, name, opts):
        instance = aws.ec2.Instance("instance", ..., opts=pulumi.ResourceOptions(parent=self))
        pod = kubernetes.core.v1.Pod("pod", ..., opts=pulumi.ResourceOptions(parent=self))

useast1 = aws.Provider("useast1", region="us-east-1")
myk8s = kubernetes.Provider("myk8s", context="test-ci")
my_resource = MyResource("myResource", pulumi.ResourceOptions(providers={
    "aws": useast1,
    "kubernetes": myk8s,
})
```

**Comment by jemrobinson** [comment]
Doing this with Pulumi *should* be as simple as replacing:

```python
shm_ns_record = network.RecordSet(
            f"{self._name}_ns_record",
            ...
            opts=ResourceOptions.merge(
                child_opts, ResourceOptions(parent=sre_dns_zone)
            ),
        )
```

with

```python
shm_provider = pulumi_azure_native.provider.Provider(subscription_id="shm-subscription-id")
shm_ns_record = network.RecordSet(
            f"{self._name}_ns_record",
            ...
            opts=ResourceOptions.merge(
                child_opts, ResourceOptions(parent=sre_dns_zone, provider=shm_provider)
            ),
        )
```

**Comment by JimMadge** [comment]
Yes, I was worried it would mean creating a new stack _etc._ and making another call to the Pulumi CLI :+1:
