### ISSUE TITLE
Improve naming of persistent data storage accounts

### ISSUE THREAD

**Issue by dsj976** [alan-turing-institute/data-safe-haven#2207]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [x] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

The naming convention of persistent data storage accounts (which follows the pattern `<SHM ID><SRE ID>data<random letters>`), is not very user friendly and can make it easy to confuse storage accounts for SREs with similar IDs. Can the naming convention be improved to make it easier to read?

For example, could the storage account name start with the SRE ID, i.e. could it follow the pattern `<SRE ID><SHM ID>data<random letters>`?

**Comment by dsj976** [comment]
Tagging @cptanalatriste and @helendduncan for more ideas

**Comment by JimMadge** [comment]
Do you only have a problem with the names in v4.*?

They do not follow the same format in >v5

**Comment by jemrobinson** [comment]
They're also bad in v5 though. For example: SHM blue, SRE ultramarine -> `shblusreultsensitivedata`

**Comment by JimMadge** [comment]
We are also working with a fair few restrictions on what is a valid storage account name.

I _think_ it is only alphanumeric, no spaces, no hyphens or underscores (?) _and_ globally unique.

**Comment by JimMadge** [comment]
I don't think there is a clear plan here so I will close the issue.
