### ISSUE TITLE
Changing admin ip address in config does not update network access to storage accounts

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2212]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **managing** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** Debian bookworm
- **Data Safe Haven version:** develop

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

Changing the admin ip address in the configuration of an SRE that has already been deployed does not allow a new admin to modify infrastructure

`dsh sre teardown x` or `dsh sre deploy x` will fail because the admin cannot access files on storage accounts, so pulumi cannot refresh its state before continuing.

The logs show multiple errors like the below

```
~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_ubuntu_pro.yaml refreshing (0s)                          
 ~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_ubuntu_pro.yaml refreshing (0s) error:           
retrieving blob properties "tasks\\ubuntu_pro.yaml" (container "desiredstate" / account "shgresreimsdesiredstate6"): blobs.Client#GetProperties:       
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF           
 ~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_ubuntu_pro.yaml **refreshing failed** error:           
retrieving blob properties "tasks\\ubuntu_pro.yaml" (container "desiredstate" / account "shgresreimsdesiredstate6"): blobs.Client#GetProperties:       
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF           
 ~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_user_config.yaml refreshing (0s)                         
 ~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_user_config.yaml refreshing (0s) error:          
retrieving blob properties "tasks\\user_config.yaml" (container "desiredstate" / account "shgresreimsdesiredstate6"): blobs.Client#GetProperties:      
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF           
 ~  azure-native:storage:Blob sre_desired_state_blob_desired_state_blob_user_config.yaml **refreshing failed** error:          
retrieving blob properties "tasks\\user_config.yaml" (container "desiredstate" / account "shgresreimsdesiredstate6"): blobs.Client#GetProperties:      
Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
```

## :steam_locomotive: Workarounds or solutions

The workaround is to manually add the admin IP addresses to all storage accounts through the portal

**Comment by mattwestby** [comment]
I've not experienced this, i updated the ip addresses though in the SRE config file and then reupload the config file and when you do a redeploy it corrects it in the firewall ist on the storage account.

**Comment by jemrobinson** [comment]
@mattwestby : Did you do a redeploy from an IP address that was already allowed though?

**Comment by mattwestby** [comment]
> Did you do a redeploy from an IP address that was already allowed though?

No, it wasn’t already in the list no.

**Comment by jemrobinson** [comment]
And was it an IP address belonging to Azure?

**Comment by mattwestby** [comment]
No was my personal internet public ip.

**Comment by craddm** [comment]
For me that is exactly what didn't work. Wondering if it's possible that pulumi was picking up things that needed to change after I'd pulled some recent code updates.

**Comment by mattwestby** [comment]
Wonder whether this is the same thing that is happening with me and the ssl cert creation, pulumi not always picking up changes?

**Comment by JimMadge** [comment]
@craddm Can you clarify the steps you took here?

If you are saying you can't refresh from an IP that is not allowed, then I think that is not a bug.
If you are saying that it isn't possible to update the allowed IP addresses, then that does sound like a bug.

**Comment by craddm** [comment]
@JimMadge 

1) Deployed SRE from one IP address
2) Tried to teardown SRE from a different IP address, which failed because it wasn't an allowed IP address
3) Added the IP address in the config for the SRE and uploaded the new config
4) Tried to teardown the SRE again, which failed with the errors reported above (which are because the IP address was not allowed on the storage account)
5) Tried to run `dsh sre deploy x`, in the hope it would update the IP addresses on the storage accounts, which failed with the errors reported above
6) Tore down the SRE from the original IP address

**Comment by JimMadge** [comment]
I think that is working as expected. The change to the allowed IP address was never applied, just uploaded to the remote configuration.

**Comment by craddm** [comment]
> I think that is working as expected. The change to the allowed IP address was never applied, just uploaded to the remote configuration.

So how should the change to the allowed IP address be applied?

**Comment by JimMadge** [comment]
`dsh config upload ... && dsh sre deploy ...`. In the same way as all changes.

**Comment by craddm** [comment]
> `dsh config upload ... && dsh sre deploy ...`. In the same way as all changes.

As per step 5, I got the same error from running `dsh sre deploy ...`

It may be that you have to run this from the original IP address first, which should be documented if so

**Comment by JimMadge** [comment]
Yes, that is what I mean, that is expected. The infrastructure hasn't been updated to allow access to the storage accounts from the new IP address, we should expect deploy/teardown to fail when Pulumi attempts to modify the blobs/blob containers/_etc._.

I feel like what you are saying is the same as "I can't access a storage account from an IP address I've blocked", so this all feels quite natural to me.

What do you think should be different?

**Comment by craddm** [comment]
> Yes, that is what I mean, that is expected. The infrastructure hasn't been updated to allow access to the storage accounts from the new IP address, we should expect deploy/teardown to fail when Pulumi attempts to modify the blobs/blob containers/_etc._.
> 
> I feel like what you are saying is the same as "I can't access a storage account from an IP address I've blocked", so this all feels quite natural to me.
> 
> What do you think should be different?

You just said that I should have done `dsh config upload ... && dsh sre deploy ....` to apply the change to the allowed IP addresses. I tried that, and it failed. It never updated the allowed IP addresses. It never got that far, failing because it tried to modify things on the storage accounts before it changed the allowed IP addresses. 

If the point is that I should have changed the config and then deployed *from the original IP address*, then yes, and that should be made clearer in the documentation. A naive user might think "well I changed what IP addresses are allowed so why isn't it working?"

**Comment by mattwestby** [comment]
when you do the dsh config upload does it show you its removing the "old" ip address and adding the "new" one? Are you making the change in the sre yaml config file first?

**Comment by craddm** [comment]
> when you do the dsh config upload does it show you its removing the "old" ip address and adding the "new" one? Are you making the change in the sre yaml config file first?

I added the new address but didn't remove the old ip address.

**Comment by mattwestby** [comment]
ah ok in my config file i only had 1 ip address allowed.

**Comment by JimMadge** [comment]
> If the point is that I should have changed the config and then deployed from the original IP address, then yes, and that should be made clearer in the documentation. A naive user might think "well I changed what IP addresses are allowed so why isn't it working?"

OK, I think we are starting to go around in circles.
I don't find anything here confusing or surprising,

- The allowed IP address were _not_ updated, they were just pushed to the remote config
- Some of the Pulumi operations will fail if the requests don't come from an allowed IP address

So I'm not sure what you think should be different (or if you think this is a bug), is it

- A way to update allowed IP addresses outside of Pulumi
- Try to constrain Pulumi to update allowed IP addresses before modifying blobs _etc._
- Some documentation (in which case, what does it say?)

**Comment by craddm** [comment]
> * Some documentation (in which case, what does it say?)

"When changing the permitted admin or data owner IP addresses for a deployed SRE in the SRE configuration file, you must run `dsh sre deploy ...` from the originally permitted IP address after uploading the updated configuration file. You cannot update the allowed IP addresses from the new IP address."

**Comment by craddm** [comment]
I think my point is that ok, this is intended behaviour, but it isn't completely obvious to anyone who isn't very dsh-brained.

**Comment by JimMadge** [comment]
@craddm OK, can you open a PR.

We might want to be careful with the wording to balance being helpful with not being misleading. I don't think what you've said above is quite correct.

It might help to add a section (if there isn't one already) explaining the workflow of updating an SRE. Uploading a configuration does not apply any changes itself, only when running deploy.
