### ISSUE TITLE
Invalid data collection rule error during deployment

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2220]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** Debian bookworm
- **Data Safe Haven version:** develop

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

Initial deployment sometimes fails during setting up of the data collection rule for monitoring of VMs. The error message states that the relevant output tables do not exist in the log workspace.

Running `dsh sre deploy ...` again completes deployment successfully.

I think this may be a race condition - the process creating the DCR sometimes runs before the log workspace is finished setting up.

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

![Screenshot 2024-10-03 at 12 24 37](https://github.com/user-attachments/assets/937539de-85e2-43c2-b89d-f86f4fd41760)

</details>

## :recycle: To reproduce

Deploy an SRE

**Comment by jemrobinson** [comment]
If you can work out which resource A actually depends on resource B, you can add a `depends_on` that will ensure they get deployed in the correct order.

**Comment by JimMadge** [comment]
@craddm Have you seen this one again recently?

**Comment by craddm** [comment]
No - I did see it a couple of times before I reported it, but not since.

**Comment by JimMadge** [comment]
OK, do you want to close this as could not reproduce, or add a depends on in case this is a rare (but possible) bug?

**Comment by craddm** [comment]
Feels to me like it would be best to add a depends_on, just in case. And we need to revisit monitoring code soon anyway

**Comment by craddm** [comment]
Adding a `depends_on` did not fix this. I think we can depend on the creation of the log workspace, but that it still takes a while after the log workspace is created for the table to be created, so we can still get this failure on an initial run. Running the deployment again a minute or two later successfully completes.

I've seen a similar report for [Terraform](https://github.com/hashicorp/terraform-provider-azurerm/issues/21897)

**Comment by JimMadge** [comment]
Can we create the tables with Pulumi so that the rule depends on the table existing?

There is a resource for tables in [azure native](https://www.pulumi.com/registry/packages/azure-native/api-docs/operationalinsights/)

**Comment by jemrobinson** [comment]
... or if not, you might be able to [`get_table`](https://www.pulumi.com/registry/packages/azure-native/api-docs/operationalinsights/gettable/) and depend on that.

**Comment by craddm** [comment]
These are MS default tables, so doubt we can create them under Pulumi. I'll try some other variation on the theme (like get_table)

**Comment by JimMadge** [comment]
Any reason we use the default tables? Would making our own tables fix the problem?

**Comment by JimMadge** [comment]
Some references

- [data flow arguments](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/datacollectionrule/#dataflow)

**Comment by craddm** [comment]
Although I was quite frequently encountering this problem in the past, I have not encountered it again over the last month or so. I'll close this for now and reopen if it happens again.
