### ISSUE TITLE
Desktop icons link to incorrect locations

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2225]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** Debian bookworm
- **Data Safe Haven version:** develop
- **Browser details:** chrome

## :no_entry_sign: Describe the problem

The desktop icons point to the `input`, `output`, and `shared` drives point to the wrong locations

![image](https://github.com/user-attachments/assets/cbe51de3-9620-42e6-85eb-f341acc5cd81)

## :steam_locomotive: Workarounds or solutions

Update them to link to the correct locations

**Comment by JimMadge** [comment]
Yes, those are the old locations.

The Desktop files are defined [here](https://github.com/alan-turing-institute/data-safe-haven/tree/develop/data_safe_haven/resources/workspace/ansible/files/etc/skel/Desktop).
