### ISSUE TITLE
Better explanation of domain setup

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2228]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

The instructions about how to register a domain are very opaque. They also conflate the idea of "I own this domain" with "Entra is allowed to register users with this in their user name".

We should change these to something more user-friendly, e.g. 

```
- "Domain 'mytre.example.org' is not registered
- You need to register 'mytre' with 'example.org'
- Create a new NS record for 'example.org'
- Add the following records ...
```

**Comment by JimMadge** [comment]
I'm not sure where this is. Is that part of the documentation or are these messages from the CLI?

**Comment by jemrobinson** [comment]
The current CLI output around setting up the SHM DNS zone is quite opaque and doesn't explain what to do if you don't already understand DNS. We should fix that CLI output so that it's more clear, but I don't think we need to change the underlying logic.

**Comment by JimMadge** [comment]
@jemrobinson could you put links to those lines here?

**Comment by jemrobinson** [comment]
It's this function: https://github.com/alan-turing-institute/data-safe-haven/blob/727f43d6f161494b4e132e068e3a7da9873684be/data_safe_haven/external/api/graph_api.py#L1019-L1078

**Comment by jemrobinson** [comment]
I'm not 100% sure what the best set of messages would be. The rough logic in this function is:

- **Entra step** `self.read_domains()` checks which domains have been registered with Entra as ones we want to use
- **DNS step** the `while True` loop then tries to resolve `domain_name` from your local machine and, if it exists, checks that its nameservers are pointing to the expected set of `ns*.azure*` nameservers
  - if yes, then we break out of the loop
  - **DNS step** if no, then we ask the user to make sure that e.g. `my-subdomain.my-domain.com` is correctly delegated by `my-domain.com` (i.e. that there is an NS record at `my-domain.com` that says "ask these Azure nameservers if you need to know about `my-subdomain`)
- **Entra step** we send a POST request to Entra asking it to verify ownership of `my-subdomain.my-domain.com` so that we can create users `@my-subdomain.my-domain.com`. It does this by adding a TXT record to `my-subdomain.my-domain.com` (which we know is hosted on Azure)

I wonder whether in the longer term we should separate the DNS and Entra steps into two different functions?
