### ISSUE TITLE
Support "Internet" as a valid IP address in the config file

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#2229]
## :white_check_mark: Checklist

- [ ] I have searched open and closed issues for duplicates.
- [ ] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [ ] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [ ] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

Support "Internet" as a valid IP address in the config file

**Comment by JimMadge** [comment]
@jemrobinson You've made an infinite loop 🤯

**Comment by JimMadge** [comment]
As the config values are parsed as IP ranges, can we use something like `*` or `0.0.0.0/0`?

**Comment by JimMadge** [comment]
For the user IP address ranges,

https://github.com/alan-turing-institute/data-safe-haven/blob/eede40fdaf43094b6e3ebe2c49ce63073c9893b7/data_safe_haven/infrastructure/programs/declarative_sre.py#L144-L163

https://github.com/alan-turing-institute/data-safe-haven/blob/eede40fdaf43094b6e3ebe2c49ce63073c9893b7/data_safe_haven/infrastructure/programs/sre/networking.py#L119-L130

The Pulumi Azure Native parameter `source_address_prefixes` [should accept IP addresses, CIDR ranges, '*' and Azure tags](https://www.pulumi.com/registry/packages/azure-native/api-docs/network/securityrule/#source_address_prefixes_python).

_Our_ config validation will reject anything but IPV4 addresses or IPV4 address ranges.

**Comment by JimMadge** [comment]
`0.0.0.0/0` works, but that may be more permissive than we would want.
