### ISSUE TITLE
Pulumi using wrong Python/Python path in pipx install

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2239]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** 
- **Data Safe Haven version:** 

## :package: Packages

<details>
<summary>List of packages</summary>

```none
Paste list of packages here
```

</details>

## :no_entry_sign: Describe the problem

After pipx install, when calling `dsh` Pulumi will look for a Python interpreter and find system Python, not the Python venv with all of the dependencies. It will fail because of missing packages.

On option to fix,
[can declare venv path](https://www.pulumi.com/docs/iac/languages-sdks/python/#pypi-packages) in Pulumi package settings.
We set these [here](https://github.com/alan-turing-institute/data-safe-haven/blob/53058974451dc0febb535d594e4849b74067f4b2/data_safe_haven/infrastructure/project_manager.py#L86)

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
Your log details here
```

</details>

**Comment by craddm** [comment]
There is an environment variable we can set to tell Pulumi to use a specific python version: `PULUMI_PYTHON_CMD` - see https://www.pulumi.com/docs/iac/cli/environment-variables/
