### ISSUE TITLE
Enhance the teardown documentation for clarity

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#2252]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

https://data-safe-haven.readthedocs.io/en/develop/management/index.html#removing-a-deployed-data-safe-haven

## :memo: Required documentation changes

- Explain a bit more exactly what will happen when running `dsh sre teardown YOUR_SRE_NAME` or `dsh shm teardown` so System Managers new to DSH don't delete things without meaning
- Add some big scary warnings, especially to the SHM teardown part saying "deleting this will affect all SREs" etc
- I'm not sure if in DSH v5 the storage account is now falling under the SRE resources as oppose to the SHM subscription (as was the case in v4)? If so, also add big scary warning saying data will be deleted by SRE teardown (unless this is not the case, in which case explain that)

**Comment by craddm** [comment]
On this note, maybe we should be preventing the SHM from being torn down if any SREs are still deployed... or at least give a warning

**Comment by jemrobinson** [comment]
+1 for prevention (with an error message explaining why).

**Comment by edwardchalstrey1** [comment]
> On this note, maybe we should be preventing the SHM from being torn down if any SREs are still deployed... or at least give a warning

Also, perhaps in both teardown scripts multiple "Are you sure you really want to do this" prompts

**Comment by JimMadge** [comment]
@craddm Shall I take this one so you can focus on #2146?

**Comment by craddm** [comment]
Made some edits in #2254

**Comment by JimMadge** [comment]
Great 🚀.

I think the other thing to do is make some code changes,

- adding an extra prompt for the user to confirm teardown
- blocking teardown of SHM if SREs are deployed

We can do that in another PR. I would be happy bumping that to 5.0.2, what do you think?
