### ISSUE TITLE
Update recommended VM in docs

### ISSUE THREAD

**Issue by helen-d-little** [alan-turing-institute/data-safe-haven#2271]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates
- [x] This is a request for a change to documentation
- [x] This isn't a feature request or bug report
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :ledger: Where is the problem?

The `Standard_D8s_v6` VM is not available on the current SHM subscription. The [docs](https://github.com/alan-turing-institute/data-safe-haven/blob/latest/docs/source/deployment/deploy_sre.md) suggest to use it VM
## :memo: Required documentation changes

Update to VM that is available for the current subscription - (`Standard_D8s_v4` and `Standard_D8s_v5` are available)

**Comment by jemrobinson** [comment]
While this is true for the subscription you're using, I'm not sure this SKU is unavailable in general.

**Comment by JimMadge** [comment]
The [docs](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/general-purpose/dsv6-series?tabs=sizebasic) say Dsv6 is in preview, which I assume means not generally available.
