### ISSUE TITLE
Syslogs and performance counters are not being collected 

### ISSUE THREAD

**Issue by craddm** [alan-turing-institute/data-safe-haven#2273]
The current supported method of collecting syslogs and performance counters from VMs is to use data collection rules to funnel the data from Azure Monitoring Agent ([AMA data collection](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-data-collection)).

We setup our data collection rules and endpoints according to the latest guidance, but the data is not being collected. 

An alternative is to use diagnostic settings, which do successfully collect data when set up through the portal - https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings

**Comment by JimMadge** [comment]
So, diagnostic settings are not part of the 'new' logging solution?

We can create [diagnostic settings with pulumi azure-native](https://www.pulumi.com/registry/packages/azure-native/api-docs/insights/diagnosticsetting/).

**Comment by JimMadge** [comment]
Is there a workaround we could put in the docs immediately?
