### ISSUE TITLE
Show the Guacamole URL on the terminal after creating an SRE

### ISSUE THREAD

**Issue by cptanalatriste** [alan-turing-institute/data-safe-haven#2274]
## :white_check_mark: Checklist

- [ ] I have searched open and closed issues for duplicates.
- [ ] This is a request for a new feature in the Data Safe Haven or an upgrade to an existing feature.
- [ ] The feature is still missing in the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [ ] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [ ] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :strawberry: Suggested change

When SRE creation finishes successfully, it would be nice to see the Guacamole URL printed on the terminal, to go ahead and check the SRD. Maybe it would also be good to see some "next steps" (i.e. user enrollment,...)

## :steam_locomotive: How could this be done?

Send the information to standard output, maybe?

**Comment by JimMadge** [comment]
The sre FQDN is an output of `SRENetworkingComponent`

https://github.com/alan-turing-institute/data-safe-haven/blob/40089a677f809c0017a0990945ffe07a6d7d67f5/data_safe_haven/infrastructure/programs/sre/networking.py#L1973

If we exported it from the Pulumi stack here

https://github.com/alan-turing-institute/data-safe-haven/blob/40089a677f809c0017a0990945ffe07a6d7d67f5/data_safe_haven/infrastructure/programs/declarative_sre.py#L419-L423

I think we should be able to print it.
