### ISSUE TITLE
Add blob storage logs

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#2309]
Part of #1922

**Comment by JimMadge** [comment]
Easy to set up in the portal.

Having a little trouble getting the resource uri for the diagnostic setting correct in Pulumi.
It seems that the diagnostic setting we want doesn't apply to either the storage account or blob container.
Instead, it belongs to the `blobServices` of the storage account.

(Storage accounts do support diagnostic settings but they only have metrics, not logs on data events).

**Comment by craddm** [comment]
Had that same problem - `resource_uri=props.storage_account_id.apply(lambda v: f"{v}/blobServices/default")` fixed it. Need the `/default` on the end.

**Comment by JimMadge** [comment]
@craddm Yeah, that looked to be the URI. I think I tried that and it didn't work but I'll have another look.

Where did you use that?

**Comment by JimMadge** [comment]
@craddm That was right :tada:!
The error I had was because I had deployed a diagnostic setting in the portal to test which conflicted with what I had put in Pulumi.

Thanks for the nudge or I might have not noticed 👍.
