### ISSUE TITLE
Redirect HTTP to HTTPS when connecting to RDS webclient

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/data-safe-haven#361]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **using** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Data Safe Haven version:** 0.3.0-beta
- **Browser details:** All
- **Operating system details:** All

## :no_entry_sign: Describe the problem

The Microsoft Remote Desktop gateway can only be accessed over `https` but we do not currently run an HTTP->HTTPS upgrade route. This means that users must explicitly type `https` rather than `http`. 

## :steam_locomotive: Workarounds or solutions

- Add an `nginx` instance in front of the RDS server
- Use an application gateway

**Comment by craddm** [comment]
Closed as MS RDS is now removed, as of merging of #1535 into develop (see also #1159)
