### ISSUE TITLE
Deploy web applications (GitLab and HackMD) different sign in methods

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/data-safe-haven#698]
> * I'm into the Hackmd, using the long form of my username (is there a reason this is different?).

> I think I know where this is specified, but can you open an issue for it?

_Originally posted by @jemrobinson in https://github.com/alan-turing-institute/data-safe-haven/issues/686#issuecomment-644191846_

After installing gitlab and hackmd to an SRE Data server, you can access them on the webclient. Oddly, the way you login to each of them is different.

For Gitlab, you use the shortform user name of one of the users in the `SG <SRE ID> Research Users` security group. For me, this was `kxutest`.

Whilst for Hackmd, we use the longform username. For me this is `kxutest@testc.dsgroupdev.co.uk`. 

For ease of use it might make sense for them to use the same login details.

**Comment by jemrobinson** [comment]
This was done in #908.
