### ISSUE TITLE
Fix hyphens in SRE name

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#799]
#### Description
If the SRE name has a hyphen in it then this will also form part of the storage account names. This is not allowed

#### Desired behaviour
One of:
- Throw an exception for SRE names containing hyphens
- Remove hyphens from SRE names (silently or with a message)
- Remove hyphens from storage account names(silently or with a message)

#### To reproduce
Attempt to deploy an SRE using an SRE ID that contains a hyphen

#### Tasks
- [ ] Decide which of the above options is best and implement it

**Comment by jemrobinson** [comment]
Is this still a problem in Powershell?

**Comment by craddm** [comment]
Still a problem. We already automatically force the name to lower-case, but modifying it by removing characters feels a little more dicey.

**Comment by JimMadge** [comment]
I think removing or changing to another, valid character is fine so long as it is clear in the code and done consistently.

In any case, if we know that there are invalid characters we should validate or adjust the inputs.

**Comment by craddm** [comment]
Removing the character is easy - so do we do it only for the storage account or for the SRE as a whole? I would include a message to say it's being done.

**Comment by craddm** [comment]
Removing the character is easy - so do we do it only for the storage account or for the SRE as a whole? I would include a message to say it's being done.

**Comment by craddm** [comment]
Removing the character is easy - so do we do it only for the storage account or for the SRE as a whole? I would include a message to say it's being done.

**Comment by JimMadge** [comment]
I think either is fine.

**Comment by craddm** [comment]
Actually, is there any reason not to do this for SHMs as well?

**Comment by JimMadge** [comment]
Which part of the SHM? The storage accounts?

**Comment by craddm** [comment]
Either just the storage accounts or just overall, as with the SREs. We'd have the same problem with the SHM if people used a hyphen there.

**Comment by JimMadge** [comment]
Ok, in that case, let's have the same solution for both.

I don't have a strong opinion about changing all names or just storage accounts.
It is just important to apply the transformation (or reject configurations with hyphens) consistently.

@craddm Do you want to assign yourself to this?
