### ISSUE TITLE
Automate GitLab export

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#832]
#### :scroll: Description
Currently exporting GitLab repos is a manual process involving:

- accessing each repository from inside the Safe Haven
- for each branch that needs to be exported doing the following:
  - use the web interface to "download as ZIP"
  - save the zip file with an appropriate name (eg. `<username>-<repo name>-<branch name>.zip`
- save all of these zip files to `/output`

#### :strawberry: Desired behaviour
Even with the constraints that GitLab can only be accessed from inside the Safe Haven, it would be nice if the above could be scripted - either on the DSVM or on the GitLab VM.

#### :page_facing_up: Tasks
- [ ] Decide on the best way to script this
- [ ] Do it

**Comment by jemrobinson** [comment]
Is this something we want to do in Powershell? If not, does the issue also apply to Gitea in Pulumi?

**Comment by craddm** [comment]
Removed this from the `4.2.0` milestone - won't implement in the Powershell version.

**Comment by JimMadge** [comment]
[Gitea backup and restore docs](https://docs.gitea.com/next/administration/backup-and-restore)

> Inside the gitea-dump-1482906742.zip file, will be the following:
>
> - app.ini - Optional copy of configuration file if originally stored outside the default custom/ directory
> - custom/ - All config or customization files in custom/.
> - data/ - Data directory (APP_DATA_PATH), except sessions if you are using file session. This directory includes attachments, avatars, lfs, indexers, SQLite file if you are using SQLite.
> - **repos/ - Complete copy of the repository directory.**
> - gitea-db.sql - SQL dump of database
> - log/ - Various logs. They are not needed for a recovery or migration.
