### ISSUE TITLE
Rotation of SAS tokens

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/data-safe-haven#895]
#### :scroll: Description
We currently use SAS tokens in a few places, most notably for accessing the ingress and egress storage accounts from inside the SRE. These have a default lifetime of 1 year. We need to work out a process for retiring/rotating these tokens that is as seamless as possible.

#### :strawberry: Desired behaviour
A procedure for rotating SAS tokens has been implemented.

**Comment by craddm** [comment]
Options:
1. automate or semi-automate rotation
2. Document that tokens will need to be refreshed after 1 year.

**Comment by JimMadge** [comment]
New SAS tokens, valid for 1 year, are created and put into a KeyVault whenever `Setup_SRE_Storage_Accounts.ps1` is run,

https://github.com/alan-turing-institute/data-safe-haven/blob/01725bf5f461f7a4bb584481c69dd330f8557cb5/deployment/secure_research_environment/setup/Setup_SRE_Storage_Accounts.ps1#L61-L74

systemd units for mounting blob stores are defined in cloud-init,

https://github.com/alan-turing-institute/data-safe-haven/blob/01725bf5f461f7a4bb584481c69dd330f8557cb5/deployment/secure_research_environment/cloud_init/cloud-init-srd.mustache.yaml#L259-L274

which call mount scripts,

https://github.com/alan-turing-institute/data-safe-haven/blob/01725bf5f461f7a4bb584481c69dd330f8557cb5/deployment/secure_research_environment/cloud_init/cloud-init-srd.mustache.yaml#L422-L431

which read credentials from a files, also defined in cloud-init,

https://github.com/alan-turing-institute/data-safe-haven/blob/01725bf5f461f7a4bb584481c69dd330f8557cb5/deployment/secure_research_environment/cloud_init/cloud-init-srd.mustache.yaml#L382-L388

That means that though new tokens will be generated, SRDs will continue to use old credentials.

Options could be,

1. Manually edit files 😬
2. Advise to regenerate tokens and redeploy SRDs (which would prompt fetching the latest token from the KeyVault)
3. Add Script to
    1. Generate new SAS tokens
    2. Write those tokens to and SRD (or SRDs)

**Comment by jemrobinson** [comment]
Another option is to increase the token lifetime. If we also provide instructions about how to manually regenerate tokens, I think that would cover the use-cases where shorter tokens are preferable. We should check that DSPT doesn't make this a requirement, but I think it doesn't.

**Comment by JimMadge** [comment]
Thoughts @craddm @jemrobinson?

I recall that touching the file system is awkward (no SSH), so the process is "complete a template script to change something, then run that remotely using the Azure API"? Not sure if 3. will be too much hassle for an edge case.

I think it would be good at least to pull out the code that generates new SAS tokens to save people rerunning the whole storage deployment script.

**Comment by jemrobinson** [comment]
If you want to pull something out, it should be code that does the following:

- generates new SAS tokens
- stores them in the KeyVault
- iterates over deployed SRDs and updates the appropriate files (`/opt/configuration/credentials-ingress.secret` and `/opt/configuration/credentials-egress.secret`)
