### ISSUE TITLE
Nexus password in plain text

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/data-safe-haven#921]
The way that we call the Python script to configure Nexus using its API

https://github.com/alan-turing-institute/data-safe-haven/blob/aa24fc74ee2a2d6873230ccec172d2f5db24a242/deployment/safe_haven_management_environment/cloud_init/cloud-init-nexus.yaml#L60

means that the cloud-init cloud config file remains on the Nexus VM with the Nexus app's admin password in plain text (`/var/lib/cloud/instance/user_data.txt`).

This file is only readable by root and users are not indented to log into this machine, so the risk seems relatively low. Still, this feels like bad practice.

**Comment by craddm** [comment]
Removed from `4.2.0` milestone - no longer an issue in Pulumi
